### ISSUE TITLE
[Bug] TypeError: object of type 'NoneType' has no len() on L40S

### ISSUE THREAD

**Issue by zhyncs** [sgl-project/sglang#1023]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.

### Describe the bug

related https://github.com/sgl-project/sglang/pull/1021 cc @hnyls2002 
```
Exception in ModelTpServer:
Traceback (most recent call last):
  File "/sglang/python/sglang/srt/managers/tp_worker.py", line 221, in exposed_step
    self.forward_step()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sglang/python/sglang/srt/managers/tp_worker.py", line 233, in forward_step
    new_batch = self.get_new_prefill_batch()
  File "/sglang/python/sglang/srt/managers/tp_worker.py", line 391, in get_new_prefill_batch
    req.init_next_round_input()
  File "/sglang/python/sglang/srt/managers/schedule_batch.py", line 169, in init_next_round_input
    self.extend_input_len = len(self.fill_ids) - len(self.prefix_indices)
TypeError: object of type 'NoneType' has no len()

Exception in ControllerSingle:
Traceback (most recent call last):
  File "/sglang/python/sglang/srt/managers/controller_single.py", line 166, in start_controller_process
    controller.loop_for_forward()
  File "/sglang/python/sglang/srt/managers/controller_single.py", line 103, in loop_for_forward
    out_pyobjs = self.tp_server.exposed_step(recv_reqs)
  File "/sglang/python/sglang/srt/managers/tp_worker.py", line 221, in exposed_step
    self.forward_step()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sglang/python/sglang/srt/managers/tp_worker.py", line 233, in forward_step
    new_batch = self.get_new_prefill_batch()
  File "/sglang/python/sglang/srt/managers/tp_worker.py", line 391, in get_new_prefill_batch
    req.init_next_round_input()
  File "/sglang/python/sglang/srt/managers/schedule_batch.py", line 169, in init_next_round_input
    self.extend_input_len = len(self.fill_ids) - len(self.prefix_indices)
TypeError: object of type 'NoneType' has no len()

Killed
```

### Reproduction

```bash
git clone https://github.com/sgl-project/sglang.git
cd sglang
pip install --upgrade pip
pip install -e "python[all]"
pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/

python3 -m sglang.launch_server --model meta-llama/Meta-Llama-3.1-8B-Instruct --port 8413 --disable-radix-cache

python3 -m sglang.bench_serving --backend sglang --port 8413 --dataset-name random --num-prompts 500 --random-input 4096 --random-output 2048
```

### Environment

```Shell
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
GPU 0: NVIDIA L40S
GPU 0 Compute Capability: 8.9
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.54.15
PyTorch: 2.4.0+cu121
flashinfer: 0.1.4+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.3
aiohttp: 3.10.3
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 23.2
PIL: 10.2.0
psutil: 5.9.8
pydantic: 2.8.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 24.0.1
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.3
anthropic: 0.33.0
NVIDIA Topology:
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      64-127,192-255  1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576
```

**Comment by zhyncs** [comment]
fixed with https://github.com/sgl-project/sglang/pull/1031 @merrymercy 

```
============ Serving Benchmark Result ============
Backend:                                 sglang
Traffic request rate:                    inf
Successful requests:                     500
Benchmark duration (s):                  633.20
Total input tokens:                      1011340
Total generated tokens:                  521571
Total generated tokens (retokenized):    521933
Request throughput (req/s):              0.79
Input token throughput (tok/s):          1597.19
Output token throughput (tok/s):         823.71
----------------End-to-End Latency----------------
Mean E2E Latency (ms):                   339618.33
Median E2E Latency (ms):                 339943.24
---------------Time to First Token----------------
Mean TTFT (ms):                          258089.69
Median TTFT (ms):                        251119.93
P99 TTFT (ms):                           541583.10
-----Time per Output Token (excl. 1st token)------
Mean TPOT (ms):                          88.54
Median TPOT (ms):                        80.40
P99 TPOT (ms):                           143.26
---------------Inter-token Latency----------------
Mean ITL (ms):                           78.26
Median ITL (ms):                         69.47
P99 ITL (ms):                            386.83
==================================================
```
