### ISSUE TITLE
OOM after flush_cache when flashinfer is enabled

### ISSUE THREAD

**Issue by comaniac** [sgl-project/sglang#109]
When benchmarking my serving workloads, I found the following pattern will constantly cause OOM error:

1. Launch a container with SRT and flashinfer enabled.
2. Benchmark with 800 requests.
3. Call `http://0.0.0.0:25000/flush_cache` and confirm the cache is flushed in the SRT log.
4. Benchmark with 800 requests again.

The above steps result in the following error in the middle of the second benchmarking:

```
CUDA Error: out of memory (2) /sglang/3rdparty/flashinfer/include/flashinfer/handler.cuh: line 100 at function cudaMallocAsync(&float_buffer_, sizeof(float) *
 tmp_size, stream_)
Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/sglang/python/sglang/srt/managers/router/model_rpc.py", line 165, in exposed_step
    self.forward_step()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/sglang/python/sglang/srt/managers/router/model_rpc.py", line 192, in forward_step
    self.forward_decode_batch(self.running_batch)
  File "/sglang/python/sglang/srt/managers/router/model_rpc.py", line 428, in forward_decode_batch
    logits = self.model_runner.forward(batch, ForwardMode.DECODE)
  File "/sglang/python/sglang/srt/managers/router/model_runner.py", line 473, in forward
    return self.forward_decode(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/sglang/python/sglang/srt/managers/router/model_runner.py", line 395, in forward_decode
    input_metadata = InputMetadata.create(
  File "/sglang/python/sglang/srt/managers/router/model_runner.py", line 216, in create
    ret.init_flashinfer_args(tp_size)
  File "/sglang/python/sglang/srt/managers/router/model_runner.py", line 128, in init_flashinfer_args
    self.decode_wrapper.begin_forward(
  File "/usr/local/lib/python3.10/dist-packages/flashinfer/ops/__init__.py", line 523, in begin_forward
    self._wrapper.begin_forward(
RuntimeError: BatchDecodeWithPagedKVCache failed with error out of memory
```

Not sure whether it's caused by the memory leak when flushing cache. @hnyls2002 do you have an idea?

**Comment by hnyls2002** [comment]
That's strange. I am unsure whether the flush cache function conflicts with Flashinfer's kernels. I will check it soon.

**Comment by hnyls2002** [comment]
@comaniac After updating the `flashinfer` into its wheel edition, I didn't come across the OOM problem after flushing the cache as you described. Could you please check again to make sure this bug is temporarily fixed?

**Comment by comaniac** [comment]
I just did the same test as before with the latest SGLang as FlashInfer. The issue is no longer happening so we should be able to close it for now.
