### ISSUE TITLE
Issue with running example with Mixtral AWQ

### ISSUE THREAD

**Issue by davidsyoung** [sgl-project/sglang#110]
Hey, 

Not sure if I'm doing something silly on my end, but I said I would submit an issue to get some help. Hope that's okay. 2x 3090 GPU. 

I am running with the following Dockerfile:

```
FROM pytorch/pytorch:2.1.1-cuda12.1-cudnn8-devel

RUN apt update && apt dist-upgrade -y

RUN pip install --upgrade pip
RUN pip install "sglang[all]"

WORKDIR /

COPY . . 

EXPOSE 30000

CMD ["/bin/bash","-c","python -m sglang.launch_server --model-path /models/TheBloke_Nous-Hermes-2-Mixtral-8x7B-DPO-AWQ/ --tokenizer-path /models/TheBloke_Nous-Hermes-2-Mixtral-8x7B-DPO-AWQ/ --port 30000 --host 192.168.1.55 --tp-size 2"]
```

Here is the test example I have ran (also tried simple curl with same outcome):
```
from sglang import function, system, user, assistant, gen, set_default_backend, RuntimeEndpoint

@function
def multi_turn_question(s, question_1, question_2):
    s += system("You are a helpful assistant.")
    s += user(question_1)
    s += assistant(gen("answer_1", max_tokens=256))
    s += user(question_2)
    s += assistant(gen("answer_2", max_tokens=256))

set_default_backend(RuntimeEndpoint("http://192.168.1.55:30000"))

state = multi_turn_question.run(
    question_1="What is the capital of the United States?",
    question_2="List two local attractions.",
)

for m in state.messages():
    print(m["role"], ":", m["content"])

print(state["answer_1"])
```

The following is the full log, including error that hangs the process:

```
==========
== CUDA ==
==========

CUDA Version 12.1.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
server started on [0.0.0.0]:10005
server started on [0.0.0.0]:10004
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
accepted ('127.0.0.1', 55998) with fd 5
welcome ('127.0.0.1', 55998)
accepted ('127.0.0.1', 41050) with fd 5
welcome ('127.0.0.1', 41050)
Rank 0: load weight begin.
Rank 1: load weight begin.
quant_config: AWQConfig(weight_bits=4, group_size=128, zero_point=True)
quant_config: AWQConfig(weight_bits=4, group_size=128, zero_point=True)
Rank 1: load weight end.
Rank 0: load weight end.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Rank 1: max_total_num_token=135847, max_prefill_num_token=32768, context_len=32768, model_mode=[]
Rank 0: max_total_num_token=135847, max_prefill_num_token=32768, context_len=32768, model_mode=[]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://192.168.1.55:30000 (Press CTRL+C to quit)
INFO:     192.168.1.6:34408 - "GET /get_model_info HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 0. #new_token: 27. #remaining_req: 0. #running_req: 0
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/router/manager.py", line 79, in start_router_process
    loop.run_until_complete(router.loop_for_forward())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/router/manager.py", line 38, in loop_for_forward
    out_pyobjs = await self.model_client.step(next_step_input)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 516, in _func
    await asyncio.gather(*[asyncio.to_thread(t.wait) for t in tasks])
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/rpyc/core/async_.py", line 51, in wait
    self._conn.serve(self._ttl)
  File "/opt/conda/lib/python3.10/site-packages/rpyc/core/protocol.py", line 438, in serve
    data = self._channel.poll(timeout) and self._channel.recv()
  File "/opt/conda/lib/python3.10/site-packages/rpyc/core/channel.py", line 55, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
  File "/opt/conda/lib/python3.10/site-packages/rpyc/core/stream.py", line 280, in read
    raise EOFError("connection closed by peer")
EOFError: connection closed by peer
```

Thanks for all of your help in advance :)

**Comment by davidsyoung** [comment]
Whilst debugging, I attempted to add --trust-remote-code and build from source without any improvement, in case you think I just needed the latest mixtral fix in commit.

**Comment by davidsyoung** [comment]
Turns out it isn't specifically Mistral/Mixtral, but more so the way the communication happens across GPUs.

**Comment by davidsyoung** [comment]
For anyone that has gone down a rabbit hole with this, what was missing was --ipc=host on docker run. Finally!
