### ISSUE TITLE
[Bug] Can't run Qwen2-57B-A14B-Instruct-GPTQ-Int4

### ISSUE THREAD

**Issue by xcxjack** [sgl-project/sglang#1100]
### Describe the bug

I can't start sglang with model qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4, below is the error ouput.
Does sglang support it now ?

python -m sglang.launch_server --quantization gptq --model-path qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4 --port 8000 --disable-flashinfer-sampling --disable-flashinfer --tp 2 --enable-p2p-check

server_args=ServerArgs(model_path='qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4', tokenizer_path='qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', dtype='auto', trust_remote_code=False, context_length=None, quantization='gptq', served_model_name='qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4', chat_template=None, host='127.0.0.1', port=8000, additional_ports=[8001, 8002, 8003, 8004], mem_fraction_static=0.87, max_running_requests=None, max_num_reqs=None, max_total_tokens=None, chunked_prefill_size=None, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=2, stream_interval=1, random_seed=495990100, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key=None, file_storage_pth='SGLang_storage', dp_size=1, load_balance_method='round_robin', disable_flashinfer=True, disable_flashinfer_sampling=True, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_disk_cache=False, enable_torch_compile=False, enable_p2p_check=True, enable_mla=False, attention_reduce_in_fp32=False, efficient_weight_load=False, nccl_init_addr=None, nnodes=1, node_rank=None)
[gpu=0] Init nccl begin.
[gpu=1] Init nccl begin.
INFO 08-14 20:27:09 custom_all_reduce_utils.py:234] reading GPU P2P access cache from /home/xiao/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
INFO 08-14 20:27:09 custom_all_reduce_utils.py:234] reading GPU P2P access cache from /home/xiao/.cache/vllm/gpu_p2p_access_cache_for_0,1.json
WARNING 08-14 20:27:09 custom_all_reduce.py:127] Custom allreduce is disabled because your platform lacks GPU P2P capability or P2P test failed. To silence this warning, specify disable_custom_all_reduce=True explicitly.
WARNING 08-14 20:27:09 custom_all_reduce.py:127] Custom allreduce is disabled because your platform lacks GPU P2P capability or P2P test failed. To silence this warning, specify disable_custom_all_reduce=True explicitly.
[gpu=0] Load weight begin. avail mem=21.42 GB
[gpu=1] Load weight begin. avail mem=21.42 GB
INFO 08-14 20:27:09 gptq_marlin.py:102] Detected that the model can run with gptq_marlin, however you specified quantization=gptq explicitly, so forcing gptq. Use quantization=gptq_marlin for faster inference
INFO 08-14 20:27:09 gptq_marlin.py:102] Detected that the model can run with gptq_marlin, however you specified quantization=gptq explicitly, so forcing gptq. Use quantization=gptq_marlin for faster inference
Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 787, in run_tp_server
    model_server = ModelTpServer(
                   ^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 100, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 127, in __init__
    self.load_model()
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 180, in load_model
    self.model = get_model(
                 ^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
    return loader.load_model(model_config=model_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 324, in load_model
    model = _initialize_model(model_config, self.load_config,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 154, in _initialize_model
    return model_class(config=model_config.hf_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 364, in __init__
    self.model = Qwen2MoeModel(config, cache_config, quant_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 321, in __init__
    [
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 322, in <listcomp>
    Qwen2MoeDecoderLayer(
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 267, in __init__
    self.mlp = Qwen2MoeSparseMoeBlock(config=config, quant_config=quant_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 104, in __init__
    self.experts = FusedMoE(
                   ^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 186, in __init__
    assert self.quant_method is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Process Process-1:1:
Initialization failed. controller_init_state: Traceback (most recent call last):
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/managers/controller_single.py", line 150, in start_controller_process
    controller = ControllerSingle(
                 ^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/managers/controller_single.py", line 84, in __init__
    self.tp_server = ModelTpServer(
                     ^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 100, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 127, in __init__
    self.load_model()
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 180, in load_model
    self.model = get_model(
                 ^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
    return loader.load_model(model_config=model_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 324, in load_model
    model = _initialize_model(model_config, self.load_config,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 154, in _initialize_model
    return model_class(config=model_config.hf_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 364, in __init__
    self.model = Qwen2MoeModel(config, cache_config, quant_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 321, in __init__
    [
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 322, in <listcomp>
    Qwen2MoeDecoderLayer(
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 267, in __init__
    self.mlp = Qwen2MoeSparseMoeBlock(config=config, quant_config=quant_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 104, in __init__
    self.experts = FusedMoE(
                   ^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 186, in __init__
    assert self.quant_method is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

Initialization failed. detoken_init_state: init ok
Traceback (most recent call last):
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 787, in run_tp_server
    model_server = ModelTpServer(
                   ^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 100, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 127, in __init__
    self.load_model()
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 180, in load_model
    self.model = get_model(
                 ^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/__init__.py", line 21, in get_model
    return loader.load_model(model_config=model_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 324, in load_model
    model = _initialize_model(model_config, self.load_config,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/model_loader/loader.py", line 154, in _initialize_model
    return model_class(config=model_config.hf_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 364, in __init__
    self.model = Qwen2MoeModel(config, cache_config, quant_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 321, in __init__
    [
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 322, in <listcomp>
    Qwen2MoeDecoderLayer(
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 267, in __init__
    self.mlp = Qwen2MoeSparseMoeBlock(config=config, quant_config=quant_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/sglang/srt/models/qwen2_moe.py", line 104, in __init__
    self.experts = FusedMoE(
                   ^^^^^^^^^
  File "/home/xiao/miniconda3/envs/sglang/lib/python3.11/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 186, in __init__
    assert self.quant_method is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

### Reproduction

python -m sglang.launch_server --quantization gptq --model-path qwen/Qwen2-57B-A14B-Instruct-GPTQ-Int4 --port 8000 --disable-flashinfer-sampling --disable-flashinfer --tp 2 --enable-p2p-check

### Environment

Python: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 2080 Ti
GPU 0,1 Compute Capability: 7.5
CUDA_HOME: /usr/local/cuda-12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.66
CUDA Driver Version: 535.183.01
PyTorch: 2.4.0+cu121
sglang: 0.2.12
flashinfer: 0.1.4+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.3
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 26.1.0
vllm: 0.5.4
multipart: 0.0.9
openai: 1.40.6
anthropic: 0.33.1
NVIDIA Topology:
	GPU0	GPU1	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	PHB	0-15	0		N/A
GPU1	PHB	 X 	0-15	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024

**Comment by zhyncs** [comment]
Currently does not support sm75

**Comment by jeejeelee** [comment]
GPTQ is not yet supported for this MOE Model. There is a PR in vLLM attempting to address this issue, see:  https://github.com/vllm-project/vllm/pull/6502

**Comment by chuangzhidan** [comment]
How to use two graphics cards to deploy services? I only see that the memory usage of one graphics card is increasing.

**Comment by merrymercy** [comment]
closed this for now as the pr is in https://github.com/vllm-project/vllm/pull/6502.
@chuangzhidan use `--tp 2`
