### ISSUE TITLE
[Bug] enable-torch-compile error

### ISSUE THREAD

**Issue by siddhatiwari** [sgl-project/sglang#1196]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

Starting the server with  `--enable-torch-compile` flag fails with this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 781, in run_tp_server
    model_server = ModelTpServer(
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 99, in __init__
    self.model_runner = ModelRunner(
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 140, in __init__
    self.init_cuda_graphs()
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 373, in init_cuda_graphs
    raise Exception(
Exception: Capture cuda graph failed: backend='inductor' raised:
RuntimeError: "_local_scalar_dense_cuda" not implemented for 'Float8_e4m3fn'

While executing %empty : [num_users=1] = call_function[target=torch.ops.aten.empty.memory_format](args = ([1, 8192],), kwargs = {dtype: torch.float8_e4m3fn, device: cuda:1, pin_memory: False})
Original traceback:
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 165, in forward
    qkv, _ = self.qkv_proj(hidden_states)
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 334, in forward
    output_parallel = self.quant_method.apply(self, input_, bias)
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/fp8.py", line 231, in apply
    return apply_fp8_linear(
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/vllm/model_executor/layers/quantization/utils/w8a8_utils.py", line 119, in apply_fp8_linear
    qinput, x_scale = ops.scaled_fp8_quant(
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/vllm/_custom_ops.py", line 32, in wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/testfs/sglang-venv/lib/python3.10/site-packages/vllm/_custom_ops.py", line 348, in scaled_fp8_quant
    output = torch.empty(shape, device=input.device, dtype=torch.float8_e4m3fn)
```

### Reproduction

```CUDA_VISIBLE_DEVICES=2,3 python -m sglang.launch_server --model-path NousResearch/Meta-Llama-3.1-70B-Instruct --port 30003 --tp 2 --mem-fraction-static 0.93 --quantization fp8  --host 0.0.0.0 --context-length 2560  --max-num-reqs 15 --chunked-prefill-size 8192 --enable-torch-compile```

### Environment

```
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 12.2, V12.2.140
CUDA Driver Version: 535.129.03
PyTorch: 2.4.0+cu121
sglang: 0.2.13
flashinfer: 0.1.5+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.5
fastapi: 0.112.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.6
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.2.0
vllm: 0.5.4
multipart: 0.0.9
openai: 1.42.0
anthropic: 0.34.1
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     104-207 1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     104-207 1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     104-207 1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     104-207 1               N/A
NIC0    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0


ulimit soft: 4096
```

**Comment by zhaochenyang20** [comment]
@siddhatiwari Hey. Thanks for pointing this out. We've noticed this issue and will fix ASAP.

But I want to point out that torch compile right now only works for small models that can be served on only on GPU, like llama3.1-8b. For llama3.1 70b, even if you can compile it, the model would be slightly slower. (For 8b model it will be quicker of cause).

So please turn down compile for you 70b model. And we  will try to fix this bug.

**Comment by merrymercy** [comment]
torch.compile now only works for fp16, so your fp8 command will fail

**Comment by HaiShaw** [comment]
@merrymercy I think torch.compile works with fp8 now on torch 2.5.
