### ISSUE TITLE
No such file or directory: '/sbin/ldconfig'

### ISSUE THREAD

**Issue by zwc163** [sgl-project/sglang#1226]
Traceback (most recent call last):
  File "/root/python/sglang/srt/managers/tp_worker.py", line 865, in run_tp_server
    model_server = ModelTpServer(
  File "/root/python/sglang/srt/managers/tp_worker.py", line 100, in __init__
    self.model_runner = ModelRunner(
  File "/root/python/sglang/srt/model_executor/model_runner.py", line 140, in __init__
    self.init_cuda_graphs()
  File "/root/python/sglang/srt/model_executor/model_runner.py", line 371, in init_cuda_graphs
    self.cuda_graph_runner.capture(batch_size_list)
  File "/root/python/sglang/srt/model_executor/cuda_graph_runner.py", line 162, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/root/python/sglang/srt/model_executor/cuda_graph_runner.py", line 242, in capture_one_batch_size
    run_once()
  File "/root/python/sglang/srt/model_executor/cuda_graph_runner.py", line 239, in run_once
    return forward(input_ids, input_metadata.positions, input_metadata)
  File "/root/python/sglang/srt/models/mixtral.py", line 310, in forward
    hidden_states = self.model(input_ids, positions, input_metadata, input_embeds)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/python/sglang/srt/models/mixtral.py", line 281, in forward
    hidden_states, residual = layer(
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/python/sglang/srt/models/mixtral.py", line 238, in forward
    hidden_states = self.block_sparse_moe(hidden_states)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/python/sglang/srt/models/mixtral.py", line 99, in forward
    final_hidden_states = self.experts(hidden_states, router_logits)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
Process Process-1:1:
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/layer.py", line 250, in forward
    final_hidden_states = self.quant_method.apply(
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/layer.py", line 75, in apply
    return self.forward(x, layer.w13_weight, layer.w2_weight,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/custom_op.py", line 13, in forward
    return self._forward_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/layer.py", line 92, in forward_cuda
    return fused_moe(x,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 613, in fused_moe
    return fused_experts(hidden_states,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 513, in fused_experts
    invoke_fused_moe_kernel(curr_hidden_states,
  File "/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/fused_moe/fused_moe.py", line 246, in invoke_fused_moe_kernel
    fused_moe_kernel[grid](
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 345, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/jit.py", line 607, in run
    device = driver.active.get_current_device()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 23, in __getattr__
    self._initialize_obj()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 20, in _initialize_obj
    self._obj = self._init_fn()
  File "/usr/local/lib/python3.10/dist-packages/triton/runtime/driver.py", line 9, in _create_driver
    return actives[0]()
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/driver.py", line 371, in __init__
    self.utils = CudaUtils()  # TODO: make static
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/driver.py", line 80, in __init__
    mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/driver.py", line 57, in compile_module_from_src
    so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/driver.py", line 45, in library_dirs
    return [libdevice_dir, *libcuda_dirs()]
  File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/driver.py", line 24, in libcuda_dirs
    libs = subprocess.check_output(["/sbin/ldconfig", "-p"]).decode()
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/sbin/ldconfig'

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by zwc163** [comment]
thanks
