### ISSUE TITLE
[Bug] 0.2.14 version. ValueError: malformed node or string: None

### ISSUE THREAD

**Issue by lss15151161** [sgl-project/sglang#1245]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

[17:30:41 TP0] Exception in ModelTpServer:
Traceback (most recent call last):
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/site-packages/sglang/srt/managers/tp_worker.py", line 222, in exposed_step
    self.handle_generate_request(recv_req)
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/site-packages/sglang/srt/managers/tp_worker.py", line 341, in handle_generate_request
    ) = self.model_runner.model.pad_input_ids(
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/site-packages/sglang/srt/models/llava.py", line 85, in pad_input_ids
    num_patch_width, num_patch_height = get_anyres_image_grid_shape(
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/site-packages/sglang/srt/mm_utils.py", line 173, in get_anyres_image_grid_shape
    possible_resolutions = ast.literal_eval(grid_pinpoints)
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/ast.py", line 105, in literal_eval
    return _convert(node_or_string)
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/ast.py", line 104, in _convert
    return _convert_signed_num(node)
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/ast.py", line 78, in _convert_signed_num
    return _convert_num(node)
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/ast.py", line 69, in _convert_num
    _raise_malformed_node(node)
  File "/root/miniconda3/envs/sglang_0.2/lib/python3.9/ast.py", line 66, in _raise_malformed_node
    raise ValueError(f'malformed node or string: {node!r}')
ValueError: malformed node or string: None

### Reproduction

pip install sglang[all]
pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/

cd sglang/examples/frontend_language/quick_start
python local_example_llava_next.py

### Environment

python 3.9
cuda 12.1

**Comment by lukashelff** [comment]
How did you solve this issue? I still receive this error on the on sglang 0.3.2

**Comment by xin-ran-w** [comment]
I meet this issue too, did you solve it?
