### ISSUE TITLE
llava-v1.6-vicuna-7b NoneType Object Error when handle_generate_request, maybe misspelled

### ISSUE THREAD

**Issue by luixiao0** [sgl-project/sglang#131]
sglang version: `sglang==0.1.10`
torch version: `2.1.0+cu118`

When running the server via: 

`python3 -m sglang.launch_server --model-path ./llava-v1.6-vicuna-7b --tokenizer-path SurfaceData/llava-v1.6-vicuna-7b-processor --chat-template vicuna_v1.1 --port 30000`

Running the following test script :

```
@sgl.function
def pipeline(s, prompt, max_tokens):
    for p in prompt:
        if type(p) is str:
            s += p
        else:
            s += sgl.image(p) # p would be PIL.Image
    s += sgl.gen("response", max_tokens=max_tokens)

backend = RuntimeEndpoint(sgl_endpoint)
sgl.set_default_backend(backend)
pipeline.run(prompt, max_new_tokens, temperature=temperature, top_p=top_p, top_k=top_k, stream=True)
```

the request triggered `handle_generate_request` in `srt.managers.router.model_rpc` and assert
```
Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 159, in exposed_step
    self.handle_generate_request(recv_req)
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 240, in handle_generate_request
    req.input_ids, req.image_offset = self.model_runner.model.pad_input_ids(
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/models/llava.py", line 49, in pad_input_ids
    num_patch_width, num_patch_height = get_anyres_image_grid_shape(
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/mm_utils.py", line 121, in get_anyres_image_grid_shape
    width, height = select_best_resolution(image_size, possible_resolutions)
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/mm_utils.py", line 22, in select_best_resolution
    original_width, original_height = original_size
TypeError: cannot unpack non-iterable NoneType object
```
but the recv_req from the debugger shows pxel_values and image_size correctly

i went through the sglang lib and i found line 242 of model_rpc.py is suspicious

the following is a snippet from `model_rpc.py`

```
    def handle_generate_request(
        self,
        recv_req: TokenizedGenerateReqInput,
    ):
        req = Req(recv_req.rid, recv_req.input_text, recv_req.input_ids)
        req.pixel_values = recv_req.pixel_values
        if req.pixel_values is not None:
            print('pixel value is not none')
            pad_value = [
                (recv_req.image_hash) % self.model_config.vocab_size,
                (recv_req.image_hash >> 16) % self.model_config.vocab_size,
                (recv_req.image_hash >> 32) % self.model_config.vocab_size,
                (recv_req.image_hash >> 64) % self.model_config.vocab_size,
            ]
            req.input_ids, req.image_offset = self.model_runner.model.pad_input_ids(
                req.input_ids, pad_value, req.pixel_values.shape, req.image_size
            )
            req.image_size = recv_req.image_size
        req.sampling_params = recv_req.sampling_params
        req.return_logprob = recv_req.return_logprob
        req.logprob_start_len = recv_req.logprob_start_len
        req.stream = recv_req.stream
        req.tokenizer = self.tokenizer
```
req.image_size is None when self.model_runner.model.pad_input_ids is called， maybe it should be recv_req.image_size?

**Comment by luixiao0** [comment]
the following is the recv_req i got

```
TokenizedGenerateReqInput(rid='5e89021657f84c36ade6288f3a50ca78',
input_text='sys prompts USER: userquestion.\n <image>\n ASSISTANT:',
input_ids=[a list of input ID],
pixel_values=array([[[A BIG ARRAY]]], dtype=float16),
image_hash=5408669136032689008,
image_size=(468, 336),
sampling_params=<sglang.srt.sampling_params.SamplingParams object at 0x7f1e00529e70>,
return_logprob=False, logprob_start_len=0, stream=True)
```

**Comment by luixiao0** [comment]
when i change from `req.image_size` to `recv_req.image_size` it kinda works, am i doing right?

**Comment by merrymercy** [comment]
Yes. It is bug that has been fixed in the main branch

https://github.com/sgl-project/sglang/commit/c7af9f73938a79b84dab6b6b4b9aa339118b593b
