### ISSUE TITLE
[Bug] ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by oliver-li** [sgl-project/sglang#1333]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

I'm using the run_batch method for batch inference on multiple cards and I'm encountering a ConnectionResetError. Does this mean the sglang service has crashed? Should I implement a mechanism to restart the service on my own?
```
/usr/local/conda/lib/python3.9/site-packages/sglang/lang/interpreter.py:330: UserWarning: Error in stream_executor: Traceback (most recent call last):
  File "/usr/local/conda/lib/python3.9/site-packages/sglang/lang/interpreter.py", line 328, in _thread_worker_func
    self._execute(expr)
  File "/usr/local/conda/lib/python3.9/site-packages/sglang/lang/interpreter.py", line 371, in _execute
    self._execute(x)
  File "/usr/local/conda/lib/python3.9/site-packages/sglang/lang/interpreter.py", line 366, in _execute
    self._execute_gen(other)
  File "/usr/local/conda/lib/python3.9/site-packages/sglang/lang/interpreter.py", line 496, in _execute_gen
    comp, meta_info = self.backend.generate(
  File "/usr/local/conda/lib/python3.9/site-packages/sglang/lang/backend/runtime_endpoint.py", line 159, in generate
    res = http_request(
  File "/usr/local/conda/lib/python3.9/site-packages/sglang/utils.py", line 96, in http_request
    resp = urllib.request.urlopen(req, data=data, cafile=verify)
  File "/usr/local/conda/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/conda/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/conda/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/conda/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/conda/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/conda/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/usr/local/conda/lib/python3.9/http/client.py", line 1377, in getresponse
    response.begin()
  File "/usr/local/conda/lib/python3.9/http/client.py", line 320, in begin
    version, status, reason = self._read_status()
  File "/usr/local/conda/lib/python3.9/http/client.py", line 281, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/conda/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

  warnings.warn(f"Error in stream_executor: {get_exception_traceback()}")
```

### Reproduction

sglang==0.3.0
python3 -m sglang.launch_server --model-path xxxx --port 30000 -tp 4

### Environment

| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 12.2     
4* A100

**Comment by m0g1cian** [comment]
I've also seen this when I was testing a very large batch size after upgrade to 0.3.0. Reduce batch size solves the issue but I don't know if this issue is really memory correlated or not?

**Comment by merrymercy** [comment]
It typically means the server crashed. Can you try to restart and print the error log form the server?

**Comment by fanganpai** [comment]
Similar issue was encountered. In my case it happened when request load was so high.
May lowering the batch size changes the throughput of your service and avoids this?

**Comment by fanganpai** [comment]
I checked the server logs and everything is fine there, only the successful requests are logged. Those failed requests dont put anything in logs at all.
