### ISSUE TITLE
[Bug] it didn't work when using tp on RTX 3090

### ISSUE THREAD

**Issue by milktea888** [sgl-project/sglang#1343]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [x] 5. Please use English, otherwise it will be closed.

### Describe the bug

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/dfs/data/github/sglang/python/sglang/launch_server.py", line 19, in <module>
    raise e
  File "/dfs/data/github/sglang/python/sglang/launch_server.py", line 17, in <module>
    launch_server(server_args)
  File "/dfs/data/github/sglang/python/sglang/srt/server.py", line 365, in launch_server
    raise RuntimeError(
RuntimeError: Initialization failed. controller_init_state: Traceback (most recent call last):
  File "/dfs/data/github/sglang/python/sglang/srt/managers/controller_single.py", line 149, in start_controller_process
    controller = ControllerSingle(
  File "/dfs/data/github/sglang/python/sglang/srt/managers/controller_single.py", line 83, in __init__
    self.tp_server = ModelTpServer(
  File "/dfs/data/github/sglang/python/sglang/srt/managers/tp_worker.py", line 99, in __init__
    self.model_runner = ModelRunner(
  File "/dfs/data/github/sglang/python/sglang/srt/model_executor/model_runner.py", line 109, in __init__
    min_per_gpu_memory = self.init_torch_distributed()
  File "/dfs/data/github/sglang/python/sglang/srt/model_executor/model_runner.py", line 140, in init_torch_distributed
    initialize_model_parallel(tensor_model_parallel_size=self.tp_size)
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 931, in initialize_model_parallel
    _TP = init_model_parallel_group(group_ranks,
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 773, in init_model_parallel_group
    return GroupCoordinator(
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 164, in __init__
    self.ca_comm = CustomAllreduce(
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 130, in __init__
    if not _can_p2p(rank, world_size):
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 31, in _can_p2p
    if not gpu_p2p_access_check(rank, i):
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/custom_all_reduce_utils.py", line 227, in gpu_p2p_access_check
    result = pickle.loads(returned.stdout)
_pickle.UnpicklingError: invalid load key, 'W'.
, detoken_init_state: init ok

### Reproduction

python3 -m sglang.launch_server --model-path ../llama3/safesensor_models/ --port 30000 --trust-remote-code --disable-radix-cache --tp 2 --enable-p2p-check

### Environment

WARNING 09-06 09:46:19 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead. See https://pypi.org/project/pynvml for more information.
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
GPU 0,1: NVIDIA GeForce RTX 3090
GPU 0,1 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.3, V12.3.107
CUDA Driver Version: 525.116.04
PyTorch: 2.4.0+cu121
sglang: 0.3.0
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.24.4
aiohttp: 3.9.1
fastapi: 0.112.3
hf_transfer: 0.1.8
huggingface_hub: 0.24.6
interegular: 0.3.3
packaging: 23.2
PIL: 10.2.0
psutil: 5.9.4
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 25.1.2
vllm: 0.5.5
multipart: 0.0.9
openai: 1.43.0
anthropic: 0.34.2
NVIDIA Topology: 
        GPU0    GPU1    NIC0    CPU Affinity    NUMA Affinity
GPU0     X      SYS     SYS     6-11,54-59      1
GPU1    SYS      X      SYS     36-41,84-89     6
NIC0    SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0

ulimit soft: 1048576

**Comment by PenglongHuang** [comment]
The sglang document indicates using -- tp to represent tensor parallelism, but in reality, the parameter in the source code is -- tp-size, and -- tp cannot be found

**Comment by milktea888** [comment]
ok, thank you. I'll try --tp-size

**Comment by hysyyds** [comment]
> The sglang document indicates using -- tp to represent tensor parallelism, but in reality, the parameter in the source code is -- tp-size, and -- tp cannot be found

work for me.

**Comment by merrymercy** [comment]
try `--disable-custom-all-reduce`
