### ISSUE TITLE
deepseek-v2 torch.compile error

### ISSUE THREAD

**Issue by cdj0311** [sgl-project/sglang#1372]
hi,
Deepseek-coder-v2-lite-base running with --enable-torch-compile get and error,  I don't know what's the means, could you help me?

Running command:
````
python -m sglang.launch_server --model-path Deepseek-coder-v2-lite-base --port 30000 --trust-remote-code --tp-size 2 --enable-torch-compile
````
Get an Error:
````
[17:23:54] server_args=ServerArgs(model_path='/home/deepseek-coder-v2-lite-base', tokenizer_path='/home/deepseek-coder-v2-lite-base', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', dtype='auto', kv_cache_dtype='auto', trust_remote_code=True, context_length=None, quantization=None, served_model_name='/home/deepseek-coder-v2-lite-base', chat_template=None, is_embedding=False, host='127.0.0.1', port=30000, additional_ports=[30001, 30002, 30003, 30004], mem_fraction_static=0.87, max_running_requests=None, max_num_reqs=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=2, stream_interval=1, random_seed=756038125, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key=None, file_storage_pth='SGLang_storage', dp_size=1, load_balance_method='round_robin', nccl_init_addr=None, nnodes=1, node_rank=None, json_model_override_args='{}', disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_disk_cache=False, disable_custom_all_reduce=False, enable_mixed_chunk=False, enable_torch_compile=True, torchao_config='', enable_p2p_check=False, enable_mla=False, triton_attention_reduce_in_fp32=False)
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[17:23:54 TP0] Init nccl begin.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[17:23:54 TP1] Init nccl begin.
[17:23:54 TP0] Load weight begin. avail mem=44.00 GB
[17:23:54 TP1] Load weight begin. avail mem=44.00 GB
/root/miniconda3/lib/python3.10/site-packages/torchao/ops.py:12: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  return torch.library.impl_abstract(f"{name}")(func)
/root/miniconda3/lib/python3.10/site-packages/torchao/ops.py:12: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  return torch.library.impl_abstract(f"{name}")(func)
[17:23:56 TP0] lm_eval is not installed, GPTQ may not be usable
[17:23:56 TP1] lm_eval is not installed, GPTQ may not be usable
Cache shape torch.Size([163840, 64])
Cache shape torch.Size([163840, 64])
Loading safetensors checkpoint shards:   0% Completed | 0/16 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   6% Completed | 1/16 [00:00<00:03,  4.68it/s]
Loading safetensors checkpoint shards:  12% Completed | 2/16 [00:00<00:03,  4.33it/s]
Loading safetensors checkpoint shards:  19% Completed | 3/16 [00:00<00:03,  4.30it/s]
Loading safetensors checkpoint shards:  25% Completed | 4/16 [00:00<00:02,  4.31it/s]
Loading safetensors checkpoint shards:  31% Completed | 5/16 [00:01<00:02,  4.33it/s]
Loading safetensors checkpoint shards:  38% Completed | 6/16 [00:01<00:02,  4.58it/s]
Loading safetensors checkpoint shards:  44% Completed | 7/16 [00:01<00:01,  4.74it/s]
Loading safetensors checkpoint shards:  50% Completed | 8/16 [00:01<00:01,  4.79it/s]
Loading safetensors checkpoint shards:  56% Completed | 9/16 [00:01<00:01,  4.86it/s]
Loading safetensors checkpoint shards:  62% Completed | 10/16 [00:02<00:01,  4.97it/s]
Loading safetensors checkpoint shards:  69% Completed | 11/16 [00:02<00:00,  5.02it/s]
Loading safetensors checkpoint shards:  75% Completed | 12/16 [00:02<00:00,  5.09it/s]
Loading safetensors checkpoint shards:  81% Completed | 13/16 [00:02<00:00,  5.12it/s]
Loading safetensors checkpoint shards:  88% Completed | 14/16 [00:02<00:00,  5.14it/s]
[17:23:59 TP1] Load weight end. type=DeepseekV2ForCausalLM, dtype=torch.float16, avail mem=29.29 GB
Loading safetensors checkpoint shards:  94% Completed | 15/16 [00:03<00:00,  5.18it/s]
Loading safetensors checkpoint shards: 100% Completed | 16/16 [00:03<00:00,  5.84it/s]
Loading safetensors checkpoint shards: 100% Completed | 16/16 [00:03<00:00,  4.98it/s]

[17:23:59 TP0] Load weight end. type=DeepseekV2ForCausalLM, dtype=torch.float16, avail mem=29.29 GB
[17:23:59 TP0] Memory pool end. avail mem=4.41 GB
[17:23:59 TP1] Memory pool end. avail mem=4.41 GB
[17:23:59 TP1] Capture cuda graph begin. This can take up to several minutes.
[17:23:59 TP0] Capture cuda graph begin. This can take up to several minutes.
INFO 09-10 17:24:14 custom_all_reduce.py:223] Registering 0 cuda graph addresses
INFO 09-10 17:24:14 custom_all_reduce.py:223] Registering 0 cuda graph addresses
[17:24:14 TP1] Exception in run_tp_server:
Traceback (most recent call last):
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 513, in init_cuda_graphs
    self.cuda_graph_runner.capture(batch_size_list)
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 181, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 265, in capture_one_batch_size
    run_once()
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 259, in run_once
    return forward(input_ids, input_metadata.positions, input_metadata)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 660, in forward
    hidden_states = self.model(input_ids, positions, input_metadata)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 625, in forward
    hidden_states = self.embed_tokens(input_ids)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 629, in torch_dynamo_resume_in_forward_at_625
    hidden_states, residual = layer(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 576, in forward
    hidden_states = self.self_attn(
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 584, in torch_dynamo_resume_in_forward_at_576
    hidden_states = self.mlp(hidden_states)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 146, in forward
    self.experts(hidden_states=hidden_states, router_logits=router_logits)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 287, in forward
    final_hidden_states = self.quant_method.apply(
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 68, in apply
    return self.forward(x=x,
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 14, in forward
    return self._forward_method(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 23, in forward_native
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sglang/python/sglang/srt/managers/tp_worker.py", line 901, in run_tp_server
    model_server = ModelTpServer(
  File "/home/sglang/python/sglang/srt/managers/tp_worker.py", line 98, in __init__
    self.model_runner = ModelRunner(
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 120, in __init__
    self.init_cuda_graphs()
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 515, in init_cuda_graphs
    raise Exception(
Exception: Capture cuda graph failed: 
Possible solutions:
1. disable cuda graph by --disable-cuda-graph
2. set --mem-fraction-static to a smaller value
3. disable torch compile by not using --enable-torch-compile
Open an issue on GitHub https://github.com/sgl-project/sglang/issues/new/choose 


Process Process-1:1:
Traceback (most recent call last):
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 513, in init_cuda_graphs
    self.cuda_graph_runner.capture(batch_size_list)
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 181, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 265, in capture_one_batch_size
    run_once()
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 259, in run_once
    return forward(input_ids, input_metadata.positions, input_metadata)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 660, in forward
    hidden_states = self.model(input_ids, positions, input_metadata)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 625, in forward
    hidden_states = self.embed_tokens(input_ids)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 629, in torch_dynamo_resume_in_forward_at_625
    hidden_states, residual = layer(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 576, in forward
    hidden_states = self.self_attn(
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 584, in torch_dynamo_resume_in_forward_at_576
    hidden_states = self.mlp(hidden_states)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 146, in forward
    self.experts(hidden_states=hidden_states, router_logits=router_logits)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 287, in forward
    final_hidden_states = self.quant_method.apply(
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 68, in apply
    return self.forward(x=x,
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 14, in forward
    return self._forward_method(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 23, in forward_native
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/root/miniconda3/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sglang/python/sglang/srt/managers/tp_worker.py", line 901, in run_tp_server
    model_server = ModelTpServer(
  File "/home/sglang/python/sglang/srt/managers/tp_worker.py", line 98, in __init__
    self.model_runner = ModelRunner(
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 120, in __init__
    self.init_cuda_graphs()
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 515, in init_cuda_graphs
    raise Exception(
Exception: Capture cuda graph failed: 
Possible solutions:
1. disable cuda graph by --disable-cuda-graph
2. set --mem-fraction-static to a smaller value
3. disable torch compile by not using --enable-torch-compile
Open an issue on GitHub https://github.com/sgl-project/sglang/issues/new/choose 

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/sglang/python/sglang/launch_server.py", line 16, in <module>
    raise e
  File "/home/sglang/python/sglang/launch_server.py", line 14, in <module>
    launch_server(server_args)
  File "/home/sglang/python/sglang/srt/server.py", line 363, in launch_server
    raise RuntimeError(
RuntimeError: Initialization failed. controller_init_state: Traceback (most recent call last):
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 513, in init_cuda_graphs
    self.cuda_graph_runner.capture(batch_size_list)
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 181, in capture
    ) = self.capture_one_batch_size(bs, forward)
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 265, in capture_one_batch_size
    run_once()
  File "/home/sglang/python/sglang/srt/model_executor/cuda_graph_runner.py", line 259, in run_once
    return forward(input_ids, input_metadata.positions, input_metadata)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 660, in forward
    hidden_states = self.model(input_ids, positions, input_metadata)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 625, in forward
    hidden_states = self.embed_tokens(input_ids)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 629, in torch_dynamo_resume_in_forward_at_625
    hidden_states, residual = layer(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 576, in forward
    hidden_states = self.self_attn(
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 584, in torch_dynamo_resume_in_forward_at_576
    hidden_states = self.mlp(hidden_states)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sglang/python/sglang/srt/models/deepseek_v2.py", line 146, in forward
    self.experts(hidden_states=hidden_states, router_logits=router_logits)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 287, in forward
    final_hidden_states = self.quant_method.apply(
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/layers/fused_moe/layer.py", line 68, in apply
    return self.forward(x=x,
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 14, in forward
    return self._forward_method(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/vllm/model_executor/custom_op.py", line 23, in forward_native
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sglang/python/sglang/srt/managers/controller_single.py", line 145, in start_controller_process
    controller = ControllerSingle(
  File "/home/sglang/python/sglang/srt/managers/controller_single.py", line 81, in __init__
    self.tp_server = ModelTpServer(
  File "/home/sglang/python/sglang/srt/managers/tp_worker.py", line 98, in __init__
    self.model_runner = ModelRunner(
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 120, in __init__
    self.init_cuda_graphs()
  File "/home/sglang/python/sglang/srt/model_executor/model_runner.py", line 515, in init_cuda_graphs
    raise Exception(
Exception: Capture cuda graph failed: 
Possible solutions:
1. disable cuda graph by --disable-cuda-graph
2. set --mem-fraction-static to a smaller value
3. disable torch compile by not using --enable-torch-compile
Open an issue on GitHub https://github.com/sgl-project/sglang/issues/new/choose 

, detoken_init_state: init ok
(base) 
````

**Comment by zhyncs** [comment]
enable-torch-compile requires CUDA Graph support. This requires support for CUDA Graph before it can be achieved.

**Comment by zhyncs** [comment]
cc @merrymercy @ispobock
