### ISSUE TITLE
Error on json decoding with llava

### ISSUE THREAD

**Issue by isaac-vidas** [sgl-project/sglang#138]
Encountered the following error when using the `regex` in call to `gen` method. Server doesn't work afterwards:

```console
~$ python3 -m sglang.launch_server --model-path liuhaotian/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --port 30000
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Rank 0: load weight begin.
/opt/conda/envs/llava_test/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
INFO 02-03 23:02:55 weight_utils.py:164] Using model weights format ['*.bin']
INFO 02-03 23:03:01 weight_utils.py:164] Using model weights format ['*.bin']
Rank 0: load weight end.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Rank 0: max_total_num_token=44713, max_prefill_num_token=7452, context_len=4096, model_mode=[]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO:     Started server process [66164]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
INFO:     127.0.0.1:51098 - "GET /get_model_info HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 0. #new_token: 646. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 0.00%.
#running-req: 1, #token: 646, token usage: 0.01, #queue-req: 0
INFO:     127.0.0.1:58036 - "POST /generate HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 645. #new_token: 1. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 49.92%.
new fill batch. #seq: 1. #cached_token: 35. #new_token: 39. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 49.78%.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [0,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [1,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [2,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [3,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [4,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [5,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [6,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [7,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [8,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [9,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [10,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [11,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [12,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [13,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [14,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [15,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [16,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [17,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [18,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [19,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [0,0,0], thread: [20,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

...

../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [29,0,0], thread: [27,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [29,0,0], thread: [28,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [29,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [29,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1292: indexSelectLargeIndex: block: [29,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 168, in exposed_step
    self.forward_step()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 183, in forward_step
    self.forward_fill_batch(new_batch)
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 391, in forward_fill_batch
    logits, (logprobs, normalized_logprobs) = self.model_runner.forward(
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 460, in forward
    return self.forward_extend_multi_modal(**kwargs)
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 437, in forward_extend_multi_modal
    return self.model.forward(
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/models/llava.py", line 107, in forward
    .cpu()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 168, in exposed_step
    self.forward_step()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 179, in forward_step
    new_batch = self.get_new_fill_batch()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 293, in get_new_fill_batch
    self.token_to_kv_pool.available_size() + self.tree_cache.evictable_size()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/memory_pool.py", line 92, in available_size
    return torch.sum(self.mem_state == 0).item()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 168, in exposed_step
    self.forward_step()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 179, in forward_step
    new_batch = self.get_new_fill_batch()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 293, in get_new_fill_batch
    self.token_to_kv_pool.available_size() + self.tree_cache.evictable_size()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/memory_pool.py", line 92, in available_size
    return torch.sum(self.mem_state == 0).item()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 168, in exposed_step
    self.forward_step()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 179, in forward_step
    new_batch = self.get_new_fill_batch()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 293, in get_new_fill_batch
    self.token_to_kv_pool.available_size() + self.tree_cache.evictable_size()
  File "/opt/conda/envs/llava_test/lib/python3.10/site-packages/sglang/srt/memory_pool.py", line 92, in available_size
    return torch.sum(self.mem_state == 0).item()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

...
```

## How to reproduce the error

* Run the server with `python3 -m sglang.launch_server --model-path liuhaotian/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --port 30000`
* Run the following code:
```python
import sglang as sgl
from enum import Enum
from pydantic import BaseModel
from sglang.srt.constrained.json_schema import build_regex_from_object
from sglang import function, system, user, assistant, gen, set_default_backend, RuntimeEndpoint
set_default_backend(RuntimeEndpoint("http://localhost:30000"))

@sgl.function
def image_qa(s, image_path, question, regex=None):
    s += sgl.user(sgl.image(image_path) + question)
    s += sgl.assistant(sgl.gen("answer", regex=regex))

class Color(str, Enum):
    black = "Black"
    orange = "Orange"
    white = "White"

class Attributes(BaseModel):
    color: Color

state = image_qa.run(
    image_path="cat.jpg",
    question="What color is the cat? respond only in JSON format. The key should be color and the only values allowed are Black, Orange, White",
    regex=build_regex_from_object(Attributes),
    max_new_tokens=200,
    temperature=0
)
print(state['answer'])
```

## Additional notes:
* Tested on A100 40GB
* sglang 0.1.11
* torch 2.1.2
* CUDA:
  ```console
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2023 NVIDIA Corporation
  Built on Mon_Apr__3_17:16:06_PDT_2023
  Cuda compilation tools, release 12.1, V12.1.105
  Build cuda_12.1.r12.1/compiler.32688072_0
  ```
* If I remove the `regex` parameter, the output is what I expect it to be (e.g. `' {\n"color": "Orange",\n}'`)
* `json_decode.py` file with llama2 (`python -m sglang.launch_server --model-path meta-llama/Llama-2-7b-chat-hf --port 30000`)  ran successfully so it might be a multimodal issue. As far as I know [Outlines](https://github.com/outlines-dev/outlines) doesn't support multimodals yet.
  ```console
  ~$ python json_decode.py
  Hermione Granger is a character in Harry Potter. Please fill in the following information about this character.
  {
      "name": "Hermione Granger",
      "house": "Gryffindor",
      "blood status": "Pure-blood",
      "occupation": "student",
      "wand": {
          "wood": "cherry",
          "core": "hornbeam",
          "length": 16.75
      },
      "alive": "Alive",
      "patronus": "toad",
      "bogart": "Owl"
  }
  ```

**Comment by merrymercy** [comment]
The bug has been fixed by this commit: https://github.com/sgl-project/sglang/commit/bb3a3b6675b1844a13ebe368ad693f3dc75b315b

Could you try the latest main branch?

We will publish a new version to pypi soon.

**Comment by isaac-vidas** [comment]
Thanks @merrymercy, it's working perfectly! 🎉 

<img width="1079" alt="image" src="https://github.com/sgl-project/sglang/assets/80056737/bff4c697-3bb0-4a8d-8a9f-04663bebf671">

I should have checked with the latest changes :)
Thanks for this amazing framework!
