### ISSUE TITLE
[Bug] requests.exceptions.JSONDecodeError: 

### ISSUE THREAD

**Issue by eyuansu62** [sgl-project/sglang#1386]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [x] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

After installing the newest version, it encouters a bug: when I launch a sglang run, it raises two exceptions in a few seconds.
```
(vllm) user@node14:~$  python -m sglang.launch_server --model-path models/Qwen2-72B-Instruct --port 30000 --tp 8
[14:39:01] server_args=ServerArgs(model_path='models/Qwen2-72B-Instruct', tokenizer_path='models/Qwen2-72B-Instruct', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', dtype='auto', kv_cache_dtype='auto', trust_remote_code=False, context_length=None, quantization=None, served_model_name='models/Qwen2-72B-Instruct', chat_template=None, is_embedding=False, host='127.0.0.1', port=30000, additional_ports=[30001, 30002, 30003, 30004], mem_fraction_static=0.83, max_running_requests=None, max_num_reqs=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=8, stream_interval=1, random_seed=420923413, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key=None, file_storage_pth='SGLang_storage', dp_size=1, load_balance_method='round_robin', disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_disk_cache=False, disable_custom_all_reduce=False, enable_mixed_chunk=False, enable_torch_compile=False, enable_p2p_check=False, enable_mla=False, triton_attention_reduce_in_fp32=False, nccl_init_addr=None, nnodes=1, node_rank=None)
[14:39:07 TP3] Init nccl begin.
[14:39:07 TP0] Init nccl begin.
[14:39:07 TP5] Init nccl begin.
[14:39:07 TP7] Init nccl begin.
[14:39:07 TP6] Init nccl begin.
[14:39:07 TP2] Init nccl begin.
[14:39:07 TP4] Init nccl begin.
[14:39:07 TP1] Init nccl begin.
[14:39:21 TP2] Load weight begin. avail mem=76.63 GB
[14:39:21 TP6] Load weight begin. avail mem=76.63 GB
[14:39:21 TP4] Load weight begin. avail mem=76.63 GB
[14:39:21 TP5] Load weight begin. avail mem=76.63 GB
[14:39:21 TP0] Load weight begin. avail mem=76.73 GB
[14:39:21 TP3] Load weight begin. avail mem=76.63 GB
[14:39:21 TP1] Load weight begin. avail mem=76.63 GB
[14:39:21 TP7] Load weight begin. avail mem=77.10 GB
Loading safetensors checkpoint shards:   0% Completed | 0/37 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:   3% Completed | 1/37 [00:00<00:07,  4.61it/s]
Loading safetensors checkpoint shards:   5% Completed | 2/37 [00:00<00:08,  4.28it/s]
Loading safetensors checkpoint shards:   8% Completed | 3/37 [00:00<00:08,  4.15it/s]
Loading safetensors checkpoint shards:  11% Completed | 4/37 [00:00<00:08,  4.02it/s]
Loading safetensors checkpoint shards:  14% Completed | 5/37 [00:01<00:07,  4.06it/s]
Loading safetensors checkpoint shards:  16% Completed | 6/37 [00:01<00:07,  4.22it/s]
Loading safetensors checkpoint shards:  19% Completed | 7/37 [00:01<00:06,  4.31it/s]
Loading safetensors checkpoint shards:  22% Completed | 8/37 [00:01<00:06,  4.32it/s]
Loading safetensors checkpoint shards:  24% Completed | 9/37 [00:02<00:05,  4.99it/s]
Loading safetensors checkpoint shards:  27% Completed | 10/37 [00:02<00:05,  4.65it/s]
Loading safetensors checkpoint shards:  30% Completed | 11/37 [00:02<00:06,  4.30it/s]
Loading safetensors checkpoint shards:  32% Completed | 12/37 [00:02<00:05,  4.66it/s]
Loading safetensors checkpoint shards:  35% Completed | 13/37 [00:02<00:05,  4.64it/s]
Loading safetensors checkpoint shards:  38% Completed | 14/37 [00:03<00:05,  4.56it/s]
Loading safetensors checkpoint shards:  41% Completed | 15/37 [00:03<00:04,  4.55it/s]
Loading safetensors checkpoint shards:  43% Completed | 16/37 [00:03<00:04,  4.53it/s]
Loading safetensors checkpoint shards:  46% Completed | 17/37 [00:03<00:04,  4.33it/s]
Loading safetensors checkpoint shards:  49% Completed | 18/37 [00:04<00:04,  4.40it/s]
Loading safetensors checkpoint shards:  51% Completed | 19/37 [00:04<00:03,  4.50it/s]
Loading safetensors checkpoint shards:  54% Completed | 20/37 [00:04<00:03,  4.51it/s]
Loading safetensors checkpoint shards:  57% Completed | 21/37 [00:04<00:03,  4.57it/s]
Loading safetensors checkpoint shards:  59% Completed | 22/37 [00:04<00:03,  4.36it/s]
Loading safetensors checkpoint shards:  62% Completed | 23/37 [00:05<00:03,  4.41it/s]
Loading safetensors checkpoint shards:  65% Completed | 24/37 [00:05<00:02,  4.44it/s]
Loading safetensors checkpoint shards:  68% Completed | 25/37 [00:05<00:02,  4.28it/s]
Loading safetensors checkpoint shards:  70% Completed | 26/37 [00:05<00:02,  4.37it/s]
Loading safetensors checkpoint shards:  73% Completed | 27/37 [00:06<00:02,  4.27it/s]
Loading safetensors checkpoint shards:  76% Completed | 28/37 [00:06<00:02,  4.35it/s]
Loading safetensors checkpoint shards:  78% Completed | 29/37 [00:06<00:01,  4.42it/s]
Loading safetensors checkpoint shards:  81% Completed | 30/37 [00:06<00:01,  4.26it/s]
Loading safetensors checkpoint shards:  84% Completed | 31/37 [00:07<00:01,  4.10it/s]
Loading safetensors checkpoint shards:  86% Completed | 32/37 [00:07<00:01,  4.11it/s]
Loading safetensors checkpoint shards:  89% Completed | 33/37 [00:07<00:00,  4.13it/s]
Loading safetensors checkpoint shards:  92% Completed | 34/37 [00:07<00:00,  4.14it/s]
Loading safetensors checkpoint shards:  95% Completed | 35/37 [00:08<00:00,  4.24it/s]
Loading safetensors checkpoint shards:  97% Completed | 36/37 [00:08<00:00,  4.36it/s]
[14:39:31 TP4] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=59.64 GB
[14:39:31 TP7] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=60.11 GB
[14:39:31 TP6] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=59.64 GB
[14:39:31 TP2] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=59.64 GB
Loading safetensors checkpoint shards: 100% Completed | 37/37 [00:08<00:00,  4.51it/s]
Loading safetensors checkpoint shards: 100% Completed | 37/37 [00:08<00:00,  4.38it/s]

[14:39:31 TP0] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=59.73 GB
[14:39:31 TP3] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=59.64 GB
[14:39:31 TP1] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=59.64 GB
[14:39:31 TP5] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=59.64 GB
[14:39:31 TP6] Memory pool end. avail mem=12.45 GB
[14:39:31 TP5] Memory pool end. avail mem=12.45 GB
[14:39:31 TP0] Memory pool end. avail mem=12.54 GB
[14:39:31 TP3] Memory pool end. avail mem=12.45 GB
[14:39:31 TP7] Memory pool end. avail mem=12.92 GB
[14:39:31 TP1] Memory pool end. avail mem=12.45 GB
[14:39:31 TP4] Memory pool end. avail mem=12.45 GB
[14:39:31 TP2] Memory pool end. avail mem=12.45 GB
[14:39:31 TP6] Capture cuda graph begin. This can take up to several minutes.
[14:39:31 TP7] Capture cuda graph begin. This can take up to several minutes.
[14:39:31 TP5] Capture cuda graph begin. This can take up to several minutes.
[14:39:31 TP3] Capture cuda graph begin. This can take up to several minutes.
[14:39:31 TP0] Capture cuda graph begin. This can take up to several minutes.
[14:39:31 TP1] Capture cuda graph begin. This can take up to several minutes.
[14:39:31 TP4] Capture cuda graph begin. This can take up to several minutes.
[14:39:31 TP2] Capture cuda graph begin. This can take up to several minutes.
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
INFO 09-11 14:39:46 custom_all_reduce.py:223] Registering 3703 cuda graph addresses
[14:39:48 TP0] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
[14:39:48 TP4] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
[14:39:48 TP1] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
[14:39:48 TP6] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
[14:39:48 TP3] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
[14:39:48 TP2] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
[14:39:48 TP7] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
[14:39:48 TP5] max_total_num_tokens=1218251, max_prefill_tokens=16384, max_running_requests=5119, context_len=32768
INFO:     Started server process [37328]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)

Exception in thread Thread-1 (_wait_and_warmup):
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/site-packages/sglang/srt/server.py", line 449, in _wait_and_warmup
    model_info = res.json()
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Reproduction

python -m sglang.launch_server --model-path models/Qwen2-72B-Instruct --port 30000 --tp 8

### Environment

```
(vllm) user@node14:~$ python3 -m sglang.check_env
/home/user/anaconda3/envs/vllm/lib/python3.10/site-packages/pydantic/_internal/_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Python: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda-12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.91
CUDA Driver Version: 535.154.05
PyTorch: 2.4.0+cu121
sglang: 0.3.0
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.4
aiohttp: 3.9.5
fastapi: 0.111.1
hf_transfer: 0.1.8
huggingface_hub: 0.23.4
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.1
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.5
multipart: 0.0.9
openai: 1.44.1
anthropic: 0.34.2
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    NIC9    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     0-23,96-119     0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     0-23,96-119     0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     0-23,96-119     0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    SYS     SYS     SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     24-47,120-143   1               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     SYS     SYS     SYS     SYS     PIX     SYS     SYS     SYS     SYS     48-71,144-167   2               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     SYS     SYS     SYS     SYS     SYS     PIX     SYS     SYS     SYS     48-71,144-167   2               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX     SYS     SYS     48-71,144-167   2               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX     SYS     72-95,168-191   3               N/A
NIC0    PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC1    SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC2    SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     SYS     SYS     SYS     SYS
NIC3    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     SYS     SYS     PXB
NIC4    SYS     SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     SYS     SYS
NIC5    SYS     SYS     SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS     SYS
NIC6    SYS     SYS     SYS     SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS     SYS
NIC7    SYS     SYS     SYS     SYS     SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS     SYS
NIC8    SYS     SYS     SYS     SYS     SYS     SYS     SYS     PIX     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X      SYS
NIC9    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS     PXB     SYS     SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_6
  NIC5: mlx5_7
  NIC6: mlx5_8
  NIC7: mlx5_9
  NIC8: mlx5_10
  NIC9: mlx5_bond_0


ulimit soft: 1048576
```

**Comment by Ke-shuang** [comment]
I encountered the same problem and don't know how to solve it

**Comment by merrymercy** [comment]
Can you help to print this object?

```
  File "/home/user/anaconda3/envs/vllm/lib/python3.10/site-packages/sglang/srt/server.py", line 449, in _wait_and_warmup
    model_info = res.json()
```

insert a `print(res.text)` before this line

**Comment by merrymercy** [comment]
Or apply this patch https://github.com/sgl-project/sglang/pull/1390/files so we can know better about this error

**Comment by eyuansu62** [comment]
I have tried your new patch and the following is the output:
```
[19:45:50] Initialization failed. warmup error: Traceback (most recent call last):
  File "/root/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/server.py", line 443, in _wait_and_warmup
    assert res.status_code == 200, f"{res=}, {res.text=}"
AssertionError: res=<Response [502]>, res.text=''
```

**Comment by eyuansu62** [comment]
It seems that we can solve it by changing both the port and host simultaneously.
```
python -m sglang.launch_server --model-path Qwen/Qwen2-0.5B-Instruct  --port 3000 --host 0.0.0.0
```

**Comment by merrymercy** [comment]
@eyuansu62 Yeah, your local settings may have special permissions for certain ports. Close this for now as it is resolved.
