### ISSUE TITLE
[Bug] tp-4 start timeout

### ISSUE THREAD

**Issue by siddhatiwari** [sgl-project/sglang#1485]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

Trying to run `CarrotAI/Mistral-Large-Instruct-2407-FP8-Dynamic-8bit` with tp 4 fails with a timeout. It also fails with the suggested `--disable-cuda-graph` flag. 

But decreasing `mem-fraction-static` works. Not sure if this is a known issue/intended since there are suggestions in the error response, will close this issue if so.

### Reproduction

Run:
```
CUDA_VISIBLE_DEVICES=0,1,2,3  python -m sglang.launch_server --model-path CarrotAI/Mistral-Large-Instruct-2407-FP8-Dynamic-8bit --port 30003 --tp 4 --mem-fraction-static 0.98 --host 0.0.0.0 --context-length 8192
```

After a while, it fails with this error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 959, in run_tp_server
    model_server = ModelTpServer(
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 100, in __init__
    self.model_runner = ModelRunner(
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 128, in __init__
    self.init_cuda_graphs()
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 468, in init_cuda_graphs
    self.cuda_graph_runner = CudaGraphRunner(self)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/model_executor/cuda_graph_runner.py", line 149, in __init__
    raise Exception(
Exception: Capture cuda graph failed: [../third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 1800000ms for recv operation to complete
Possible solutions:
1. disable cuda graph by --disable-cuda-graph
2. set --mem-fraction-static to a smaller value
3. disable torch compile by not using --enable-torch-compile
Open an issue on GitHub https://github.com/sgl-project/sglang/issues/new/choose
```

Run:
```
CUDA_VISIBLE_DEVICES=0,1,2,3  python -m sglang.launch_server --model-path CarrotAI/Mistral-Large-Instruct-2407-FP8-Dynamic-8bit --port 30003 --tp 4 --mem-fraction-static 0.98 --host 0.0.0.0 --context-length 8192 --disable-cuda-graph
```

Fails with error:
```
Process Process-1:2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 969, in run_tp_server
    model_server.exposed_step(recv_reqs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 239, in exposed_step
    self.forward_step()
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 259, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 560, in forward_prefill_batch
    logits_output = self.model_runner.forward(batch)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 523, in forward
    return self.forward_extend(batch)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 491, in forward_extend
    return self.model.forward(
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/models/llama.py", line 317, in forward
    return self.logits_processor(
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/sglang/srt/layers/logits_processor.py", line 181, in forward
    last_logits = tensor_model_parallel_all_gather(last_logits)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/vllm/distributed/communication_op.py", line 17, in tensor_model_parallel_all_gather
    return get_tp_group().all_gather(input_, dim)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/vllm/distributed/parallel_state.py", line 318, in all_gather
    torch.distributed.all_gather_into_tensor(output_tensor,
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/sglang_env/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 3200, in all_gather_into_tensor
    work = group._allgather_base(output_tensor, input_tensor, opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/NCCLUtils.cpp:76, unhandled cuda error (run with NCCL_DEBUG=INFO for details), NCCL version 2.20.5
ncclUnhandledCudaError: Call to CUDA function failed.
Last error:
Failed to CUDA calloc 268435456 bytes
```

### Environment

```
Python: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: None
PyTorch: 2.4.0+cu121
sglang: 0.3.1.post2
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.5
fastapi: 0.115.0
hf_transfer: 0.1.8
huggingface_hub: 0.25.0
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.9
openai: 1.46.1
anthropic: 0.34.2
NVIDIA Topology: 
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	NIC0	NIC1	NIC2	NIC3	NIC4	NIC5	NIC6	NIC7	NIC8	NIC9	NIC10	NIC11	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	NV18	NV18	NV18	NV18	NV18	NV18	NV18	PIX	PIX	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	0-12	0	N/A
GPU1	NV18	 X 	NV18	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	26-38	2	N/A
GPU2	NV18	NV18	 X 	NV18	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	39-51	3	N/A
GPU3	NV18	NV18	NV18	 X 	NV18	NV18	NV18	NV18	SYS	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	13-25	1	N/A
GPU4	NV18	NV18	NV18	NV18	 X 	NV18	NV18	NV18	SYS	SYS	SYS	SYS	SYS	SYS	PIX	PIX	PIX	SYS	SYS	SYS	52-64	4	N/A
GPU5	NV18	NV18	NV18	NV18	NV18	 X 	NV18	NV18	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	SYS	SYS	78-90	6	N/A
GPU6	NV18	NV18	NV18	NV18	NV18	NV18	 X 	NV18	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	SYS	91-103	7	N/A
GPU7	NV18	NV18	NV18	NV18	NV18	NV18	NV18	 X 	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	65-77	5	N/A
NIC0	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	PIX	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS			
NIC1	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	 X 	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS			
NIC2	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	PIX	 X 	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS			
NIC3	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS			
NIC4	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	SYS	SYS	SYS	SYS	SYS	SYS	SYS			
NIC5	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	SYS	SYS	SYS	SYS	SYS	SYS			
NIC6	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	PIX	PIX	SYS	SYS	SYS			
NIC7	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	 X 	PIX	SYS	SYS	SYS			
NIC8	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	PIX	 X 	SYS	SYS	SYS			
NIC9	SYS	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	SYS	SYS			
NIC10	SYS	SYS	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 	SYS			
NIC11	SYS	SYS	SYS	SYS	SYS	SYS	SYS	PIX	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	SYS	 X 			

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_4
  NIC5: mlx5_5
  NIC6: mlx5_6
  NIC7: mlx5_7
  NIC8: mlx5_8
  NIC9: mlx5_9
  NIC10: mlx5_10
  NIC11: mlx5_11


ulimit soft: 1024
```

**Comment by merrymercy** [comment]
Thanks for reporting this.

`--mem-fraction-static 0.98` is too high and the OOM is expected. The default value is around 0.85. You can only slightly increase that.
