### ISSUE TITLE
unable to install uvloop in windows (dependency)

### ISSUE THREAD

**Issue by Sai-s19** [sgl-project/sglang#152]
Getting this error

pip install sglang[all]
Requirement already satisfied: sglang[all] in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (0.1.11)
Requirement already satisfied: requests in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from sglang[all]) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from requests->sglang[all]) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from requests->sglang[all]) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from requests->sglang[all]) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from requests->sglang[all]) (2023.11.17)
Collecting anthropic (from sglang[all])
  Using cached anthropic-0.15.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: numpy in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from sglang[all]) (1.24.4)
Requirement already satisfied: openai>=1.0 in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from sglang[all]) (1.6.1)
Requirement already satisfied: aiohttp in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from sglang[all]) (3.9.1)
Requirement already satisfied: fastapi in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from sglang[all]) (0.109.2)
Requirement already satisfied: psutil in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from sglang[all]) (5.9.7)
Collecting rpyc (from sglang[all])
  Using cached rpyc-5.3.1-py3-none-any.whl (74 kB)
Requirement already satisfied: torch in c:\users\keshav s\anaconda3\envs\llm-workspace\lib\site-packages (from sglang[all]) (2.1.2)
Collecting uvloop (from sglang[all])
  Using cached uvloop-0.19.0.tar.gz (2.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Keshav S\anaconda3\envs\llm-workspace\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Keshav S\anaconda3\envs\llm-workspace\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Keshav S\anaconda3\envs\llm-workspace\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Keshav S\AppData\Local\Temp\pip-build-env-xnl04q07\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Keshav S\AppData\Local\Temp\pip-build-env-xnl04q07\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\Keshav S\AppData\Local\Temp\pip-build-env-xnl04q07\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by aliencaocao** [comment]
its clear enough. you cant use sglang on windows. Use WSL 2 instead

**Comment by CoqueTornado** [comment]
same here.... SGLang installation drop me today this line

Bard said this brief to what you posted (similar to what I had):
RuntimeError: uvloop does not support Windows at the moment
