### ISSUE TITLE
[Bug] IndexError: list index out of range

### ISSUE THREAD

**Issue by lvxianfeng-git** [sgl-project/sglang#1526]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

python3 -m sglang.launch_server --model-path lmms-lab/llava-onevision-qwen2-7b-ov --port=30000 --chat-template=chatml-llava
[17:39:10] server_args=ServerArgs(model_path='lmms-lab/llava-onevision-qwen2-7b-ov', tokenizer_path='lmms-lab/llava-onevision-qwen2-7b-ov', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', dtype='auto', kv_cache_dtype='auto', trust_remote_code=False, context_length=None, quantization=None, served_model_name='lmms-lab/llava-onevision-qwen2-7b-ov', chat_template='chatml-llava', is_embedding=False, host='127.0.0.1', port=30000, additional_ports=[30001, 30002, 30003, 30004], mem_fraction_static=0.88, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=1, stream_interval=1, random_seed=229169063, constrained_json_whitespace_pattern=None, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key=None, file_storage_pth='SGLang_storage', dp_size=1, load_balance_method='round_robin', nccl_init_addr=None, nnodes=1, node_rank=None, json_model_override_args='{}', attention_backend='flashinfer', sampling_backend='flashinfer', disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, enable_mixed_chunk=False, enable_torch_compile=False, max_torch_compile_bs=32, torchao_config='', enable_p2p_check=False, triton_attention_reduce_in_fp32=False, lora_paths=None, max_loras_per_batch=8)
[17:39:11 TP0] Automatically turn off --chunked-prefill-size and adjust --mem-fraction-static for multimodal models.
[17:39:12 TP0] Init nccl begin.
[17:39:12 TP0] Load weight begin. avail mem=23.43 GB
[17:39:13 TP0] lm_eval is not installed, GPTQ may not be usable
[17:39:14] Use chat template: chatml-llava
INFO 09-27 17:39:14 weight_utils.py:236] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  25% Completed | 1/4 [00:03<00:10,  3.66s/it]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:07<00:07,  3.66s/it]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:08<00:02,  2.44s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:12<00:00,  2.94s/it]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:12<00:00,  3.01s/it]

[17:39:28 TP0] Load weight end. type=LlavaQwenForCausalLM, dtype=torch.float16, avail mem=8.23 GB
[17:39:28 TP0] Memory pool end. avail mem=2.51 GB
[17:39:28 TP0] Capture cuda graph begin. This can take up to several minutes.
[17:39:37 TP0] max_total_num_tokens=101381, max_prefill_tokens=16384, max_running_requests=2049, context_len=32768
INFO:     Started server process [74616]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
INFO:     127.0.0.1:49624 - "GET /get_model_info HTTP/1.1" 200 OK
[17:39:39 TP0] Prefill batch. #new-seq: 1, #new-token: 6, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
INFO:     127.0.0.1:49632 - "POST /generate HTTP/1.1" 200 OK
[17:39:39] The server is fired up and ready to roll!
[17:39:58 TP0] Prefill batch. #new-seq: 1, #new-token: 26, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
[17:39:59 TP0] Decode batch. #running-req: 1, #token: 64, token usage: 0.00, gen throughput (token/s): 1.89, #queue-req: 0
[17:39:59 TP0] Decode batch. #running-req: 1, #token: 104, token usage: 0.00, gen throughput (token/s): 50.56, #queue-req: 0
[17:40:00 TP0] Decode batch. #running-req: 1, #token: 144, token usage: 0.00, gen throughput (token/s): 50.54, #queue-req: 0
INFO:     127.0.0.1:59192 - "POST /generate HTTP/1.1" 200 OK
[17:40:32 TP0] Prefill batch. #new-seq: 1, #new-token: 9, #cached-token: 17, cache hit rate: 29.31%, token usage: 0.00, #running-req: 0, #queue-req: 0
[17:40:32 TP0] Decode batch. #running-req: 1, #token: 53, token usage: 0.00, gen throughput (token/s): 1.25, #queue-req: 0
[17:40:33 TP0] Decode batch. #running-req: 1, #token: 93, token usage: 0.00, gen throughput (token/s): 50.61, #queue-req: 0
INFO:     127.0.0.1:57398 - "POST /generate HTTP/1.1" 200 OK
[17:41:00 TP0] Prefill batch. #new-seq: 1, #new-token: 1847, #cached-token: 14, cache hit rate: 1.62%, token usage: 0.00, #running-req: 0, #queue-req: 0
[17:41:00 TP0] Exception in ModelTpServer:
Traceback (most recent call last):
  File "/home/nvidia/sglang/python/sglang/srt/managers/tp_worker.py", line 240, in exposed_step
    self.forward_step()
  File "/home/nvidia/sglang/python/sglang/srt/managers/tp_worker.py", line 259, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/home/nvidia/sglang/python/sglang/srt/managers/tp_worker.py", line 560, in forward_prefill_batch
    logits_output = self.model_runner.forward(batch)
  File "/home/nvidia/sglang/python/sglang/srt/model_executor/model_runner.py", line 516, in forward
    return self.forward_extend_multi_modal(batch)
  File "/home/nvidia/sglang/python/sglang/srt/model_executor/model_runner.py", line 503, in forward_extend_multi_modal
    return self.model.forward(
  File "/opt/conda/envs/LLaVA-NeXT/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nvidia/sglang/python/sglang/srt/models/llava.py", line 188, in forward
    if modalities_list[image_idx] == "image":
IndexError: list index out of range

[17:41:00 TP0] Exception in ControllerSingle:
Traceback (most recent call last):
  File "/home/nvidia/sglang/python/sglang/srt/managers/controller_single.py", line 160, in start_controller_process
    controller.loop_for_forward()
  File "/home/nvidia/sglang/python/sglang/srt/managers/controller_single.py", line 99, in loop_for_forward
    out_pyobjs = self.tp_server.exposed_step(recv_reqs)
  File "/opt/conda/envs/LLaVA-NeXT/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nvidia/sglang/python/sglang/srt/managers/tp_worker.py", line 240, in exposed_step
    self.forward_step()
  File "/home/nvidia/sglang/python/sglang/srt/managers/tp_worker.py", line 259, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/home/nvidia/sglang/python/sglang/srt/managers/tp_worker.py", line 560, in forward_prefill_batch
    logits_output = self.model_runner.forward(batch)
  File "/home/nvidia/sglang/python/sglang/srt/model_executor/model_runner.py", line 516, in forward
    return self.forward_extend_multi_modal(batch)
  File "/home/nvidia/sglang/python/sglang/srt/model_executor/model_runner.py", line 503, in forward_extend_multi_modal
    return self.model.forward(
  File "/opt/conda/envs/LLaVA-NeXT/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/nvidia/sglang/python/sglang/srt/models/llava.py", line 188, in forward
    if modalities_list[image_idx] == "image":
IndexError: list index out of range

[rank0]:W0927 17:41:00.442000 140445967414848 torch/_inductor/compile_worker/subproc_pool.py:126] SubprocPool unclean exit
Killed

### Reproduction

python3 -m sglang.launch_server --model-path lmms-lab/llava-onevision-qwen2-7b-ov --port=30000 --chat-template=chatml-llava

### Environment

     active environment : LLaVA-NeXT
    active env location : /opt/conda/envs/LLaVA-NeXT
            shell level : 1
       user config file : /home/nvidia/.condarc
 populated config files : /home/nvidia/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.3.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=cascadelake
                          __conda=24.5.0=0
                          __cuda=12.4=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : /opt/conda/pkgs
                          /home/nvidia/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/nvidia/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.12.3 Linux/5.15.0-122-generic ubuntu/22.04.5 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by Michael-Loving** [comment]
when i execute the fllowing python, sgl server crashed.

import requests

response = requests.post(
    "http://localhost:30000/generate",
    json={
        "text": "<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n"
        "<|im_start|>user\n<image>\nDescribe the image.<|im_end|>\n"
                "<|im_start|>assistant\n",
        "image_data": "example_image.png",
        "sampling_params": {
            "temperature": 0.3,
            "max_new_tokens": 768,
        },
    },
)
print(response.json())

**Comment by ddemillard** [comment]
I am seeing the same issue on a custom Llava 1.6 34b model that was previously working just fine. I am building Sglang from source.

**Comment by ddemillard** [comment]
This error occurs due to the adjustment to the new openai modalities format.

I think it was introduced in this hash: 662ecd93680c8195eda799cb9a497f93efdc521a

@lvxianfeng-git 
You can revert by this commit hash to have the server as working before: f64eae3a291ade9654f1b030878df098bdefa9ee

The problem with this change is that it breaks being able to call the commit as we did before using the /generate endpoint. It would be great to have this backward compatible.
