### ISSUE TITLE
offset = input_ids.index(self.config.image_token_index)

### ISSUE THREAD

**Issue by JAADARI** [sgl-project/sglang#161]
anyone faced this problem before ? :

Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/home/fjaadari/anaconda3/envs/llava/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 161, in exposed_step
    self.handle_generate_request(recv_req)
  File "/home/fjaadari/anaconda3/envs/llava/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 243, in handle_generate_request
    req.input_ids, req.image_offset = self.model_runner.model.pad_input_ids(
  File "/home/fjaadari/anaconda3/envs/llava/lib/python3.10/site-packages/sglang/srt/models/llava.py", line 63, in pad_input_ids
    offset = input_ids.index(self.config.image_token_index)
ValueError: 32000 is not in list

**Comment by isidentical** [comment]
This means you are not passing the `<image>` token in your prompt, make sure to include it (or use a chat template)

**Comment by Mr-Loevan** [comment]
same question
