### ISSUE TITLE
[Feature] GGUF support

### ISSUE THREAD

**Issue by remixer-dec** [sgl-project/sglang#1616]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Hi! Since .gguf format is already supported by vLLM, is it be possible to add support for it in SGLang server?

**Comment by merrymercy** [comment]
It should be easy. Could you give us an example command you want us to have?

**Comment by remixer-dec** [comment]
`python -m sglang.launch_server --model-path /path/to/model.gguf`

**Comment by hahmad2008** [comment]
@remixer-dec @merrymercy  
How to serve a gguf model? VLLM provided a tutorial for that like this https://docs.vllm.ai/en/latest/getting_started/examples/gguf_inference.html 

But how to inference with sglang?  @merrymercy  could you please provide a command to do that?
example for this model: `TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF`

**Comment by XYZliang** [comment]
> `python -m sglang.launch_server --model-path /path/to/model.gguf`

If you haven't tried it, please don't reply.. This doesn't work at all.

```
python -m sglang.launch_server --model-path /home/xyzliang/data/project/oil/gguf/v3_merge_Q4_K_M.gguf --port 30000 --mem-fraction-static 0.8
WARNING 11-08 15:09:00 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
[2024-11-08 15:09:08] server_args=ServerArgs(model_path='/home/xyzliang/data/project/oil/gguf/v3_merge_Q4_K_M.gguf', tokenizer_path='/home/xyzliang/data/project/oil/gguf/v3_merge_Q4_K_M.gguf', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=False, dtype='auto', kv_cache_dtype='auto', quantization=None, context_length=None, device='cuda', served_model_name='/home/xyzliang/data/project/oil/gguf/v3_merge_Q4_K_M.gguf', chat_template=None, is_embedding=False, host='127.0.0.1', port=30000, mem_fraction_static=0.8, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=1, stream_interval=1, random_seed=879353602, constrained_json_whitespace_pattern=None, decode_log_interval=40, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, api_key=None, file_storage_pth='SGLang_storage', enable_cache_report=False, watchdog_timeout=600, dp_size=1, load_balance_method='round_robin', dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, lora_paths=None, max_loras_per_batch=8, attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='outlines', disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_penalizer=False, disable_nan_detection=False, enable_overlap_schedule=False, enable_mixed_chunk=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=160, torchao_config='', enable_p2p_check=False, triton_attention_reduce_in_fp32=False, num_continuous_decode_steps=1)
WARNING 11-08 15:09:14 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
WARNING 11-08 15:09:14 cuda.py:22] You are using a deprecated `pynvml` package. Please install `nvidia-ml-py` instead, and make sure to uninstall `pynvml`. When both of them are installed, `pynvml` will take precedence and cause errors. See https://pypi.org/project/pynvml for more information.
[2024-11-08 15:09:22] Traceback (most recent call last):
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 154, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '/home/xyzliang/data/project/oil/gguf/v3_merge_Q4_K_M.gguf'. Use `repo_type` argument if needed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/sglang/srt/managers/detokenizer_manager.py", line 216, in run_detokenizer_process
    manager = DetokenizerManager(server_args, port_args)
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/sglang/srt/managers/detokenizer_manager.py", line 72, in __init__
    self.tokenizer = get_tokenizer(
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/sglang/srt/hf_transformers_utils.py", line 129, in get_tokenizer
    tokenizer = AutoTokenizer.from_pretrained(
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 844, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "/opt/anaconda3/envs/BDCI2024/lib/python3.10/site-packages/transformers/utils/hub.py", line 469, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/home/xyzliang/data/project/oil/gguf/v3_merge_Q4_K_M.gguf'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
```

**Comment by remixer-dec** [comment]
@XYZliang maybe read the previous comment?  It's not supposed to be working, I replied the command that I was asked for

**Comment by XYZliang** [comment]
> @XYZliang maybe read the previous comment? It's not supposed to be working, I replied the command that I was asked for

Sorry, I didn't pay attention to the users who commented...

**Comment by whk6688** [comment]
not work. error is:

(python311) whk@VM-2-13-ubuntu:~/code/qwen25-3b$ python -m sglang.launch_server --model-path Qwen2.5-3B-Instruct-q5_k_m.gguf  --port 8075 --host 0.0.0.0 --mem-fraction-static 0.2 --chat-template template.json
[2024-11-14 11:42:24] server_args=ServerArgs(model_path='Qwen2.5-3B-Instruct-q5_k_m.gguf', tokenizer_path='Qwen2.5-3B-Instruct-q5_k_m.gguf', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=False, dtype='auto', kv_cache_dtype='auto', quantization=None, context_length=None, device='cuda', served_model_name='Qwen2.5-3B-Instruct-q5_k_m.gguf', chat_template='template.json', is_embedding=False, host='0.0.0.0', port=8075, mem_fraction_static=0.2, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, tp_size=1, stream_interval=1, random_seed=995653076, constrained_json_whitespace_pattern=None, watchdog_timeout=300, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_pth='SGLang_storage', enable_cache_report=False, dp_size=1, load_balance_method='round_robin', dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, lora_paths=None, max_loras_per_batch=8, attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='outlines', disable_flashinfer=False, disable_flashinfer_sampling=False, disable_radix_cache=False, disable_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_penalizer=False, disable_nan_detection=False, enable_overlap_schedule=False, enable_mixed_chunk=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=160, torchao_config='', enable_p2p_check=False, triton_attention_reduce_in_fp32=False, num_continuous_decode_steps=1, delete_ckpt_after_loading=False)
Traceback (most recent call last):
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/transformers/configuration_utils.py", line 668, in _get_config_dict
    config_dict = cls._dict_from_json_file(resolved_config_file)
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/transformers/configuration_utils.py", line 771, in _dict_from_json_file
    text = reader.read()
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 8: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/sglang/launch_server.py", line 16, in <module>
    raise e
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/sglang/launch_server.py", line 14, in <module>
    launch_server(server_args)
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/sglang/srt/server.py", line 457, in launch_server
    launch_engine(server_args=server_args)
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/sglang/srt/server.py", line 429, in launch_engine
    tokenizer_manager = TokenizerManager(server_args, port_args)
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/sglang/srt/managers/tokenizer_manager.py", line 103, in __init__
    self.model_config = ModelConfig(
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/sglang/srt/configs/model_config.py", line 46, in __init__
    self.hf_config = get_config(
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/sglang/srt/hf_transformers_utils.py", line 66, in get_config
    config = AutoConfig.from_pretrained(
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1017, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/wanghaikuan/anaconda3/envs/python311/lib/python3.10/site-packages/transformers/configuration_utils.py", line 672, in _get_config_dict
    raise EnvironmentError(
OSError: It looks like the config file at 'Qwen2.5-3B-Instruct-q5_k_m.gguf' is not a valid JSON file.

**Comment by merrymercy** [comment]
It should be easy to support. Contributions are welcome! Or you can convert that to HF format.

**Comment by zhengy001** [comment]
Please take a look at this PR: https://github.com/sgl-project/sglang/pull/2215

**Comment by merrymercy** [comment]
supported by https://github.com/sgl-project/sglang/pull/2215

**Comment by remixer-dec** [comment]
Let's go! Thank you!

**Comment by remixer-dec** [comment]
Just updated SGLang and tried to load GGUF models:
The output quality differs a lot from llama.cpp with the same model. It just kees outputting nonsense in SGLang.
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/7844f699-99ca-4569-bd13-b90b01d1b21c">

**Comment by remixer-dec** [comment]
The same model loaded in vLLM works totally fine as well
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/d3e9c569-10fc-41f3-b4df-f83c3b3e9de2">

**Comment by zhengy001** [comment]
> Just updated SGLang and tried to load GGUF models: The output quality differs a lot from llama.cpp with the same model. It just kees outputting nonsense in SGLang. <img alt="image" width="1055" src="https://private-user-images.githubusercontent.com/6587642/393054624-7844f699-99ca-4569-bd13-b90b01d1b21c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2NDIzNjksIm5iZiI6MTczMzY0MjA2OSwicGF0aCI6Ii82NTg3NjQyLzM5MzA1NDYyNC03ODQ0ZjY5OS05OWNhLTQ1NjktYmQxMy1iOTBiMDFkMWIyMWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDhUMDcxNDI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmIwYjE0NTU2YWU0OWZiNTdmMDdlMTAwODBmYTZiNzE0ZmQzY2Y0YjVjZTRkZGVmZjhmOWQyMjZhNjgwMTBlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ycBSiWCYg6BoL8djUxfdygo45cLdXz_hgUZhEVvP98I">

@remixer-dec 
Applying this patch should be good
<img width="525" alt="patch" src="https://github.com/user-attachments/assets/ee818885-8477-4d93-9cdf-226fe43c3ed2">

**Comment by remixer-dec** [comment]
@zhengy001 it is better (at least no collapse), but it keeps generating text without ever stopping (by default)
<img width="1018" alt="after-patch" src="https://github.com/user-attachments/assets/826c5b2a-cb5c-4ffd-aafd-2da1aff7f34e">
P.S. if you manually pass stop sequence <pre>&lt;/s&gt;</pre> in each request, it does stop correctly, but such information should be loaded from model metadata and, if specified, from --chat-template template.

Currently when custom chat template is specified:
for GPTQ model:
<img width="465" alt="GPTQ" src="https://github.com/user-attachments/assets/3167e400-221c-414a-a8fc-fdf1504d967d">
vs GGUF:
<img width="502" alt="GGUF" src="https://github.com/user-attachments/assets/0343b056-8ab2-48bd-82bd-c6cc73cb4b59">

**Comment by zhengy001** [comment]
> @zhengy001 it is better (at least no collapse), but it keeps generating text without ever stopping (by default) <img alt="after-patch" width="1018" src="https://private-user-images.githubusercontent.com/6587642/393659453-826c5b2a-cb5c-4ffd-aafd-2da1aff7f34e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjk5NTksIm5iZiI6MTczNDA2OTY1OSwicGF0aCI6Ii82NTg3NjQyLzM5MzY1OTQ1My04MjZjNWIyYS1jYjVjLTRmZmQtYWFmZC0yZGExYWZmN2YzNGUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMDYwMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzVhMzdkNWQ3N2EzYTM3Y2FmZjc0OWU4NWYxYzFhNTNkMDVmMWUzYTY3ZTFhY2VlZWJlMThhNTUwMWVlMjFiNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.JPR-OO8vAli6WG1fSmHNqtYlDZ_QvINzKigbR44qO0k"> P.S. if you manually pass stop sequence
> 
> </s>
> in each request, it does stop correctly, but such information should be loaded from model metadata and, if specified, from --chat-template template.
> Currently when custom chat template is specified: for GPTQ model: <img alt="GPTQ" width="465" src="https://private-user-images.githubusercontent.com/6587642/393663656-3167e400-221c-414a-a8fc-fdf1504d967d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjk5NTksIm5iZiI6MTczNDA2OTY1OSwicGF0aCI6Ii82NTg3NjQyLzM5MzY2MzY1Ni0zMTY3ZTQwMC0yMjFjLTQxNGEtYThmYy1mZGYxNTA0ZDk2N2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMDYwMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE4ODUxY2ViZWYxNjk0MzE3MTY3MjdjZDM5ZDQwZWIwNWFkZmFiYTE4Njg4ZTZlNjExM2VjODAzNDQ4N2ZjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PRlYXOc_T8eKOQ5zqvhpQsW-p-C5z4I0azygIT-RlL0"> vs GGUF: <img alt="GGUF" width="502" src="https://private-user-images.githubusercontent.com/6587642/393663876-0343b056-8ab2-48bd-82bd-c6cc73cb4b59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwNjk5NTksIm5iZiI6MTczNDA2OTY1OSwicGF0aCI6Ii82NTg3NjQyLzM5MzY2Mzg3Ni0wMzQzYjA1Ni04YWIyLTQ4YmQtODJiZC1jNmNjNzNjYjRiNTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMDYwMDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDFkZGM5NDZjZWNkMDVjNzFkMzQ4ZDk3ZDAwZmQ4MWE3YWQwNzk3NTBlMTY2MTk4MDEyOGEzMzFjODM0YjE0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ts1C-H8-poaSvm50PKNSLdrMxjV-vyW_b8MRnnynmcY">

Model EOS is not loaded correctly.

Pls check this PR
https://github.com/sgl-project/sglang/pull/2475

**Comment by JunweiLiang** [comment]
It seems this support has been reverted. Why is that?

https://github.com/sgl-project/sglang/pull/2287

**Comment by remixer-dec** [comment]
@JunweiLiang no, it was "revert revert" which adds it back after pushing other commits before

**Comment by JunweiLiang** [comment]
@remixer-dec Sorry to bother you, but it seems using Deepseek GGUF fails with version 0.4.2.post1. Do you know what might be the problem? Thanks so much!
`$ python -m sglang.launch_server --model-path models/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf --tp 4 --enable-p2p-check --host 0.0.0.0 --port 6666 --trust-remote-code`
Errors:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/junweil/.local/lib/python3.10/site-packages/sglang/launch_server.py", line 14, in <module>
    launch_server(server_args)
  File "/home/junweil/.local/lib/python3.10/site-packages/sglang/srt/entrypoints/http_server.py", line 491, in launch_server
    tokenizer_manager, scheduler_info = _launch_subprocesses(server_args=server_args)
  File "/home/junweil/.local/lib/python3.10/site-packages/sglang/srt/entrypoints/engine.py", line 426, in _launch_subprocesses
    tokenizer_manager = TokenizerManager(server_args, port_args)
  File "/home/junweil/.local/lib/python3.10/site-packages/sglang/srt/managers/tokenizer_manager.py", line 134, in __init__
    self.model_config = ModelConfig(
  File "/home/junweil/.local/lib/python3.10/site-packages/sglang/srt/configs/model_config.py", line 53, in __init__
    self.hf_config = get_config(
  File "/home/junweil/.local/lib/python3.10/site-packages/sglang/srt/hf_transformers_utils.py", line 67, in get_config
    config = AutoConfig.from_pretrained(
  File "/home/junweil/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1054, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/junweil/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 591, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/junweil/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 650, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/junweil/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 374, in cached_file
    raise EnvironmentError(
OSError: models does not appear to have a file named models/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf. Checkout 'https://huggingface.co/models/tree/None' for available files.
```

The files are there:
```
$ ls models/
DeepSeek-R1-Distill-Qwen-32B  DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf  DeepSeek-R1-Distill-Qwen-32B-Q8_0.gguf
```

**Comment by remixer-dec** [comment]
I'm very confused, why are Github releases not aligned with PyPi releases?
Github releases are still stuck at **0.4.1** while pypi is already at **0.4.2.post2** 

Anyways, @JunweiLiang everything works just fine, you probably forgot to add `--quantization gguf`

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/25f6ea75-b647-4f53-be86-2de4a403873c" />

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/5abe8b83-9831-4dd9-8481-7193b6d7c4d3" />

**Comment by JunweiLiang** [comment]
@remixer-dec Thanks you! With `--quantization gguf` I found that `--model-path models/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf` does not work but `--model-path DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf` works. There might be some bug in the model path parsing. 

I have a question on how SGLang utilizes the GGUF model though. It seems `Q4_K_M` takes up the same amount of VRAM as the original non-quantized model. Is that expected? Thanks so much!

**Comment by zhengy001** [comment]
> @remixer-dec Thanks you! With `--quantization gguf` I found that `--model-path models/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf` does not work but `--model-path DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf` works. There might be some bug in the model path parsing. 
> 
> I have a question on how SGLang utilizes the GGUF model though. It seems `Q4_K_M` takes up the same amount of VRAM as the original non-quantized model. Is that expected? Thanks so much!

You may use path of /models/DeepSeek-R1-Distill-Qwen-32B-Q4_K_M.gguf(/ at the beginning) depends on where the gguf file is. I think Q4 should be about half of original model with FP16. Need investigation.

**Comment by remixer-dec** [comment]
> takes up the same amount of VRAM as the original non-quantized model


I think we should address this question to the creators of sglang, the amount of vram is usually controlled via `--mem-fraction-static` parameter, I do find it inconvenient that for every model we have to brute force this parameter's value by trying different numbers until it fails, to find out how much VRAM can we free up. Besides this, it will cut the effective context length (max_total_num_tokens in the logs) if you set the parameter too low, but not low enough to crash. So we should aim for a `--mem-fraction-static` number that makes `max_total_num_tokens == context_length`

In general, I noticed that models loaded in sglang (and not only gguf) consume slightly more VRAM than in llama.cpp, usually you expect that the model will take up the same amount of memory as it uses on disk, plus a few GB for the context length, but it feels like something else is consuming the memory, I suspect that it is KV cache, I tried `--disable-radix-cache` but it still shows in the logs that KV cache is used.

So far, for the model that I tested (DeepSeek-R1-Distill-Qwen-32B-Q2_K.gguf) with `--context-length` set to `4096` and `--mem-fraction-static` set to `0.56` I see the following numbers:

| Engine | VRAM |
|--------|--------|
| llama.cpp | 12.99G |
| sglang | 14.27G |
| sglang (cuda graph on) | 14.39G |

**Comment by remixer-dec** [comment]
@zhengy001 I noticed that for some reason the model does not start its reply with `<think>` in sglang==0.4.2.post2, possibly related to templates?

llama.cpp:
(always starts with `<think>`)
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/e14b9efd-450d-4a4d-8511-731ab085a471" />

sglang:
<img width="600" alt="Image" src="https://github.com/user-attachments/assets/6ce124d5-700b-4d52-be0d-f530b0960cc4" />

**Comment by zhengy001** [comment]
> @zhengy001 I noticed that for some reason the model does not start its reply with `<think>` in sglang==0.4.2.post2, possibly related to templates?
> 
> llama.cpp:
> (always starts with `<think>`)
> <img width="600" alt="Image" src="https://github.com/user-attachments/assets/e14b9efd-450d-4a4d-8511-731ab085a471" />
> 
> sglang:
> <img width="600" alt="Image" src="https://github.com/user-attachments/assets/6ce124d5-700b-4d52-be0d-f530b0960cc4" />

Deepseek-R1 is trained to output with CoT format by default and no need to feed an explicit template(e.g. think step by step). However, I am not sure the distilled model. Your SGLang output doesn't have CoT process, however, it has "/think" as the end of CoT, suspect there is something wrong, llama.cpp output is more reasoning.

**Comment by remixer-dec** [comment]
> no need to feed an explicit template(e.g. think step by step). 

Yes, I understand that there is no system prompt required.

I dug deeper into the issue and found the origin of the problem.
- vLLM (latest with latest gguf package) has the same issue with the GGUF model
- GPTQ-quantized model works in vLLM (only if you do not use `--quantization gptq`) and works perfectly in SGlang
- Using `--log-requests` parameter I compared the tokens from both models and they are different

<img width="1291" alt="Image" src="https://github.com/user-attachments/assets/9f1ae9ba-31cf-47e8-aa05-7c8c7d4cb8ba" />

The tokenizer, instead of treating `<｜User｜>` and other parts of the chat template as a single token, treats them as multiple tokens. `<`, `｜`, `User`, `｜`, `>`.

And BOS token is also missing.

<img width="663" alt="Image" src="https://github.com/user-attachments/assets/5bad7b65-0b06-4fed-9308-a211c5548bf6" />
