### ISSUE TITLE
ModuleNotFoundError: No module named 'zmq'

### ISSUE THREAD

**Issue by surak** [sgl-project/sglang#167]
Hi!

Should zmq be on your dependencies list?

```
2024-02-08 09:56:23 | ERROR | stderr | Traceback (most recent call last):
2024-02-08 09:56:23 | ERROR | stderr |   File "/p/haicluster/llama/FastChat/fastchat/serve/sglang_worker.py", line 269, in <module>
2024-02-08 09:56:23 | ERROR | stderr |     runtime = sgl.Runtime(
2024-02-08 09:56:23 | ERROR | stderr |               ^^^^^^^^^^^^
2024-02-08 09:56:23 | ERROR | stderr |   File "/p/haicluster/llama/FastChat/sc_venv_2024/venv/lib/python3.11/site-packages/sglang/api.py", line 37, in Runtime
2024-02-08 09:56:23 | ERROR | stderr |     from sglang.srt.server import Runtime
2024-02-08 09:56:23 | ERROR | stderr |   File "/p/haicluster/llama/FastChat/sc_venv_2024/venv/lib/python3.11/site-packages/sglang/srt/server.py", line 30, in <module>
2024-02-08 09:56:23 | ERROR | stderr |     from sglang.srt.managers.detokenizer_manager import start_detokenizer_process
2024-02-08 09:56:23 | ERROR | stderr |   File "/p/haicluster/llama/FastChat/sc_venv_2024/venv/lib/python3.11/site-packages/sglang/srt/managers/detokenizer_manager.py", line 4, in <module>
2024-02-08 09:56:23 | ERROR | stderr |     import zmq
2024-02-08 09:56:23 | ERROR | stderr | ModuleNotFoundError: No module named 'zmq'
srun: error: haicluster2: task 0: Exited with exit code 1
```

**Comment by surak** [comment]
Same for rpyc, interegular, numba, lark...

**Comment by hnyls2002** [comment]
@surak What is the installation command you used?
We have specified all the needed dependencies here 
https://github.com/sgl-project/sglang/blob/cba50273324e9770c587754a4abbea974a4124ba/python/pyproject.toml#L20-L26

And
```
pip install "sglang[all]"
```
can install all of the dependencies. If you want to install the editable version, you can use this
```
pip install -e ".[all]"
```
under the `python/` dir.
