### ISSUE TITLE
[Bug] deadlock or hang on Qwen2-7B models

### ISSUE THREAD

**Issue by zeng-zc** [sgl-project/sglang#1691]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

I come across several hangs or deadlocks when running sglang v0.3.0 recently. It both occurs on A100 and A800. I think the stability is still a serious problem for production environment deployment. I hope the core-team could pay more attentions to this problem. It's quite annoying when crash or hang occurs frequently.

### Reproduction

server side:
```
 python3 -m sglang.launch_server    --model-path Qwen/Qwen2-7B-Instruct \
      --host 0.0.0.0 --port 30000       --tp-size 4 
```
When I'ved tested it with about 1000 requests, it hangs. The server logging messages don't refresh again.
If I add ` --disable-cuda-graph --disable-flashinfer-sampling ` in the launching parameters, it still hangs but less frequently.

### Environment

`# python3 -m sglang.check_env`:

```
Python: 3.10.14 (main, Apr  6 2024, 18:45:05) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A100-SXM4-40GB
GPU 0,1,2,3 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 525.85.12
PyTorch: 2.4.0+cu121
flashinfer: 0.1.6+cu124torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.5
fastapi: 0.112.2
hf_transfer: 0.1.8
huggingface_hub: 0.24.6
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.9
openai: 1.43.0
anthropic: 0.34.1
NVIDIA Topology: 
	[4mGPU0	GPU1	GPU2	GPU3	NIC0	NIC1	CPU Affinity	NUMA Affinity[0m
GPU0	 X 	NV12	NV12	NV12	PXB	SYS	0-63,128-191	0
GPU1	NV12	 X 	NV12	NV12	NODE	SYS	0-63,128-191	0
GPU2	NV12	NV12	 X 	NV12	NODE	SYS	0-63,128-191	0
GPU3	NV12	NV12	NV12	 X 	SYS	NODE	64-127,192-255	1
NIC0	PXB	NODE	NODE	SYS	 X 	SYS		
NIC1	SYS	SYS	SYS	NODE	SYS	 X 		

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1


ulimit soft: 65536
```

**Comment by zhyncs** [comment]
@zeng-zc May you try the case with TP 1?

**Comment by zhyncs** [comment]
BTW Please use the latest version [0.3.3.post1](https://pypi.org/project/sglang/)

**Comment by zeng-zc** [comment]
> BTW Please use the latest version [0.3.3.post1](https://pypi.org/project/sglang/)

I've also tested the latest docker image `sglang:v0.3.3.post1-cu121-srt`,
It also hangs, this is the logs:
```
sglang  | INFO:     10.198.34.144:39868 - "POST /v1/completions HTTP/1.1" 200 OK
sglang  | INFO:     172.25.0.1:58068 - "GET /health HTTP/1.1" 200 OK
sglang  | [23:23:40] Abort request 4cbad29d64c044d89b4ad326112098eb
sglang  | Traceback (most recent call last):
sglang  |   File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
sglang  |     await fut
sglang  | asyncio.exceptions.CancelledError
sglang  | 
sglang  | During handling of the above exception, another exception occurred:
sglang  | 
sglang  | Traceback (most recent call last):
sglang  |   File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
sglang  |     return fut.result()
sglang  | asyncio.exceptions.CancelledError
sglang  | 
sglang  | The above exception was the direct cause of the following exception:
sglang  | 
sglang  | Traceback (most recent call last):
sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 447, in _wait_for_response
sglang  |     await asyncio.wait_for(state.event.wait(), timeout=4)
sglang  |   File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
sglang  |     raise exceptions.TimeoutError() from exc
sglang  | asyncio.exceptions.TimeoutError
sglang  | 
sglang  | During handling of the above exception, another exception occurred:
sglang  | 
sglang  | Traceback (most recent call last):
sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/server.py", line 116, in health_generate
sglang  |     async for _ in tokenizer_manager.generate_request(gri, request):
sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 157, in generate_request
sglang  |     async for response in self._handle_single_request(obj, request):
sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 326, in _handle_single_request
sglang  |     async for response in self._wait_for_response(state, obj, rid, request):
sglang  |   File "/sgl-workspace/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 452, in _wait_for_response
sglang  |     raise ValueError(f"Abort request {rid}")
sglang  | ValueError: Abort request 4cbad29d64c044d89b4ad326112098eb
```

**Comment by zeng-zc** [comment]
> @zeng-zc May you try the case with TP 1?

40G gpu memeory is not big enough to serve the 7B model. If it'd be the tp or nccl reason, then how to fix?

**Comment by merrymercy** [comment]
try `--disable-custom-all-reduce`?

**Comment by zeng-zc** [comment]
> try `--disable-custom-all-reduce`?

I've tried:
https://github.com/sgl-project/sglang/issues/1693#issuecomment-2418773828

**Comment by zeng-zc** [comment]
Does any one have any idea? For my benchmark, sglang's result is prettier than vllm, that is, higher throughput, lower latency and lower TTFT, but less stable for production env. If the stability issue were fixed, I prefer sglang.

**Comment by zeng-zc** [comment]
> try `--disable-custom-all-reduce`?

Here are some updated infomation.
I added  `--disable-custom-all-reduce` in the launch command, and did a stress testing. After about 15 hours' running, it crashed. The following is the logs. And the machine is A800 40G * 8, using tp=8.

```
[00:44:00 TP0] Prefill batch. #new-seq: 1, #new-token: 7, #cached-token: 1, cache hit rate: 89.83%, token usage: 0.25, #running-req: 171, #queue-req: 0
INFO:     10.119.60.77:39700 - "POST /v1/completions HTTP/1.1" 200 OK
[00:44:00 TP0] Decode batch. #running-req: 170, #token: 85928, token usage: 0.25, gen throughput (token/s): 1758.37, #queue-req: 0
[00:44:00 TP0] Prefill batch. #new-seq: 1, #new-token: 3353, #cached-token: 1241, cache hit rate: 89.83%, token usage: 0.25, #running-req: 170, #queue-req: 0
INFO:     10.119.60.77:39716 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39732 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39746 - "POST /v1/completions HTTP/1.1" 200 OK
[00:44:01 TP0] Prefill batch. #new-seq: 3, #new-token: 2665, #cached-token: 5686, cache hit rate: 89.83%, token usage: 0.26, #running-req: 171, #queue-req: 0
INFO:     10.119.60.77:39752 - "POST /v1/completions HTTP/1.1" 200 OK
[00:44:01 TP0] Prefill batch. #new-seq: 1, #new-token: 14, #cached-token: 3964, cache hit rate: 89.83%, token usage: 0.27, #running-req: 174, #queue-req: 0
INFO:     10.119.60.77:39754 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39770 - "POST /v1/completions HTTP/1.1" 200 OK
[00:44:01 TP0] Prefill batch. #new-seq: 2, #new-token: 112, #cached-token: 8370, cache hit rate: 89.83%, token usage: 0.28, #running-req: 175, #queue-req: 0
INFO:     10.119.60.77:39776 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39782 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39792 - "POST /v1/completions HTTP/1.1" 200 OK
[00:44:01 TP0] Prefill batch. #new-seq: 2, #new-token: 107, #cached-token: 3700, cache hit rate: 89.83%, token usage: 0.28, #running-req: 177, #queue-req: 0
[00:44:01 TP0] Prefill batch. #new-seq: 1, #new-token: 52, #cached-token: 1, cache hit rate: 89.83%, token usage: 0.28, #running-req: 179, #queue-req: 0
INFO:     10.119.60.77:39808 - "POST /v1/completions HTTP/1.1" 200 OK
[00:44:02 TP0] Prefill batch. #new-seq: 1, #new-token: 27, #cached-token: 0, cache hit rate: 89.83%, token usage: 0.27, #running-req: 177, #queue-req: 0
INFO:     10.119.60.77:39816 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39824 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39836 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39844 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39850 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39852 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39858 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39862 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39878 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39890 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39900 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39906 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39914 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39926 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39928 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39940 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39960 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39944 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39966 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39972 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39986 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:39990 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40004 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40016 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40022 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40030 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40042 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40058 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40068 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     10.119.60.77:40084 - "POST /v1/completions HTTP/1.1" 200 OK
[rank2]:[E1019 01:04:03.356317268 ProcessGroupNCCL.cpp:1375] [PG 3 Rank 2] First PG on this rank that detected no heartbeat of its watchdog.
[rank2]:[E1019 01:04:03.356565968 ProcessGroupNCCL.cpp:1413] [PG 3 Rank 2] Heartbeat monitor timed out! Process will be terminated after dumping debug info. workMetaList_.size()=121
[rank3]:[E1019 01:04:03.356658772 ProcessGroupNCCL.cpp:1375] [PG 3 Rank 3] First PG on this rank that detected no heartbeat of its watchdog.
[rank4]:[E1019 01:04:03.356674412 ProcessGroupNCCL.cpp:1375] [PG 3 Rank 4] First PG on this rank that detected no heartbeat of its watchdog.
[rank1]:[E1019 01:04:03.356759979 ProcessGroupNCCL.cpp:1375] [PG 3 Rank 1] First PG on this rank that detected no heartbeat of its watchdog.
[rank0]:[E1019 01:04:03.356837591 ProcessGroupNCCL.cpp:1375] [PG 3 Rank 0] First PG on this rank that detected no heartbeat of its watchdog.
[rank3]:[E1019 01:04:03.356871814 ProcessGroupNCCL.cpp:1413] [PG 3 Rank 3] Heartbeat monitor timed out! Process will be terminated after dumping debug info. workMetaList_.size()=121
[rank4]:[E1019 01:04:03.356908512 ProcessGroupNCCL.cpp:1413] [PG 3 Rank 4] Heartbeat monitor timed out! Process will be terminated after dumping debug info. workMetaList_.size()=121
[rank0]:[E1019 01:04:03.356947152 ProcessGroupNCCL.cpp:1413] [PG 3 Rank 0] Heartbeat monitor timed out! Process will be terminated after dumping debug info. workMetaList_.size()=121
[rank1]:[E1019 01:04:03.357037506 ProcessGroupNCCL.cpp:1413] [PG 3 Rank 1] Heartbeat monitor timed out! Process will be terminated after dumping debug info. workMetaList_.size()=121
[rank7]:[E1019 01:04:03.357615073 ProcessGroupNCCL.cpp:1375] [PG 3 Rank 7] First PG on this rank that detected no heartbeat of its watchdog.
[rank6]:[E1019 01:04:03.357809163 ProcessGroupNCCL.cpp:1375] [PG 3 Rank 6] First PG on this rank that detected no heartbeat of its watchdog.
[rank6]:[E1019 01:04:03.358023054 ProcessGroupNCCL.cpp:1413] [PG 3 Rank 6] Heartbeat monitor timed out! Process will be terminated after dumping debug info. workMetaList_.size()=121
[rank7]:[E1019 01:04:03.358125866 ProcessGroupNCCL.cpp:1413] [PG 3 Rank 7] Heartbeat monitor timed out! Process will be terminated after dumping debug info. workMetaList_.size()=121
[rank2]:[F1019 01:14:03.356851194 ProcessGroupNCCL.cpp:1224] [PG 3 Rank 2] [PG 3 Rank 2] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. workMetaList_.size() = 121
[rank4]:[F1019 01:14:03.357171903 ProcessGroupNCCL.cpp:1224] [PG 3 Rank 4] [PG 3 Rank 4] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. workMetaList_.size() = 121
[rank3]:[F1019 01:14:03.357361842 ProcessGroupNCCL.cpp:1224] [PG 3 Rank 3] [PG 3 Rank 3] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. workMetaList_.size() = 121
[rank0]:[F1019 01:14:03.357385664 ProcessGroupNCCL.cpp:1224] [PG 3 Rank 0] [PG 3 Rank 0] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. workMetaList_.size() = 121
[rank1]:[F1019 01:14:03.357494301 ProcessGroupNCCL.cpp:1224] [PG 3 Rank 1] [PG 3 Rank 1] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. workMetaList_.size() = 121
[rank6]:[F1019 01:14:03.358291284 ProcessGroupNCCL.cpp:1224] [PG 3 Rank 6] [PG 3 Rank 6] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. workMetaList_.size() = 121
[rank7]:[F1019 01:14:03.358443683 ProcessGroupNCCL.cpp:1224] [PG 3 Rank 7] [PG 3 Rank 7] ProcessGroupNCCL's watchdog got stuck for 600 seconds without making progress in monitoring enqueued collectives. This typically indicates a NCCL/CUDA API hang blocking the watchdog, and could be triggered by another thread holding the GIL inside a CUDA api, or other deadlock-prone behaviors.If you suspect the watchdog is not actually stuck and a longer timeout would help, you can either increase the timeout (TORCH_NCCL_HEARTBEAT_TIMEOUT_SEC) to a larger value or disable the heartbeat monitor (TORCH_NCCL_ENABLE_MONITORING=0).If either of aforementioned helps, feel free to file an issue to PyTorch about the short timeout or false positive abort; otherwise, please attempt to debug the hang. workMetaList_.size() = 121
```

After this message, the server's worker process exited, and the overload of 8 gpus is nearly zero.

**Comment by merrymercy** [comment]
@zeng-zc I am sorry to hear that. Our sglang servers can run for weeks without crash, so it is likely some issues during recent refactor or the environment setups. I sent a message to you on slack. We can debug more interactively there.

**Comment by zeng-zc** [comment]
> @zeng-zc I am sorry to hear that. Our sglang servers can run for weeks without crash, so it is likely some issues during recent refactor or the environment setups. I sent a message to you on slack. We can debug more interactively there.

Oh, sorry, I've never managed to login into slack as it's banned for China IP. 
I find another crash on  A100-SXM4-80GB * 8 for `tp=4, dp=2` when serving a 72B model today.

server side:
```
python3 -m sglang.launch_server --model-path Qwen/Qwen2-72B-Instruct \
			--port 8000 --host 0.0.0.0 --tp-size 4 --dp-size 2 --show-time-cost --disable-custom-all-reduce --log-level=debug
```

client side:
Just run the `python -m sglang.bench_serving --multi` script on a SharedGPT-formatted dataset.  The dataset contains about 1000 records, covering Chinese texts and English texts. I run the script repeatly in a for loop. 

crash logs:
```
2024-10-19 23:04:02:  [08:04:01 DP0 TP0] Decode batch. #running-req: 72, #token: 12781, token usage: 0.03, gen throughput (token/s): 1377.67, #queue-req: 0
2024-10-19 23:04:03:  [08:04:02 DP1 TP0] Decode batch. #running-req: 67, #token: 12391, token usage: 0.03, gen throughput (token/s): 1509.03, #queue-req: 0
2024-10-19 23:04:04:  [08:04:03 DP0 TP0] Decode batch. #running-req: 57, #token: 10983, token usage: 0.03, gen throughput (token/s): 1457.94, #queue-req: 0
2024-10-19 23:04:05:  [08:04:04 DP1 TP0] Decode batch. #running-req: 52, #token: 10482, token usage: 0.03, gen throughput (token/s): 1387.61, #queue-req: 0
2024-10-19 23:04:05:  [08:04:04] Traceback (most recent call last):
2024-10-19 23:04:05:    File "/usr/local/lib/python3.10/dist-packages/zmq/sugar/attrsettr.py", line 56, in __getattr__
2024-10-19 23:04:05:      return self._get_attr_opt(upper_key, opt)
2024-10-19 23:04:05:    File "/usr/local/lib/python3.10/dist-packages/zmq/sugar/attrsettr.py", line 68, in _get_attr_opt
2024-10-19 23:04:05:      return self.get(opt)
2024-10-19 23:04:05:    File "_zmq.py", line 864, in zmq.backend.cython._zmq.Socket.get
2024-10-19 23:04:05:    File "_zmq.py", line 1362, in zmq.backend.cython._zmq._getsockopt
2024-10-19 23:04:05:    File "_zmq.py", line 179, in zmq.backend.cython._zmq._check_rc
2024-10-19 23:04:05:  zmq.error.ZMQError: Invalid argument
2024-10-19 23:04:05:  
2024-10-19 23:04:05:  During handling of the above exception, another exception occurred:
2024-10-19 23:04:05:  
2024-10-19 23:04:05:  Traceback (most recent call last):
2024-10-19 23:04:05:    File "/sgl-workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 173, in run_data_parallel_controller_process
2024-10-19 23:04:05:      controller.event_loop()
2024-10-19 23:04:05:    File "/sgl-workspace/sglang/python/sglang/srt/managers/data_parallel_controller.py", line 159, in event_loop
2024-10-19 23:04:05:      worker.queue.put(recv_req)
2024-10-19 23:04:05:    File "/usr/local/lib/python3.10/dist-packages/zmq/sugar/attrsettr.py", line 62, in __getattr__
2024-10-19 23:04:05:      raise AttributeError(f"{key} attribute is write-only")
2024-10-19 23:04:05:  AttributeError: queue attribute is write-only
2024-10-19 23:04:05:  
2024-10-19 23:04:05:  bash: line 5:    13 Killed                  python3 -m sglang.launch_server --model-path Qwen/Qwen2-72B-Instruct
			--port 8000 --host 0.0.0.0 --tp-size 4 --dp-size 2 --show-time-cost --disable-custom-all-reduce --log-level=debug
```

env:
```
# python3 -m sglang.check_env
Python: 3.10.15 (main, Sep  7 2024, 18:35:33) [GCC 9.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
GPU 0,1,2,3,4,5,6,7 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 550.90.07
PyTorch: 2.4.0+cu121
sglang: 0.3.3.post1
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.45.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.10
fastapi: 0.115.0
hf_transfer: 0.1.8
huggingface_hub: 0.25.2
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.2
uvicorn: 0.31.1
uvloop: 0.20.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.12
openai: 1.51.2
tiktoken: 0.8.0
anthropic: Module Not Found
litellm: Module Not Found
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1    NIC2    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV12    PXB     SYS     SYS     0-31,64-95      0               N/A
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV12    PXB     SYS     SYS     0-31,64-95      0               N/A
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV12    NODE    SYS     SYS     0-31,64-95      0               N/A
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV12    NODE    SYS     SYS     0-31,64-95      0               N/A
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV12    SYS     PXB     NODE    32-63,96-127    1               N/A
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV12    SYS     PXB     NODE    32-63,96-127    1               N/A
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV12    SYS     NODE    NODE    32-63,96-127    1               N/A
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X      SYS     NODE    NODE    32-63,96-127    1               N/A
NIC0    PXB     PXB     NODE    NODE    SYS     SYS     SYS     SYS      X      SYS     SYS
NIC1    SYS     SYS     SYS     SYS     PXB     PXB     NODE    NODE    SYS      X      NODE
NIC2    SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    SYS     NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_3
  NIC2: mlx5_bond_0


ulimit soft: 1048576
```

**Comment by zeng-zc** [comment]
> @zeng-zc I am sorry to hear that. Our sglang servers can run for weeks without crash, so it is likely some issues during recent refactor or the environment setups. I sent a message to you on slack. We can debug more interactively there.

I think it has nothing to do with the recent commits, as I encountered this same problem on sglang v0.2.13-cu124 docker image before. Maybe there is a hidden bug, I've read the related code and try to analyse the reason, but with no progress.

**Comment by 1994** [comment]
I have the same issue with Qwen2.5-7B-GPTQ-INT4 on A10.

**Comment by merrymercy** [comment]
@zeng-zc Your recent crash `AttributeError: queue attribute is write-only` has been fixed by #1767

**Comment by zeng-zc** [comment]
> @zeng-zc Your recent crash `AttributeError: queue attribute is write-only` has been fixed by #1767

Ok, thank you. I'll validate it.

**Comment by zeng-zc** [comment]
> @zeng-zc Your recent crash `AttributeError: queue attribute is write-only` has been fixed by #1767

@merrymercy Hi, I've ran the latest v0.3.4.post1-cu121 image for nearly 5 continuous days, there's not a single crash or hang. 
I've also tested the `dp=2` parameter, it's nearly runned for 3 days, definitely ok.
There's a good chance that this issue has already been resolved?

**Comment by zeng-zc** [comment]
I'm sorry to report that I've found several crashes again on latest v0.3.4.post1-cu121 image...

server side command:
```
python3 -m sglang.launch_server --model-path  Qwen2/Qwen2-72B-Instruct \
        --port 8000 --host 0.0.0.0 --tp-size 8 \
        --show-time-cost --mem-fraction-static 0.82 \
        --log-level=debug #--log-level-http=debug
```

On the client side, I just do a stress testing with `python3 -m sglang.bench_serving --multi xxxxx` command. By the way,  I've commented the following lines in https://github.com/sgl-project/sglang/blob/v0.3.4.post1/python/sglang/bench_serving.py#L464:

```
        if prompt_len > 1024 or (
            prompt_len + output_len > 2048 and fixed_output_len is None
        ):
            # Prune too long sequences.
            continue
```
I want to test on long context. My dataset contains about 500 records with sharegpt format, the content is mainly Chinese text. The average input token length is about 7000 tokens, and I restrict the output lengh to 256.

I attach the logging file in this post, the file is very long, about 10000 lines. You can search `Traceback` for error messages. And I found there isn't effective logs around the auto-restart time (my deploy environment has a auto restart when detecting `curl localhost:8000/health_generate` failed), it's very strange. When you see such a logging, then there is a restart:
```
{"Timestamp":"2024-10-29T14:00:44.212150947Z","Body":"[2024-10-29 22:00:43] server_args=ServerArgs(model_path='Qwen2/Qwen2-72B-Instruct', tokenizer_path='Qwen2/Qwen2-72B-Instruct', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=False, dtype='auto', kv_cache_dtype='auto', quantization=None, context_length=None, device='cuda', served_model_name='Qwen2/Qwen2-72B-Instruct', chat_template=None, is_embedding=False, host='0.0.0.0', port=8000, mem_fraction_"}
```

My environment is the same as this post: https://github.com/sgl-project/sglang/issues/1691#issuecomment-2424380286

The logging file: 
 
[exported_log.jsonl.TGZ](https://github.com/user-attachments/files/17565122/exported_log.jsonl.TGZ)

@merrymercy

**Comment by merrymercy** [comment]
@zeng-zc Let us create new issues for new problems. Since the original problem has been fixed, let me close this for now.
