### ISSUE TITLE
Detected errors during sampling! NaN in the probability error in Qwen2.5-7b-instruct with two a30

### ISSUE THREAD

**Issue by zzh-www** [sgl-project/sglang#1764]
=============error message==================
**python -m sglang.bench_latency --model-path models/Qwen/Qwen2.5-7B-Instruct --batch 1 --input-len 512 --output-len 1 --trust-remote-code --disable-radix-cache --mem-fraction-static 0.7 --enable-torch-compile --tp 2**
[21:43:41 TP0] Init torch distributed begin.
[21:43:41 TP1] Init torch distributed begin.
[21:43:50 TP0] Load weight begin. avail mem=21.62 GB
[21:43:50 TP1] Load weight begin. avail mem=21.62 GB
[21:43:51 TP0] lm_eval is not installed, GPTQ may not be usable
[21:43:51 TP1] lm_eval is not installed, GPTQ may not be usable
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:00<00:00,  1.76it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.52it/s]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:01<00:00,  1.55it/s]

[21:43:53 TP0] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=14.42 GB
[21:43:53 TP1] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=14.42 GB
[21:43:53 TP1] Memory pool end. avail mem=5.93 GB
[21:43:53 TP0] Memory pool end. avail mem=5.93 GB
[21:43:54 TP1] Capture cuda graph begin. This can take up to several minutes.
[21:43:54 TP0] Capture cuda graph begin. This can take up to several minutes.
INFO 10-23 21:48:26 custom_all_reduce.py:223] Registering 912 cuda graph addresses
INFO 10-23 21:48:26 custom_all_reduce.py:223] Registering 912 cuda graph addresses
max_total_num_tokens=296895
Warmup ...
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Prefill. latency: 0.91232 s, throughput:    561.21 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01266 s, throughput:     78.98 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01184 s, throughput:     84.44 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01149 s, throughput:     87.05 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01157 s, throughput:     86.41 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  latency: 0.01135 s, throughput:     88.11 token/s
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
Decode.  median latency: 0.01149 s, median throughput:     87.05 token/s
Total. latency:  0.994 s, throughput:    523.16 token/s
Benchmark ...
[21:48:28 TP1] Detected errors during sampling! NaN in the probability.
[21:48:28 TP0] Detected errors during sampling! NaN in the probability.
Prefill. latency: 0.05028 s, throughput:  10183.34 token/s
Total. latency:  0.050 s, throughput:  10203.23 token/s
Exception ignored in: <function CustomAllreduce.__del__ at 0x7ffbbe2fca60>
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 274, in __del__
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 270, in close
AttributeError: 'NoneType' object has no attribute 'dispose'
Exception ignored in: <function ShmRingBuffer.__del__ at 0x7ffbbe28bc10>
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/shm_broadcast.py", line 132, in __del__
  File "/root/miniconda3/envs/sgl/lib/python3.9/multiprocessing/shared_memory.py", line 240, in unlink
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function CustomAllreduce.__del__ at 0x7f52b1919b80>
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 274, in __del__
  File "/root/miniconda3/envs/sgl/lib/python3.9/site-packages/vllm/distributed/device_communicators/custom_all_reduce.py", line 270, in close
AttributeError: 'NoneType' object has no attribute 'dispose'
[rank0]:[W1023 21:48:30.143561942 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
[rank1]:[W1023 21:48:30.202617070 CudaIPCTypes.cpp:16] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors

============Environment=================
**python3 -m sglang.check_env**
Python: 3.9.20 (main, Oct  3 2024, 07:27:41) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA A30
GPU 0,1 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda-12.1
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 470.129.06
PyTorch: 2.4.0+cu121
sglang: 0.3.3.post1
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.45.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.10
fastapi: 0.115.2
hf_transfer: 0.1.8
huggingface_hub: 0.25.2
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.2
uvicorn: 0.31.1
uvloop: 0.21.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.12
openai: 1.51.2
tiktoken: 0.8.0
anthropic: 0.36.0
NVIDIA Topology: 
        GPU0    GPU1    mlx5_0  mlx5_1  mlx5_2  mlx5_3  CPU Affinity    NUMA Affinity
GPU0     X      NODE    SYS     SYS     SYS     SYS     18-31,80,82-95  1
GPU1    NODE     X      SYS     SYS     SYS     SYS     18-31,80,82-95  1
mlx5_0  SYS     SYS      X      PIX     SYS     SYS
mlx5_1  SYS     SYS     PIX      X      SYS     SYS
mlx5_2  SYS     SYS     SYS     SYS      X      PIX
mlx5_3  SYS     SYS     SYS     SYS     PIX      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024768

_Originally posted by @zzh-www in https://github.com/sgl-project/sglang/issues/1571#issuecomment-2432280236_

**Comment by merrymercy** [comment]
This benchmark script uses dummy token ids as inputs, so it can cause NaN for some models.
You can safely ignore this, or skip it by adding `--disable-nan-detection`, or feed correct data https://github.com/sgl-project/sglang/blob/87a7cfa080cec3f123618c1429b5f998bf5d99cb/python/sglang/bench_latency.py#L201.

To verify the correctness, you can use
```
python -m sglang.bench_latency --model-path Qwen/Qwen2.5-7B-Instruct --correct --enable-torch-compile
```
which gives the correct result
```
========== Prompt 0 ==========
The capital of France is Paris. Which of the following statements is true?
A. Paris is the capital
...
```

**Comment by merrymercy** [comment]
This benchmark script uses dummy token ids as inputs, so it can cause NaN for some models.
You can safely ignore this, or skip it by adding `--disable-nan-detection`, or feed correct data https://github.com/sgl-project/sglang/blob/87a7cfa080cec3f123618c1429b5f998bf5d99cb/python/sglang/bench_latency.py#L201.

To verify the correctness, you can use
```
python -m sglang.bench_latency --model-path Qwen/Qwen2.5-7B-Instruct --correct --enable-torch-compile
```
which gives the correct results
```
========== Prompt 0 ==========
The capital of France is Paris. Which of the following statements is true?
A. Paris is the capital
...
```

Other errors happened during the processes exits, such as `AttributeError: 'NoneType' object has no attribute 'dispose'`, can also be ignored safely.

**Comment by hahmad2008** [comment]
@merrymercy I have this with serving a model `google/gemma-2-27b-it` when launch server

`[13:40:27 TP1] Detected errors during sampling! NaN in the probability.
`

**Comment by rj-linqingxu** [comment]
+1 tp-size>1
python3 -m sglang.launch_server --model-path  /root/.xinference/cache/qwen2_5-instruct-gptq-7b-Int8/ --port 30000 --mem-fraction-static  0.8 --kv-cache-dtype int8 --attention-backend triton --sampling-backend pytorch --tp-size 2 --enable-torch-compile
[2024-11-08 05:20:19 TP1] Init torch distributed begin.
[2024-11-08 05:20:20 TP0] Init torch distributed begin.
[2024-11-08 05:20:23 TP0] Load weight begin. avail mem=22.74 GB
[2024-11-08 05:20:23 TP1] Load weight begin. avail mem=23.47 GB
[2024-11-08 05:20:23 TP0] FlashInfer is not available on Non-NV platforms. Fallback to other kernel libraries.
[2024-11-08 05:20:23 TP1] FlashInfer is not available on Non-NV platforms. Fallback to other kernel libraries.
[2024-11-08 05:20:23 TP0] FlashInfer is not available on Non-NV platforms. Fallback to other kernel libraries.
[2024-11-08 05:20:23 TP1] FlashInfer is not available on Non-NV platforms. Fallback to other kernel libraries.
Loading safetensors checkpoint shards:   0% Completed | 0/3 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  33% Completed | 1/3 [00:02<00:04,  2.09s/it]
[2024-11-08 05:20:30 TP1] Load weight end. type=Qwen2ForCausalLM, dtype=torch.float16, avail mem=19.09 GB
Loading safetensors checkpoint shards:  67% Completed | 2/3 [00:07<00:04,  4.23s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:08<00:00,  2.68s/it]
Loading safetensors checkpoint shards: 100% Completed | 3/3 [00:08<00:00,  2.89s/it]

[2024-11-08 05:20:33 TP0] Load weight end. type=Qwen2ForCausalLM, dtype=torch.float16, avail mem=18.36 GB
[2024-11-08 05:20:33 TP1] Memory pool end. avail mem=4.70 GB
[2024-11-08 05:20:33 TP0] Memory pool end. avail mem=3.97 GB
[2024-11-08 05:20:33 TP0] Capture cuda graph begin. This can take up to several minutes.
[2024-11-08 05:20:33 TP1] Capture cuda graph begin. This can take up to several minutes.
[2024-11-08 05:21:26 TP0] max_total_num_tokens=516242, max_prefill_tokens=16384, max_running_requests=4097, context_len=32768
[2024-11-08 05:21:26 TP1] max_total_num_tokens=516242, max_prefill_tokens=16384, max_running_requests=4097, context_len=32768
[2024-11-08 05:21:27] INFO:     Started server process [123523]
[2024-11-08 05:21:27] INFO:     Waiting for application startup.
[2024-11-08 05:21:27] INFO:     Application startup complete.
[2024-11-08 05:21:27] INFO:     Uvicorn running on http://127.0.0.1:10000 (Press CTRL+C to quit)
[2024-11-08 05:21:28] INFO:     127.0.0.1:43560 - "GET /get_model_info HTTP/1.1" 200 OK
[2024-11-08 05:21:28 TP0] Prefill batch. #new-seq: 1, #new-token: 6, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
[2024-11-08 05:21:32 TP1] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP0] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP1] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP0] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP0] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP1] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP1] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP0] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP1] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP0] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP1] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP0] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP0] Detected errors during sampling! NaN in the logits.
[2024-11-08 05:21:32 TP1] Detected errors during sampling! NaN in the logits.
