### ISSUE TITLE
[Bug] AssertionError: assert self.being_chunked_req is None, related to `chunked_prefill_size` and input_len

### ISSUE THREAD

**Issue by HaiShaw** [sgl-project/sglang#2255]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

```
root@c182a613717a:/dockerx/sglang#
root@c182a613717a:/dockerx/sglang# python -m sglang.bench_offline_throughput --model-path amd/Meta-Llama-3.1-8B-Instruct-FP8-KV --dataset-name random --num-prompts 200 --random-input-len 2064 --random-output-len 64 --quant fp8 --tensor-parallel-size 1 --random-range-ratio 1 --chunked-prefill-size 2048 --disable-radix-cache
WARNING 11-29 10:27:45 rocm.py:17] `fork` method is not supported by ROCm. VLLM_WORKER_MULTIPROC_METHOD is overridden to `spawn` instead.
[2024-11-29 10:27:51] server_args=ServerArgs(model_path='amd/Meta-Llama-3.1-8B-Instruct-FP8-KV', tokenizer_path='amd/Meta-Llama-3.1-8B-Instruct-FP8-KV', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=False, dtype='auto', kv_cache_dtype='auto', quantization='fp8', context_length=None, device='cuda', served_model_name='amd/Meta-Llama-3.1-8B-Instruct-FP8-KV', chat_template=None, is_embedding=False, host='127.0.0.1', port=30000, mem_fraction_static=0.88, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=2048, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, cpu_offload_gb=0, tp_size=1, stream_interval=1, random_seed=968655859, constrained_json_whitespace_pattern=None, watchdog_timeout=300, download_dir=None, base_gpu_id=0, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_pth='SGLang_storage', enable_cache_report=False, dp_size=1, load_balance_method='round_robin', dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, lora_paths=None, max_loras_per_batch=8, attention_backend='triton', sampling_backend='pytorch', grammar_backend='outlines', disable_radix_cache=True, disable_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=160, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, num_continuous_decode_steps=1, delete_ckpt_after_loading=False)
[2024-11-29 10:28:00 TP0] Init torch distributed begin.
[2024-11-29 10:28:00 TP0] Load weight begin. avail mem=191.08 GB
[2024-11-29 10:28:00 TP0] FlashInfer is not available on Non-NV platforms. Fallback to other kernel libraries.
[2024-11-29 10:28:00 TP0] FlashInfer is not available on Non-NV platforms. Fallback to other kernel libraries.
[2024-11-29 10:28:01 TP0] Skipping import of cpp extensions
[2024-11-29 10:28:01 TP0] lm_eval is not installed, GPTQ may not be usable
WARNING 11-29 10:28:01 fp8.py:48] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
INFO 11-29 10:28:01 weight_utils.py:242] Using model weights format ['*.safetensors']
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:01<00:01,  1.51s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:03<00:00,  1.82s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:03<00:00,  1.77s/it]

[2024-11-29 10:28:05 TP0] Load weight end. type=LlamaForCausalLM, dtype=torch.bfloat16, avail mem=181.00 GB
[2024-11-29 10:28:06 TP0] Memory pool end. avail mem=20.88 GB
[2024-11-29 10:28:06 TP0] Capture cuda graph begin. This can take up to several minutes.
[2024-11-29 10:28:18 TP0] max_total_num_tokens=1294946, max_prefill_tokens=16384, max_running_requests=4097, context_len=131072
#Input tokens: 412800
#Output tokens: 12800
#Input tokens: 3516
#Output tokens: 228
[2024-11-29 10:28:25] 
Warmup...
[2024-11-29 10:28:25 TP0] Prefill batch. #new-seq: 1, #new-token: 242, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
[2024-11-29 10:28:25 TP0] Prefill batch. #new-seq: 10, #new-token: 2048, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 1, #queue-req: 5
[2024-11-29 10:28:25 TP0] Prefill batch. #new-seq: 6, #new-token: 1242, #cached-token: 84, cache hit rate: 0.00%, token usage: 0.00, #running-req: 10, #queue-req: 1
[2024-11-29 10:28:25] 
Benchmark...
[2024-11-29 10:28:25 TP0] Prefill batch. #new-seq: 1, #new-token: 2048, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
[2024-11-29 10:28:25 TP0] Prefill batch. #new-seq: 1, #new-token: 17, #cached-token: 2048, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 1
[2024-11-29 10:28:25 TP0] Prefill batch. #new-seq: 1, #new-token: 2048, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 1, #queue-req: 24
[2024-11-29 10:28:25 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 2048, cache hit rate: 0.00%, token usage: 0.00, #running-req: 1, #queue-req: 30
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 2031, cache hit rate: 0.00%, token usage: 0.00, #running-req: 2, #queue-req: 48
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 2014, cache hit rate: 0.00%, token usage: 0.01, #running-req: 3, #queue-req: 70
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1997, cache hit rate: 0.00%, token usage: 0.01, #running-req: 4, #queue-req: 85
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1980, cache hit rate: 0.00%, token usage: 0.01, #running-req: 5, #queue-req: 112
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1963, cache hit rate: 0.00%, token usage: 0.01, #running-req: 6, #queue-req: 128
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1946, cache hit rate: 0.00%, token usage: 0.01, #running-req: 7, #queue-req: 155
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1929, cache hit rate: 0.00%, token usage: 0.01, #running-req: 8, #queue-req: 170
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1912, cache hit rate: 0.00%, token usage: 0.02, #running-req: 9, #queue-req: 190
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1895, cache hit rate: 0.00%, token usage: 0.02, #running-req: 10, #queue-req: 189
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1880, cache hit rate: 0.00%, token usage: 0.02, #running-req: 11, #queue-req: 188
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1863, cache hit rate: 0.00%, token usage: 0.02, #running-req: 12, #queue-req: 187
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1846, cache hit rate: 0.00%, token usage: 0.02, #running-req: 13, #queue-req: 186
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1838, cache hit rate: 0.00%, token usage: 0.02, #running-req: 14, #queue-req: 185
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1821, cache hit rate: 0.00%, token usage: 0.03, #running-req: 15, #queue-req: 184
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1804, cache hit rate: 0.00%, token usage: 0.03, #running-req: 16, #queue-req: 183
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1787, cache hit rate: 0.00%, token usage: 0.03, #running-req: 17, #queue-req: 182
[2024-11-29 10:28:26 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1770, cache hit rate: 0.00%, token usage: 0.03, #running-req: 18, #queue-req: 181
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1753, cache hit rate: 0.00%, token usage: 0.03, #running-req: 19, #queue-req: 180
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1736, cache hit rate: 0.00%, token usage: 0.03, #running-req: 20, #queue-req: 179
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1719, cache hit rate: 0.00%, token usage: 0.03, #running-req: 21, #queue-req: 178
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1702, cache hit rate: 0.00%, token usage: 0.04, #running-req: 22, #queue-req: 177
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1685, cache hit rate: 0.00%, token usage: 0.04, #running-req: 23, #queue-req: 176
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1668, cache hit rate: 0.00%, token usage: 0.04, #running-req: 24, #queue-req: 175
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1651, cache hit rate: 0.00%, token usage: 0.04, #running-req: 25, #queue-req: 174
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1634, cache hit rate: 0.00%, token usage: 0.04, #running-req: 26, #queue-req: 173
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1617, cache hit rate: 0.00%, token usage: 0.04, #running-req: 27, #queue-req: 172
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1600, cache hit rate: 0.00%, token usage: 0.05, #running-req: 28, #queue-req: 171
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1583, cache hit rate: 0.00%, token usage: 0.05, #running-req: 29, #queue-req: 170
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1569, cache hit rate: 0.00%, token usage: 0.05, #running-req: 30, #queue-req: 169
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1552, cache hit rate: 0.00%, token usage: 0.05, #running-req: 31, #queue-req: 168
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1535, cache hit rate: 0.00%, token usage: 0.05, #running-req: 32, #queue-req: 167
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1518, cache hit rate: 0.00%, token usage: 0.05, #running-req: 33, #queue-req: 166
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1501, cache hit rate: 0.00%, token usage: 0.06, #running-req: 34, #queue-req: 165
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1484, cache hit rate: 0.00%, token usage: 0.06, #running-req: 35, #queue-req: 164
[2024-11-29 10:28:27 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1467, cache hit rate: 0.00%, token usage: 0.06, #running-req: 36, #queue-req: 163
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1450, cache hit rate: 0.00%, token usage: 0.06, #running-req: 37, #queue-req: 162
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1433, cache hit rate: 0.00%, token usage: 0.06, #running-req: 38, #queue-req: 161
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1416, cache hit rate: 0.00%, token usage: 0.06, #running-req: 39, #queue-req: 160
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1399, cache hit rate: 0.00%, token usage: 0.06, #running-req: 40, #queue-req: 159
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1382, cache hit rate: 0.00%, token usage: 0.07, #running-req: 41, #queue-req: 158
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1365, cache hit rate: 0.00%, token usage: 0.07, #running-req: 42, #queue-req: 157
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1348, cache hit rate: 0.00%, token usage: 0.07, #running-req: 43, #queue-req: 156
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1331, cache hit rate: 0.00%, token usage: 0.07, #running-req: 44, #queue-req: 155
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1296, cache hit rate: 0.00%, token usage: 0.07, #running-req: 45, #queue-req: 154
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1279, cache hit rate: 0.00%, token usage: 0.07, #running-req: 46, #queue-req: 153
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1262, cache hit rate: 0.00%, token usage: 0.08, #running-req: 47, #queue-req: 152
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1245, cache hit rate: 0.00%, token usage: 0.08, #running-req: 48, #queue-req: 151
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1228, cache hit rate: 0.00%, token usage: 0.08, #running-req: 49, #queue-req: 150
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1211, cache hit rate: 0.00%, token usage: 0.08, #running-req: 50, #queue-req: 149
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1194, cache hit rate: 0.00%, token usage: 0.08, #running-req: 51, #queue-req: 148
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1177, cache hit rate: 0.00%, token usage: 0.08, #running-req: 52, #queue-req: 147
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1160, cache hit rate: 0.00%, token usage: 0.09, #running-req: 53, #queue-req: 146
[2024-11-29 10:28:28 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1143, cache hit rate: 0.00%, token usage: 0.09, #running-req: 54, #queue-req: 145
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1126, cache hit rate: 0.00%, token usage: 0.09, #running-req: 55, #queue-req: 144
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1109, cache hit rate: 0.00%, token usage: 0.09, #running-req: 56, #queue-req: 143
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1092, cache hit rate: 0.00%, token usage: 0.09, #running-req: 57, #queue-req: 142
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1075, cache hit rate: 0.00%, token usage: 0.09, #running-req: 58, #queue-req: 141
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1058, cache hit rate: 0.00%, token usage: 0.09, #running-req: 59, #queue-req: 140
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1041, cache hit rate: 0.00%, token usage: 0.10, #running-req: 60, #queue-req: 139
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1024, cache hit rate: 0.00%, token usage: 0.10, #running-req: 61, #queue-req: 138
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 1007, cache hit rate: 0.00%, token usage: 0.10, #running-req: 62, #queue-req: 137
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 990, cache hit rate: 0.00%, token usage: 0.10, #running-req: 63, #queue-req: 136
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 973, cache hit rate: 0.00%, token usage: 0.10, #running-req: 64, #queue-req: 135
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 956, cache hit rate: 0.00%, token usage: 0.10, #running-req: 65, #queue-req: 134
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 939, cache hit rate: 0.00%, token usage: 0.11, #running-req: 66, #queue-req: 133
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 922, cache hit rate: 0.00%, token usage: 0.11, #running-req: 67, #queue-req: 132
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 905, cache hit rate: 0.00%, token usage: 0.11, #running-req: 68, #queue-req: 131
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 888, cache hit rate: 0.00%, token usage: 0.11, #running-req: 69, #queue-req: 130
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 871, cache hit rate: 0.00%, token usage: 0.11, #running-req: 70, #queue-req: 129
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 854, cache hit rate: 0.00%, token usage: 0.11, #running-req: 71, #queue-req: 128
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 837, cache hit rate: 0.00%, token usage: 0.12, #running-req: 72, #queue-req: 127
[2024-11-29 10:28:29 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 820, cache hit rate: 0.00%, token usage: 0.12, #running-req: 73, #queue-req: 126
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 803, cache hit rate: 0.00%, token usage: 0.12, #running-req: 74, #queue-req: 125
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 786, cache hit rate: 0.00%, token usage: 0.12, #running-req: 75, #queue-req: 124
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 769, cache hit rate: 0.00%, token usage: 0.12, #running-req: 76, #queue-req: 123
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 752, cache hit rate: 0.00%, token usage: 0.12, #running-req: 77, #queue-req: 122
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 735, cache hit rate: 0.00%, token usage: 0.12, #running-req: 78, #queue-req: 121
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 718, cache hit rate: 0.00%, token usage: 0.13, #running-req: 79, #queue-req: 120
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 701, cache hit rate: 0.00%, token usage: 0.13, #running-req: 80, #queue-req: 119
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 684, cache hit rate: 0.00%, token usage: 0.13, #running-req: 81, #queue-req: 118
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 667, cache hit rate: 0.00%, token usage: 0.13, #running-req: 82, #queue-req: 117
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 650, cache hit rate: 0.00%, token usage: 0.13, #running-req: 83, #queue-req: 116
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 633, cache hit rate: 0.00%, token usage: 0.13, #running-req: 84, #queue-req: 115
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 616, cache hit rate: 0.00%, token usage: 0.14, #running-req: 85, #queue-req: 114
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 599, cache hit rate: 0.00%, token usage: 0.14, #running-req: 86, #queue-req: 113
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 582, cache hit rate: 0.00%, token usage: 0.14, #running-req: 87, #queue-req: 112
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 565, cache hit rate: 0.00%, token usage: 0.14, #running-req: 88, #queue-req: 111
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 548, cache hit rate: 0.00%, token usage: 0.14, #running-req: 89, #queue-req: 110
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 531, cache hit rate: 0.00%, token usage: 0.14, #running-req: 90, #queue-req: 109
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 514, cache hit rate: 0.00%, token usage: 0.15, #running-req: 91, #queue-req: 108
[2024-11-29 10:28:30 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 497, cache hit rate: 0.00%, token usage: 0.15, #running-req: 92, #queue-req: 107
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 480, cache hit rate: 0.00%, token usage: 0.15, #running-req: 93, #queue-req: 106
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 463, cache hit rate: 0.00%, token usage: 0.15, #running-req: 94, #queue-req: 105
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 446, cache hit rate: 0.00%, token usage: 0.15, #running-req: 95, #queue-req: 104
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 429, cache hit rate: 0.00%, token usage: 0.15, #running-req: 96, #queue-req: 103
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 412, cache hit rate: 0.00%, token usage: 0.16, #running-req: 97, #queue-req: 102
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 395, cache hit rate: 0.00%, token usage: 0.16, #running-req: 98, #queue-req: 101
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 378, cache hit rate: 0.00%, token usage: 0.16, #running-req: 99, #queue-req: 100
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 361, cache hit rate: 0.00%, token usage: 0.16, #running-req: 100, #queue-req: 99
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 344, cache hit rate: 0.00%, token usage: 0.16, #running-req: 101, #queue-req: 98
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 327, cache hit rate: 0.00%, token usage: 0.16, #running-req: 102, #queue-req: 97
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 310, cache hit rate: 0.00%, token usage: 0.16, #running-req: 103, #queue-req: 96
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 293, cache hit rate: 0.00%, token usage: 0.17, #running-req: 104, #queue-req: 95
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 276, cache hit rate: 0.00%, token usage: 0.17, #running-req: 105, #queue-req: 94
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 259, cache hit rate: 0.00%, token usage: 0.17, #running-req: 106, #queue-req: 93
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 242, cache hit rate: 0.00%, token usage: 0.17, #running-req: 107, #queue-req: 92
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 225, cache hit rate: 0.00%, token usage: 0.17, #running-req: 108, #queue-req: 91
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 208, cache hit rate: 0.00%, token usage: 0.17, #running-req: 109, #queue-req: 90
[2024-11-29 10:28:31 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 191, cache hit rate: 0.00%, token usage: 0.18, #running-req: 110, #queue-req: 89
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 174, cache hit rate: 0.00%, token usage: 0.18, #running-req: 111, #queue-req: 88
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 157, cache hit rate: 0.00%, token usage: 0.18, #running-req: 112, #queue-req: 87
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 140, cache hit rate: 0.00%, token usage: 0.18, #running-req: 113, #queue-req: 86
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 123, cache hit rate: 0.00%, token usage: 0.18, #running-req: 114, #queue-req: 85
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 106, cache hit rate: 0.00%, token usage: 0.18, #running-req: 115, #queue-req: 84
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 89, cache hit rate: 0.00%, token usage: 0.19, #running-req: 116, #queue-req: 83
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 72, cache hit rate: 0.00%, token usage: 0.19, #running-req: 117, #queue-req: 82
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 55, cache hit rate: 0.00%, token usage: 0.19, #running-req: 118, #queue-req: 81
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 38, cache hit rate: 0.00%, token usage: 0.19, #running-req: 119, #queue-req: 80
[2024-11-29 10:28:32 TP0] Prefill batch. #new-seq: 2, #new-token: 2048, #cached-token: 21, cache hit rate: 0.00%, token usage: 0.19, #running-req: 120, #queue-req: 79
[2024-11-29 10:28:32 TP0] Scheduler hit an exception: Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 1440, in run_scheduler_process
    scheduler.event_loop_overlap()
  File "/opt/conda/envs/py_3.9/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 398, in event_loop_overlap
    batch = self.get_next_batch_to_run()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 761, in get_next_batch_to_run
    new_batch = self.get_new_batch_prefill()
  File "/sgl-workspace/sglang/python/sglang/srt/managers/scheduler.py", line 847, in get_new_batch_prefill
    assert self.being_chunked_req is None
AssertionError

Killed
root@c182a613717a:/dockerx/sglang#
```

### Reproduction

`/dockerx/sglang# python -m sglang.bench_offline_throughput --model-path amd/Meta-Llama-3.1-8B-Instruct-FP8-KV --dataset-name random --num-prompts 200 --random-input-len 2064 --random-output-len 64 --quant fp8 --tensor-parallel-size 1 --random-range-ratio 1 --chunked-prefill-size 2048 --disable-radix-cache`

### Environment

from `v0.3.6.post2-rocm620` ~ `8b48496`
TP=1
model = amd/Meta-Llama-3.1-8B-Instruct-FP8-KV

**Comment by wangraying** [comment]
I hit the same problem when running bench_serving.py, with the server launched as following:
```
python3 -m sglang.launch_server --model-path /models/meta-llama/Llama-3.1-8B-Instruct --port 30000 --schedule-policy fcfs --chunked-prefill-size 256 --enable-mixed-chunk --schedule-conservativeness 1.0 --disable-radix-cache
```
