### ISSUE TITLE
[Bug] EOFError

### ISSUE THREAD

**Issue by HuanzhiMao** [sgl-project/sglang#2294]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

```
[2024-12-01 09:13:28 TP0] Init torch distributed begin.
[2024-12-01 09:13:28 TP2] Init torch distributed begin.
[2024-12-01 09:13:29 TP7] Init torch distributed begin.
[2024-12-01 09:13:29 TP1] Init torch distributed begin.
[2024-12-01 09:13:29 TP6] Init torch distributed begin.
[2024-12-01 09:13:30 TP4] Init torch distributed begin.
[2024-12-01 09:13:30 TP3] Init torch distributed begin.
[2024-12-01 09:13:30 TP5] Init torch distributed begin.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/launch_server.py", line 13, in <module>
    launch_server(server_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/server.py", line 487, in launch_server
    launch_engine(server_args=server_args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/server.py", line 456, in launch_engine
    data = scheduler_pipe_readers[i].recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

### Reproduction

`python -m sglang.launch_server --model-path google/gemma-2-27b-it --tp 8`

### Environment

```
2024-12-01 09:14:57.446738: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-01 09:14:57.460649: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-12-01 09:14:57.477200: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-12-01 09:14:57.482288: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-01 09:14:57.495378: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Python: 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA H100 80GB HBM3
GPU 0,1,2,3,4,5,6,7 Compute Capability: 9.0
CUDA_HOME: /usr
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 550.127.05
PyTorch: 2.5.1+cu124
sglang: 0.3.6.post2
flashinfer: 0.1.6+cu124torch2.4
triton: 3.1.0
transformers: 4.46.3
torchao: 0.6.1
numpy: 1.26.4
aiohttp: 3.11.8
fastapi: 0.115.5
hf_transfer: 0.1.8
huggingface_hub: 0.26.3
interegular: 0.3.3
modelscope: 1.20.1
orjson: 3.10.12
packaging: 21.3
psutil: 5.9.0
pydantic: 2.10.2
multipart: 0.0.19
zmq: 26.2.0
uvicorn: 0.32.1
uvloop: 0.21.0
vllm: 0.6.4.post1
openai: 1.46.0
anthropic: 0.39.0
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    NV18    NV18    NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU1    NV18     X      NV18    NV18    NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU2    NV18    NV18     X      NV18    NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU3    NV18    NV18    NV18     X      NV18    NV18    NV18    NV18    SYS     0-103   0               N/A
GPU4    NV18    NV18    NV18    NV18     X      NV18    NV18    NV18    SYS     104-207 1               N/A
GPU5    NV18    NV18    NV18    NV18    NV18     X      NV18    NV18    SYS     104-207 1               N/A
GPU6    NV18    NV18    NV18    NV18    NV18    NV18     X      NV18    SYS     104-207 1               N/A
GPU7    NV18    NV18    NV18    NV18    NV18    NV18    NV18     X      SYS     104-207 1               N/A
NIC0    SYS     SYS     SYS     SYS     SYS     SYS     SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0


Hypervisor vendor: KVM
ulimit soft: 1048576
```

**Comment by HuanzhiMao** [comment]
Update: Upgrading to `0.3.6.post3` doesn't fix the issue.

**Comment by HuanzhiMao** [comment]
And I didn't get this issue when running on 1xH100.

**Comment by Galaxy-Husky** [comment]
same issue on 2xA100.

**Comment by Galaxy-Husky** [comment]
v0.4.0 hasn't fixed the bug.

**Comment by Kevin-XiongC** [comment]
I got this error on 4xL20.

**Comment by welsonzhang** [comment]
I got this error on 2xT4 too.

**Comment by welsonzhang** [comment]
@zhyncs I found the subprocess of run_scheduler_process  will stuck in ModelRunner 

```
initialize_model_parallel(tensor_model_parallel_size=self.tp_size)
```

this function is import from vllm.distributed ， any idea for this?

**Comment by zhyncs** [comment]
python3 -m sglang.check_env

**Comment by welsonzhang** [comment]
Python: 3.12.3 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:46:43) [GCC 11.2.0]
CUDA available: True
GPU 0,1: Tesla T4
GPU 0,1 Compute Capability: 7.5
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.2, V12.2.140
CUDA Driver Version: 535.104.05
PyTorch: 2.5.1+cu124
sglang: 0.4.0.post2
flashinfer: 0.1.6+cu121torch2.4
triton: 3.1.0
transformers: 4.47.1
torchao: 0.7.0
numpy: 1.26.4
aiohttp: 3.11.11
fastapi: 0.115.6
hf_transfer: 0.1.8
huggingface_hub: 0.27.0
interegular: 0.3.3
modelscope: 1.21.0
orjson: 3.10.12
packaging: 23.2
psutil: 6.1.1
pydantic: 2.10.4
multipart: 0.0.20
zmq: 26.2.0
uvicorn: 0.34.0
uvloop: 0.21.0
vllm: 0.6.4.post1
openai: 1.58.1
anthropic: 0.42.0
decord: 0.6.0
NVIDIA Topology: 
        GPU0    GPU1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     0-39            N/A             N/A
GPU1    SYS      X      0-39            N/A             N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 262140

**Comment by HuanzhiMao** [comment]
The solution I use is to revert back to an older version, such as `0.3.5`.

**Comment by merrymercy** [comment]
This error message means the scheduler crashes during launching. https://github.com/sgl-project/sglang/commit/855d0ba381f6bfa69f906797e33efcd0708797b9 improved the error message.

We suspect it is a bug in nccl or other cuda runtime.

**Comment by longsco** [comment]
[2025-01-15 21:38:59] 
Traceback (most recent call last):
  File "/sgl-workspace/sglang/python/sglang/srt/server.py", line 533, in launch_engine
    data = scheduler_pipe_readers[i].recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
[2025-01-15 21:38:59] Rank 0 scheduler is dead. Please check if there are relevant logs.
[2025-01-15 21:39:01] Exit code: -11
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/sgl-workspace/sglang/python/sglang/launch_server.py", line 14, in <module>
    launch_server(server_args)
  File "/sgl-workspace/sglang/python/sglang/srt/server.py", line 572, in launch_server
    launch_engine(server_args=server_args)
  File "/sgl-workspace/sglang/python/sglang/srt/server.py", line 533, in launch_engine
    data = scheduler_pipe_readers[i].recv()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError


Got this error too running two 8xH100 node on 0.4.1

**Comment by zhangzx-uiuc** [comment]
Got the same error on version 0.4.2.post1. Any updates?

**Comment by ZhiYuanZeng** [comment]
Setting `export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False` works for me

**Comment by Link-Li** [comment]
Got the same error on version 0.4.5.post3
4* 8gpu h100
load deepseek v3, about 20% of the parameters have been loaded, and an EOF error occurs.
And Setting export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:False not work.

**Comment by omid-hip** [comment]
We're getting this issue when we enable nccl-rdma networking
