### ISSUE TITLE
[Bug] Overlap mode scheduler doesn't work for bench_serving with given request rate

### ISSUE THREAD

**Issue by ykcombat** [sgl-project/sglang#2312]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

When I tried using a overlapped scheduler to serve my model and use sglang.bench_serving to evluate performance with a given request rate, the scheduler got stuck and the reporting are as follows：
`Exception in thread Thread-3 (forward_thread_func):
Traceback (most recent call last):
  File "/state/partition/ykchen/conda/envs/sglang/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/state/partition/ykchen/conda/envs/sglang/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ykchen/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 99, in forward_thread_func
    self.forward_thread_func_()
  File "/state/partition/ykchen/conda/envs/sglang/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ykchen/sglang/python/sglang/srt/managers/tp_worker_overlap_thread.py", line 116, in forward_thread_func_
    logits_output, next_token_ids = self.worker.forward_batch_generation(
  File "/home/ykchen/sglang/python/sglang/srt/managers/tp_worker.py", line 139, in forward_batch_generation
    logits_output = self.model_runner.forward(forward_batch)
  File "/home/ykchen/sglang/python/sglang/srt/model_executor/model_runner.py", line 594, in forward
    return self.forward_decode(forward_batch)
  File "/home/ykchen/sglang/python/sglang/srt/model_executor/model_runner.py", line 565, in forward_decode
    return self.model.forward(
  File "/state/partition/ykchen/conda/envs/sglang/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/ykchen/sglang/python/sglang/srt/models/llama.py", line 372, in forward
    res = self.logits_processor(
  File "/state/partition/ykchen/conda/envs/sglang/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/state/partition/ykchen/conda/envs/sglang/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ykchen/sglang/python/sglang/srt/layers/logits_processor.py", line 186, in forward
    last_logits = last_logits[:, : self.config.vocab_size].float()
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`
However when I run bench_serving without specifying request rate, the scheduler works well. Besides, the normal scheduler can also work well with a given request rate.

### Reproduction

Model: Meta-Llama-3-8B-Instruct
Command to start engine:
`python -m sglang.launch_server --model-path /path/to/my/model --port 30000 --host 0.0.0.0 --disable-cuda-graph --disable-radix-cache --enable-overlap-schedule`
Command to start benchmark:
`python -m sglang.bench_serving --backend sglang --num-prompt 100 --request-rate 3`
It works when I use `python -m sglang.bench_serving --backend sglang --num-prompt 100` without specifying request rate.

### Environment

`Python: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A40
GPU 0,1,2,3 Compute Capability: 8.6
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.3, V12.3.107
CUDA Driver Version: 545.23.08
PyTorch: 2.4.0+cu121
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.46.1
requests: 2.32.3
tqdm: 4.66.6
numpy: 1.26.4
aiohttp: 3.10.10
fastapi: 0.115.4
hf_transfer: 0.1.8
huggingface_hub: 0.26.2
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.1.0
pydantic: 2.9.2
uvicorn: 0.32.0
uvloop: 0.21.0
zmq: 26.2.0
vllm: 0.6.3.post1
multipart: 0.0.16
openai: 1.53.0
anthropic: 0.37.1
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      PIX     SYS     SYS     0-11,24-35      0               N/A
GPU1    PIX      X      SYS     SYS     0-11,24-35      0               N/A
GPU2    SYS     SYS      X      PXB     12-23,36-47     1               N/A
GPU3    SYS     SYS     PXB      X      12-23,36-47     1               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1048576`

**Comment by merrymercy** [comment]
It seems you are using an old version. Your bug should already be fixed. Please use the latest main branch or 0.3.6.post3. 
The argument ` --enable-overlap-schedule` is deprecated and the overlap scheduler is enabled by default.
