### ISSUE TITLE
[Bug] ValueError: Model architectures ['Qwen2ForCausalLM'] are not supported for now. Supported architectures: dict_keys(['CohereForCausalLM', 'DbrxForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'OlmoForCausalLM', 'Phi3SmallForCausalLM', 'StableLmForCausalLM', 'XverseForCausalLM', 'XverseMoeForCausalLM'])

### ISSUE THREAD

**Issue by Trangle** [sgl-project/sglang#2356]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

2024-12-05 11:18:00,870 - datasets - INFO - PyTorch version 2.5.1 available.
2024-12-05 11:18:00,897 - datasets - INFO - Polars version 1.12.0 available.
2024-12-05 11:18:00,923 - datasets - INFO - TensorFlow version 2.16.1 available.
2024-12-05 11:18:00,949 - datasets - INFO - JAX version 0.4.35 available.
[2024-12-05 11:18:19 TP0] Scheduler hit an exception: Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1489, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 194, in __init__
    self.tp_worker = TpWorkerClass(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 61, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 62, in __init__
    self.model_runner = ModelRunner(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 152, in __init__
    self.load_model()
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 246, in load_model
    self.model = get_model(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_loader/__init__.py", line 22, in get_model
    return loader.load_model(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_loader/loader.py", line 357, in load_model
    model = _initialize_model(
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_loader/loader.py", line 136, in _initialize_model
    model_class, _ = get_model_architecture(model_config)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/model_loader/utils.py", line 37, in get_model_architecture
    return ModelRegistry.resolve_model_cls(architectures)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/registry.py", line 65, in resolve_model_cls
    return self._raise_for_unsupported(architectures)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/models/registry.py", line 32, in _raise_for_unsupported
    raise ValueError(
ValueError: Model architectures ['Qwen2ForCausalLM'] are not supported for now. Supported architectures: dict_keys(['CohereForCausalLM', 'DbrxForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'OlmoForCausalLM', 'Phi3SmallForCausalLM', 'StableLmForCausalLM', 'XverseForCausalLM', 'XverseMoeForCausalLM'])

### Reproduction

runtime = sgl.Runtime(
  model_path="Qwen/Qwen2.5-7B-Instruct", 
  tp_size=1,
  mem_fraction_static=0.8,
  # enable_flashinfer=True,
)
sgl.set_default_backend(runtime)

### Environment

python 3.10 with torch 2.5.1, vllm 0.6.4.post1 and transformers 4.63.1

**Comment by zhyncs** [comment]
I did not reproduce your issue using the latest v0.4.0 docker.

**Comment by squirrelfish** [comment]
same error, with message "Ignore import error when loading sglang.srt.models.qwen2. cannot import name 'gemma_fused_add_rmsnorm' from 'flashinfer.norm'"

**Comment by wanglining97** [comment]
same error, ValueError: Unsupported architectures: Qwen2VLForConditionalGeneration. Supported list: ['CohereForCausalLM', 'DbrxForCausalLM', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'OlmoForCausalLM', 'Phi3SmallForCausalLM', 'StableLmForCausalLM', 'XverseForCausalLM', 'XverseMoeForCausalLM']
