### ISSUE TITLE
[Bug] sglang-router failure

### ISSUE THREAD

**Issue by fengyang95** [sgl-project/sglang#2361]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

```bash 
python3 -m sglang_router.launch_server --quantization fp8 --enable-overlap-schedule   --model $LOCAL_PATH  --attention-backend $ATTENTION_BACKEND --stream-interval  $STREAM_INTERVAL --max-prefill-tokens $MODEL_LEN  --root-path $ROOT_PATH --trust-remote-code  --mem-frac $MEM_FRAC --tp $TP_SIZE --dp $DP_SIZE --kv-cache-dtype $KV_CACHE_DTYPE --port $PORT0 --mem-fraction-static $MEM_FRACTION_STATIC --schedule-conservativeness $SCHEDULE_CONSERVATIVENESS --context-length $MODEL_LEN  --chunked-prefill-size $CHUNKED_PREFILL_SIZE
```

error:
```bash
[2024-12-05 17:27:10 TP1] Capture cuda graph begin. This can take up to several minutes.
[2024-12-05 17:27:10 TP0] Capture cuda graph begin. This can take up to several minutes.
INFO 12-05 17:27:24 custom_all_reduce.py:233] Registering 2967 cuda graph addresses
INFO 12-05 17:27:24 custom_all_reduce.py:233] Registering 2967 cuda graph addresses
[2024-12-05 17:27:24 TP0] max_total_num_tokens=1058405, max_prefill_tokens=32768, max_running_requests=4097, context_len=32768
[2024-12-05 17:27:24 TP1] max_total_num_tokens=1058405, max_prefill_tokens=32768, max_running_requests=4097, context_len=32768
[2024-12-05 17:27:24] host:None
[2024-12-05 17:27:24] INFO:     Started server process [8158]
[2024-12-05 17:27:24] INFO:     Waiting for application startup.
[2024-12-05 17:27:24] INFO:     Application startup complete.
[2024-12-05 17:27:24] ERROR:    [Errno 98] error while attempting to bind on address ('::', 31000, 0, 0): address already in use
[2024-12-05 17:27:24] INFO:     Waiting for application shutdown.
[2024-12-05 17:27:24] INFO:     Application shutdown complete.
[2024-12-05 17:29:25] Initialization failed. warmup error: Traceback (most recent call last):
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/connection.py", line 199, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 495, in _make_request
    conn.request(
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/connection.py", line 441, in request
    self.endheaders()
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/connection.py", line 279, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/connection.py", line 214, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f998560add0>: Failed to establish a new connection: [Errno 111] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='0.0.0.0', port=31000): Max retries exceeded with url: /get_model_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f998560add0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/tiger/custome_sglang/python/sglang/srt/server.py", line 562, in _wait_and_warmup
    res = requests.get(url + "/get_model_info", timeout=5, headers=headers)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=31000): Max retries exceeded with url: /get_model_info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f998560add0>: Failed to establish a new connection: [Errno 111] Connection refused'))

[Router (Python)] 2024-12-05 17:31:47 - ERROR - Server on port 31000 failed to become healthy
[Router (Python)] 2024-12-05 17:31:47 - ERROR - Not all servers are healthy. Shutting down...
[Router (Python)] 2024-12-05 17:31:47 - INFO - Cleaning up processes...
[Router (Python)] 2024-12-05 17:31:47 - INFO - Cleaning up processes...
[Router (Python)] 2024-12-05 17:31:47 - INFO - Cleaning up processes...
/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
  ```

### Reproduction

```bash
python3 -m sglang_router.launch_server --quantization fp8 --enable-overlap-schedule   --model $LOCAL_PATH  --attention-backend $ATTENTION_BACKEND --stream-interval  $STREAM_INTERVAL --max-prefill-tokens $MODEL_LEN  --root-path $ROOT_PATH --trust-remote-code  --mem-frac $MEM_FRAC --tp $TP_SIZE --dp $DP_SIZE --kv-cache-dtype $KV_CACHE_DTYPE --port $PORT0 --mem-fraction-static $MEM_FRACTION_STATIC --schedule-conservativeness $SCHEDULE_CONSERVATIVENESS --context-length $MODEL_LEN  --chunked-prefill-size $CHUNKED_PREFILL_SIZE
```

### Environment

Python: 3.11.2 (main, Jul 23 2024, 17:09:09) [GCC 10.2.1 20210110]
CUDA available: True
GPU 0,1: NVIDIA H20
GPU 0,1 Compute Capability: 9.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.4, V12.4.131
CUDA Driver Version: 535.161.08
PyTorch: 2.4.0+cu124
sglang: 0.3.5
flashinfer: 0.1.6+cu124torch2.4
triton: 3.0.0
transformers: 4.46.3
requests: 2.32.3
tqdm: 4.67.1
numpy: 1.26.3
aiohttp: 3.11.7
fastapi: 0.115.5
hf_transfer: 0.1.8
huggingface_hub: 0.26.2
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.1.0
pydantic: 2.10.2
uvicorn: 0.32.1
uvloop: 0.21.0
zmq: 26.2.0
vllm: 0.6.3.post1
multipart: 0.0.19
openai: 1.56.2
anthropic: 0.40.0
NVIDIA Topology: 
        GPU0    GPU1    NIC0    NIC1    NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV18    PIX     NODE    NODE    NODE    SYS     SYS     SYS     SYS     1-47,97-143     0               N/A
GPU1    NV18     X      NODE    PIX     NODE    NODE    SYS     SYS     SYS     SYS     1-47,97-143     0               N/A
NIC0    PIX     NODE     X      NODE    NODE    NODE    SYS     SYS     SYS     SYS
NIC1    NODE    PIX     NODE     X      NODE    NODE    SYS     SYS     SYS     SYS
NIC2    NODE    NODE    NODE    NODE     X      NODE    SYS     SYS     SYS     SYS
NIC3    NODE    NODE    NODE    NODE    NODE     X      SYS     SYS     SYS     SYS
NIC4    SYS     SYS     SYS     SYS     SYS     SYS      X      NODE    NODE    NODE
NIC5    SYS     SYS     SYS     SYS     SYS     SYS     NODE     X      NODE    NODE
NIC6    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE     X      NODE
NIC7    SYS     SYS     SYS     SYS     SYS     SYS     NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_1
  NIC1: mlx5_2
  NIC2: mlx5_3
  NIC3: mlx5_4
  NIC4: mlx5_5
  NIC5: mlx5_6
  NIC6: mlx5_7
  NIC7: mlx5_8

ulimit soft: 1024768

**Comment by ByronHsu** [comment]
The error seems be to `[Errno 98] error while attempting to bind on address ('::', 31000, 0, 0): address already in use`. Did you make sure that was not occupied?

**Comment by fengyang95** [comment]
> The error seems be to `[Errno 98] error while attempting to bind on address ('::', 31000, 0, 0): address already in use`. Did you make sure that was not occupied?

@ByronHsu Thanks, switching the port number fixed the issue.

**Comment by fengyang95** [comment]
@ByronHsu  Hi, after resolving this issue, the server still fails at times.
Using sglang.launch_server to start is normal.
```bash
[2024-12-06 16:06:48 TP0] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=76.80 GB
[2024-12-06 16:06:48 TP1] Load weight end. type=Qwen2ForCausalLM, dtype=torch.bfloat16, avail mem=76.80 GB
[2024-12-06 16:06:48 TP0] Memory pool end. avail mem=11.55 GB
[2024-12-06 16:06:48 TP1] Memory pool end. avail mem=11.55 GB
[2024-12-06 16:06:48 TP0] Capture cuda graph begin. This can take up to several minutes.
[2024-12-06 16:06:48 TP1] Capture cuda graph begin. This can take up to several minutes.
INFO 12-06 16:07:01 custom_all_reduce.py:233] Registering 2967 cuda graph addresses
INFO 12-06 16:07:01 custom_all_reduce.py:233] Registering 2967 cuda graph addresses
[2024-12-06 16:07:01 TP1] max_total_num_tokens=1058405, max_prefill_tokens=32768, max_running_requests=4097, context_len=32768
[2024-12-06 16:07:01 TP0] max_total_num_tokens=1058405, max_prefill_tokens=32768, max_running_requests=4097, context_len=32768
[2024-12-06 16:07:02] host:None
[2024-12-06 16:07:02] INFO:     Started server process [17965]
[2024-12-06 16:07:02] INFO:     Waiting for application startup.
[2024-12-06 16:07:02] INFO:     Application startup complete.
[2024-12-06 16:07:02] INFO:     Uvicorn running on http://0.0.0.0:9254 (Press CTRL+C to quit)
[2024-12-06 16:07:03] INFO:     127.0.0.1:56678 - "GET /get_model_info HTTP/1.1" 200 OK
[2024-12-06 16:07:03 TP0] Prefill batch. #new-seq: 1, #new-token: 6, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
[2024-12-06 16:07:05] INFO:     127.0.0.1:56682 - "POST /generate HTTP/1.1" 200 OK
[2024-12-06 16:07:05] The server is fired up and ready to roll!
[Router (Python)] 2024-12-06 16:11:23 - ERROR - Server on port 9254 failed to become healthy
[Router (Python)] 2024-12-06 16:11:23 - ERROR - Not all servers are healthy. Shutting down...
[Router (Python)] 2024-12-06 16:11:23 - INFO - Cleaning up processes...
[2024-12-06 16:11:23] SIGTERM received. signum=None frame=None. Draining requests and shutting down...
[Router (Python)] 2024-12-06 16:11:26 - WARNING - Process 17965 did not terminate gracefully, force killing...
[Router (Python)] 2024-12-06 16:11:26 - INFO - Cleaning up processes...
[Router (Python)] 2024-12-06 16:11:26 - INFO - Cleaning up processes...
/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/tiger/.pyenv/versions/3.11.2/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by ByronHsu** [comment]
```
[Router (Python)] 2024-12-06 16:11:23 - ERROR - Server on port 9254 failed to become healthy
[Router (Python)] 2024-12-06 16:11:23 - ERROR - Not all servers are healthy. Shutting down...
```

It seems that one of the worker becomes unhealthy for some reasons. The logic `sglang_router.launch_server` is simple

1. start N sglang servers concurrently and wait until they are healthy
2. start a router binding to the servers

The code is [here](https://github.com/sgl-project/sglang/blob/main/rust/py_src/sglang_router/launch_server.py). Can we look into why `9254` was unhealthy?

**Comment by amd-maheshs3** [comment]
error: there is no --root-path argument?

**Comment by bikong2** [comment]
we use sglang for mllm inference. we got the same error when there is a invalid input or error in sglang inference, the sglang router will stop to work correctly, and we do not know the reason, is this a known bug?
