### ISSUE TITLE
[Bug] File "/u02/liuys/sglang/python/sglang/srt/server.py", line 621, in _wait_and_warmup Killed

### ISSUE THREAD

**Issue by lys791227** [sgl-project/sglang#2418]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

 执行 python -m sglang.launch_server  --model-path /u01/liuys/.cache/modelscope/hub/qwen/Qwen2___5-7B-Instruct  --tp-size 4   --host 0.0.0.0  --port 8008 过一段时间就出现下面的错误
[2024-12-09 16:10:09] INFO:     Uvicorn running on http://0.0.0.0:8008 (Press CTRL+C to quit)
[2024-12-09 16:10:51] INFO:     10.1.1.33:46322 - "GET /v1/models HTTP/1.1" 200 OK
[2024-12-09 16:10:51] INFO:     10.1.1.33:46322 - "POST /v1/chat/completions HTTP/1.1" 200 OK
[2024-12-09 16:10:51 TP0] Prefill batch. #new-seq: 1, #new-token: 25, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
[2024-12-09 16:10:56 TP0] Decode batch. #running-req: 1, #token: 66, token usage: 0.00, gen throughput (token/s): 0.83, #queue-req: 0
[2024-12-09 16:10:57 TP0] Decode batch. #running-req: 1, #token: 106, token usage: 0.00, gen throughput (token/s): 122.39, #queue-req: 0
[2024-12-09 16:10:57 TP0] Decode batch. #running-req: 1, #token: 146, token usage: 0.00, gen throughput (token/s): 122.59, #queue-req: 0
[2024-12-09 16:10:57 TP0] Decode batch. #running-req: 1, #token: 186, token usage: 0.00, gen throughput (token/s): 121.76, #queue-req: 0
[2024-12-09 16:10:58 TP0] Decode batch. #running-req: 1, #token: 226, token usage: 0.00, gen throughput (token/s): 122.17, #queue-req: 0
[2024-12-09 16:10:58 TP0] Decode batch. #running-req: 1, #token: 266, token usage: 0.00, gen throughput (token/s): 123.13, #queue-req: 0
[2024-12-09 16:14:24] Initialization failed. warmup error: Traceback (most recent call last):
  File "/u02/liuys/sglang/python/sglang/srt/server.py", line 621, in _wait_and_warmup
    assert res.status_code == 200, f"{res=}, {res.text=}"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: res=<Response [503]>, res.text=''

Killed

### Reproduction

无

### Environment

无

**Comment by LjT0812** [comment]
一样的错误

**Comment by LjT0812** [comment]
#./XXXXXXXX/sglang/srt/server.py  
line 617：把循环改大后不报错了

code：
    # Wait until the server is launched
    success = False
    for _ in range(12000):
        time.sleep(1)
        try:
            res = requests.get(url + "/get_model_info", timeout=5, headers=headers)
            assert res.status_code == 200, f"{res=}, {res.text=}"
            success = True
            break
        except (AssertionError, requests.exceptions.RequestException):
            last_traceback = get_exception_traceback()
            pass

**Comment by lys791227** [comment]
> #./XXXXXXXX/sglang/srt/server.py line 617：把循环改大后不报错了
> 
> code： # Wait until the server is launched success = False for _ in range(12000): time.sleep(1) try: res = requests.get(url + "/get_model_info", timeout=5, headers=headers) assert res.status_code == 200, f"{res=}, {res.text=}" success = True break except (AssertionError, requests.exceptions.RequestException): last_traceback = get_exception_traceback() pass

unset http_proxy 
unset https_proxy 
ok!
