### ISSUE TITLE
[Bug] SGLang's OpenAI interface fails with Llama-3.2-1B due to missing chat template

### ISSUE THREAD

**Issue by NeilJohnson0930** [sgl-project/sglang#2431]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

The official SGLang OpenAI interface example works without chat template, but when using Llama-3.2-1B, it throws ValueError requiring chat template. This seems inconsistent with the documentation.

Error: "Cannot use chat template functions because tokenizer.chat_template is not set"

### Reproduction

(camel-ai-py3.10) mi@mi:~/gitlab/ml_explore/camel$ cat test/test_openai_sglang.py 
from sglang.utils import (
    execute_shell_command,
    wait_for_server,
    terminate_process,
)

server_process = execute_shell_command(
    "python -m sglang.launch_server --model-path meta-llama/Llama-3.2-1B --port 30000 --host 0.0.0.0"
)

wait_for_server("http://localhost:30000")

from openai import OpenAI

client = OpenAI(base_url="http://127.0.0.1:30000/v1", api_key="None")

response = client.chat.completions.create(
    model="meta-llama/Llama-3.2-1B",
    messages=[
        {"role": "user", "content": "List 3 countries and their capitals."},
    ],
    temperature=0,
    max_tokens=64,
)

print(response)

terminate_process(server_process)
(camel-ai-py3.10) mi@mi:~/gitlab/ml_explore/camel$ python3 test/test_openai_sglang.py 
[2024-12-10 21:23:27] server_args=ServerArgs(model_path='meta-llama/Llama-3.2-1B', tokenizer_path='meta-llama/Llama-3.2-1B', tokenizer_mode='auto', skip_tokenizer_init=False, load_format='auto', trust_remote_code=False, dtype='auto', kv_cache_dtype='auto', quantization=None, context_length=None, device='cuda', served_model_name='meta-llama/Llama-3.2-1B', chat_template=None, is_embedding=False, host='0.0.0.0', port=30000, mem_fraction_static=0.88, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=2048, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, cpu_offload_gb=0, tp_size=1, stream_interval=1, random_seed=32666879, constrained_json_whitespace_pattern=None, watchdog_timeout=300, download_dir=None, base_gpu_id=0, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_pth='SGLang_storage', enable_cache_report=False, dp_size=1, load_balance_method='round_robin', dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, lora_paths=None, max_loras_per_batch=8, attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='outlines', disable_radix_cache=False, disable_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=4, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, num_continuous_decode_steps=1, delete_ckpt_after_loading=False)
[2024-12-10 21:23:32 TP0] Init torch distributed begin.
[2024-12-10 21:23:33 TP0] Load weight begin. avail mem=23.32 GB
INFO 12-10 21:23:36 weight_utils.py:243] Using model weights format ['*.safetensors']
INFO 12-10 21:23:36 weight_utils.py:288] No model.safetensors.index.json found in remote.
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  4.22it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  4.21it/s]

[2024-12-10 21:23:37 TP0] Load weight end. type=LlamaForCausalLM, dtype=torch.bfloat16, avail mem=20.45 GB
[2024-12-10 21:23:37 TP0] Memory pool end. avail mem=1.66 GB
[2024-12-10 21:23:37 TP0] Capture cuda graph begin. This can take up to several minutes.
[2024-12-10 21:23:38 TP0] max_total_num_tokens=578385, max_prefill_tokens=16384, max_running_requests=2260, context_len=131072
[2024-12-10 21:23:39] INFO:     Started server process [2393459]
[2024-12-10 21:23:39] INFO:     Waiting for application startup.
[2024-12-10 21:23:39] INFO:     Application startup complete.
[2024-12-10 21:23:39] INFO:     Uvicorn running on http://0.0.0.0:30000 (Press CTRL+C to quit)
[2024-12-10 21:23:39] INFO:     127.0.0.1:37630 - "GET /v1/models HTTP/1.1" 200 OK
[2024-12-10 21:23:40] INFO:     127.0.0.1:37642 - "GET /get_model_info HTTP/1.1" 200 OK
[2024-12-10 21:23:40 TP0] Prefill batch. #new-seq: 1, #new-token: 7, #cached-token: 0, cache hit rate: 0.00%, token usage: 0.00, #running-req: 0, #queue-req: 0
[2024-12-10 21:23:40] INFO:     127.0.0.1:37646 - "POST /generate HTTP/1.1" 200 OK
[2024-12-10 21:23:40] The server is fired up and ready to roll!
<IPython.core.display.HTML object>
[2024-12-10 21:23:44] INFO:     127.0.0.1:37648 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
[2024-12-10 21:23:44] ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 73, in app
    response = await f(request)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/sglang/srt/metrics/func_timer.py", line 74, in async_wrapper
    return await func(*args, **kwargs)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/sglang/srt/server.py", line 318, in openai_v1_chat_completions
    return await v1_chat_completions(tokenizer_manager, raw_request)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/sglang/srt/openai_api/adapter.py", line 1100, in v1_chat_completions
    adapted_request, request = v1_chat_generate_request(all_requests, tokenizer_manager)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/sglang/srt/openai_api/adapter.py", line 885, in v1_chat_generate_request
    prompt_ids = tokenizer_manager.tokenizer.apply_chat_template(
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1617, in apply_chat_template
    chat_template = self.get_chat_template(chat_template, tools)
  File "/home/mi/.cache/pypoetry/virtualenvs/camel-ai-34ULexV3-py3.10/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1785, in get_chat_template
    raise ValueError(
ValueError: Cannot use chat template functions because tokenizer.chat_template is not set and no template argument was passed! For information about writing templates and setting the tokenizer.chat_template attribute, please see the documentation at https://huggingface.co/docs/transformers/main/en/chat_templating

### Environment

(camel-ai-py3.10) mi@mi:~/gitlab/ml_explore/camel$ python3 -m sglang.check_env
Python: 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]
CUDA available: True
GPU 0: NVIDIA GeForce RTX 3090
GPU 0 Compute Capability: 8.6
CUDA_HOME: None
PyTorch: 2.5.1+cu124
sglang: 0.3.6.post2
flashinfer: 0.1.6+cu124torch2.4
triton: 3.1.0
transformers: 4.47.0
torchao: 0.6.1
numpy: 1.26.4
aiohttp: 3.11.10
fastapi: 0.115.6
hf_transfer: 0.1.8
huggingface_hub: 0.26.5
interegular: 0.3.3
modelscope: 1.20.1
orjson: 3.10.12
packaging: 23.2
psutil: 6.1.0
pydantic: 2.9.2
multipart: 0.0.19
zmq: 26.2.0
uvicorn: 0.32.1
uvloop: 0.21.0
vllm: 0.6.4.post1
openai: 1.57.1
anthropic: 0.29.2
decord: 0.6.0
NVIDIA Topology: 
	GPU0	CPU Affinity	NUMA Affinity	GPU NUMA ID
GPU0	 X 	0-23	0		N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024

**Comment by zhaochenyang20** [comment]
@NeilJohnson0930 Thanks for point this out. As you can see in our docs, our documents are complied in our CI with the version on our main branch and can run successfully with the results shown in the docs directly.

**Comment by zhaochenyang20** [comment]
I rerun your codes in v0.3.6 and have the same error. Could you plz update your SGLang to the latest version v0.4? The problem is solved on it.

```
from sglang.utils import (
    execute_shell_command,
    wait_for_server,
    terminate_process,
    print_highlight,
)

import requests

server_process = execute_shell_command(
    """
python3 -m sglang.launch_server --model-path meta-llama/Llama-3.2-1B --port=30010
"""
)

wait_for_server("http://localhost:30010")
```

**Comment by NeilJohnson0930** [comment]
Hi Chenyang, upgrading SGLang to 0.4.0 doesn’t seem any help, probelm still.

**Comment by zhaochenyang20** [comment]
@NeilJohnson0930 @zhyncs I find that this error comes from huggingface's update.

It seems that `meta-llama/Llama-3.2-1B` and `meta-llama/Llama-3.2-3B` lost its `chat_template` remotely, but `meta-llama/Llama-3.2-1B-Instruct` and ``meta-llama/Llama-3.2-3B-Instruct` does not.

```python
from transformers import AutoTokenizer

def test_llama_chat_template():

    tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B")


    messages = [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Hello, how are you?"},
        {"role": "assistant", "content": "I'm doing well, thank you! How can I help you today?"},
        {"role": "user", "content": "What's the weather like?"}
    ]

    try:
        output = tokenizer.apply_chat_template(
            messages,
            tokenize=True,
            add_generation_prompt=True
        )
        
        # 打印token IDs
        print("Token IDs:", output)
        
        decoded_text = tokenizer.decode(output)
        print("\nDecoded text:")
        print(decoded_text)
        
    except Exception as e:
        print(f"Error occurred: {str(e)}")

if __name__ == "__main__":
    test_llama_chat_template()
```

1. Would you please try instruct model?
2. For 3090, 3B also works out. Actually I think 8B also works.

**Comment by zhaochenyang20** [comment]
PS: @NeilJohnson0930 I found that `meta-llama/Meta-Llama-3.1-8B` also lost its `chat_template` 😓

**Comment by NeilJohnson0930** [comment]
hi chenyang, I tested the *-Instruct model and confirmed that it works properly. We will use this model to bypass the issue. Thanks a lot!
