### ISSUE TITLE
[Feature] Do we have any plan for supporting MiniCPM-V 2.6?

### ISSUE THREAD

**Issue by Xeladoes** [sgl-project/sglang#2461]
### Checklist

- [X] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 2. Please use English, otherwise it will be closed.

### Motivation

Do we have any plan for supporting MiniCPM-V 2.6?

To my experience this 8B model has better performance than other 7B vlm models

### Related resources

https://github.com/OpenBMB/MiniCPM-V
https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/minicpmv.py

**Comment by zhaochenyang20** [comment]
@Xeladoes I've asked a MiniCPM team member to serve this. Ping me later if this is not solved these days.

**Comment by Xeladoes** [comment]
@zhaochenyang20 not solved these days

**Comment by zhaochenyang20** [comment]
Thanks! I will continue to ask MiniCPM team.

**Comment by zhaochenyang20** [comment]
@mickqian Mick, would you like to take part on this?

**Comment by zhaochenyang20** [comment]
https://huggingface.co/blog/paligemma

@adarshxs Would you like to take mincpm and paligemma! Thanks a lot.

**Comment by zhaochenyang20** [comment]
@Xeladoes Already supported! Great work and thanks  @mickqian @yizhang2077

**Comment by Xeladoes** [comment]
> [@Xeladoes](https://github.com/Xeladoes) Already supported! Great work and thanks [@mickqian](https://github.com/mickqian) [@yizhang2077](https://github.com/yizhang2077)

thanks for the hard work!

**Comment by JohnnyBoyzzz** [comment]
> [@Xeladoes](https://github.com/Xeladoes) Already supported! Great work and thanks [@mickqian](https://github.com/mickqian) [@yizhang2077](https://github.com/yizhang2077)

how to deploy with sglang, I try,but failed in sglang==0.4.1.post6.

**Comment by zhaochenyang20** [comment]
@mickqian Could you give a command?

**Comment by mickqian** [comment]
> > [@Xeladoes](https://github.com/Xeladoes) Already supported! Great work and thanks [@mickqian](https://github.com/mickqian) [@yizhang2077](https://github.com/yizhang2077)@Xeladoes 已经支持！干得好，感谢 @mickqian @yizhang2077
> 
> how to deploy with sglang, I try,but failed in sglang==0.4.1.post6.如何使用 sglang 部署，我尝试了，但在 sglang==0.4.1.post6 中失败了。

How did you deploy it? Should work with:
```zsh
python -m sglang.launch_server --model openbmb/MiniCPM-V-2_6 --chat-template minicpmv --trust-remote-code
```

**Comment by JohnnyBoyzzz** [comment]
> [@mickqian](https://github.com/mickqian) Could you give a command?

# Command
CUDA_VISIBLE_DEVICES=4 /root/anaconda3/envs/sglang/bin/python -m sglang.launch_server \
    --model-path model/MiniCPM-V-2_6 \
    --served-model-name minicpm_v \
    --context-length 4096 \
    --tensor-parallel-size 1 \
    --chat-template minicpmv \
    --host 0.0.0.0 \
    --port 8090 \
    --mem-fraction-static 0.9 \
    --trust-remote-code 

# log
[2025-01-21 10:11:55] server_args=ServerArgs(model_path='model/MiniCPM-V-2_6', tokenizer_path='/mnt/new_pfs/liming_team/scc/model/MiniCPM-V-2_6-mix', tokenizer_mode='auto', load_format='auto', trust_remote_code=True, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, quantization=None, context_length=4096, device='cuda', served_model_name='minicpm_v', chat_template='minicpmv', is_embedding=False, revision=None, skip_tokenizer_init=False, host='0.0.0.0', port=8090, mem_fraction_static=0.9, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=8192, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, cpu_offload_gb=0, prefill_only_one_req=False, tp_size=1, stream_interval=1, random_seed=1009546983, constrained_json_whitespace_pattern=None, watchdog_timeout=300, download_dir=None, base_gpu_id=0, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_pth='sglang_storage', enable_cache_report=False, dp_size=1, load_balance_method='round_robin', ep_size=1, dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', lora_paths=None, max_loras_per_batch=8, attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='outlines', speculative_draft_model_path=None, speculative_algorithm=None, speculative_num_steps=5, speculative_num_draft_tokens=64, speculative_eagle_topk=8, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, disable_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_ep_moe=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=160, cuda_graph_bs=None, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_custom_logit_processor=False)
[2025-01-21 10:11:56] vision_config is None, using default vision config
/root/anaconda3/envs/sglang/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:520: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
[2025-01-21 10:11:57] Use chat template for the OpenAI-compatible API server: minicpmv
[2025-01-21 10:12:03 TP0] vision_config is None, using default vision config
/root/anaconda3/envs/sglang/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:520: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
[2025-01-21 10:12:04 TP0] Overlap scheduler is disabled for multimodal models.
[2025-01-21 10:12:04 TP0] vision_config is None, using default vision config
[2025-01-21 10:12:04 TP0] Automatically reduce --mem-fraction-static to 0.855 because this is a multimodal model.
[2025-01-21 10:12:04 TP0] Init torch distributed begin.
[2025-01-21 10:12:04 TP0] Load weight begin. avail mem=76.33 GB
[2025-01-21 10:12:04 TP0] Ignore import error when loading sglang.srt.models.minicpmv. cannot import name 'get_sampler' from 'vllm.model_executor.layers.sampler' (/root/anaconda3/envs/sglang/lib/python3.10/site-packages/vllm/model_executor/layers/sampler.py)
[2025-01-21 10:12:04 TP0] Scheduler hit an exception: Traceback (most recent call last):
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 1747, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 239, in __init__
    self.tp_worker = TpWorkerClass(
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 185, in __init__
    self.load_model()
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 303, in load_model
    self.model = get_model(
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_loader/__init__.py", line 22, in get_model
    return loader.load_model(
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_loader/loader.py", line 357, in load_model
    model = _initialize_model(
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_loader/loader.py", line 136, in _initialize_model
    model_class, _ = get_model_architecture(model_config)
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/model_loader/utils.py", line 37, in get_model_architecture
    return ModelRegistry.resolve_model_cls(architectures)
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/models/registry.py", line 65, in resolve_model_cls
    return self._raise_for_unsupported(architectures)
  File "/root/anaconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/models/registry.py", line 32, in _raise_for_unsupported
    raise ValueError(
ValueError: Model architectures ['MiniCPMV'] are not supported for now. Supported architectures: dict_keys(['BaichuanForCausalLM', 'ChatGLMModel', 'CohereForCausalLM', 'DbrxForCausalLM', 'DeepseekForCausalLM', 'DeepseekV2ForCausalLM', 'DeepseekV3ForCausalLM', 'ExaoneForCausalLM', 'GemmaForCausalLM', 'Gemma2ForCausalLM', 'Gemma2ForSequenceClassification', 'GPT2LMHeadModel', 'GPTBigCodeForCausalLM', 'GraniteForCausalLM', 'Grok1ForCausalLM', 'Grok1ModelForCausalLM', 'InternLM2ForCausalLM', 'InternLM2ForRewardModel', 'LlamaForCausalLM', 'Phi3ForCausalLM', 'InternLM3ForCausalLM', 'LlamaForClassification', 'LlamaForCausalLMEagle', 'LlamaEmbeddingModel', 'MistralModel', 'LlamaForSequenceClassification', 'LlamaForSequenceClassificationWithNormal_Weights', 'LlavaLlamaForCausalLM', 'LlavaQwenForCausalLM', 'LlavaMistralForCausalLM', 'LlavaVidForCausalLM', 'MiniCPMForCausalLM', 'MiniCPM3ForCausalLM', 'MistralForCausalLM', 'MixtralForCausalLM', 'QuantMixtralForCausalLM', 'MllamaForConditionalGeneration', 'OlmoForCausalLM', 'Olmo2ForCausalLM', 'OlmoeForCausalLM', 'Phi3SmallForCausalLM', 'QWenLMHeadModel', 'Qwen2ForCausalLM', 'Qwen2ForCausalLMEagle', 'Qwen2MoeForCausalLM', 'Qwen2VLForConditionalGeneration', 'StableLmForCausalLM', 'TorchNativeLlamaForCausalLM', 'TorchNativePhi3ForCausalLM', 'XverseForCausalLM', 'XverseMoeForCausalLM', 'YiVLForCausalLM'])

[2025-01-21 10:12:04] Received sigquit from a child proces. It usually means the child failed.
Killed

# sglang version
pip list | grep sglang
sglang                            0.4.1.post7

**Comment by zhaochenyang20** [comment]
@JohnnyBoyzzz Please use the latest commits, not the lateset release.
