### ISSUE TITLE
 cannot import name 'build_regex_from_object' 

### ISSUE THREAD

**Issue by menkeyi001** [sgl-project/sglang#251]
conda create -n sglang_qwen python=3.10
pip install "sglang[all]" 

(sglang_qwen) root@admin:/data/models# python -m sglang.launch_server --model-path ./Qwen-72B-Chat-Int4 --port 30000
Traceback (most recent call last):
  File "/root/anaconda3/envs/sglang_qwen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/sglang_qwen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/anaconda3/envs/sglang_qwen/lib/python3.10/site-packages/sglang/launch_server.py", line 3, in <module>
    from sglang.srt.server import ServerArgs, launch_server
  File "/root/anaconda3/envs/sglang_qwen/lib/python3.10/site-packages/sglang/srt/server.py", line 25, in <module>
    from sglang.srt.constrained import disable_cache
  File "/root/anaconda3/envs/sglang_qwen/lib/python3.10/site-packages/sglang/srt/constrained/__init__.py", line 4, in <module>
    from outlines.fsm.json_schema import build_regex_from_object
ImportError: cannot import name 'build_regex_from_object' from 'outlines.fsm.json_schema' (/root/anaconda3/envs/sglang_qwen/lib/python3.10/site-packages/outlines/fsm/json_schema.py)

sglang_qwen) root@admin:/data/models# pip list|grep  sglang
sglang                    0.1.12

**Comment by comaniac** [comment]
This has been fixed in upstream but hasn't been released. You can try to install from source first to workaround this issue.

**Comment by isaac-vidas** [comment]
if you install from source, make sure you also downgrade vllm to `0.3.2` (`pip install vllm==0.3.2`) because latest vllm version `0.3.3` breaks sglang.
