### ISSUE TITLE
No module named 'vllm.transformers_utils.configs.qwen'

### ISSUE THREAD

**Issue by SimoneSartoni** [sgl-project/sglang#252]
After having successfully deployed some models using this DockerFile:

```
FROM python:3.11

# It's good practice to update pip to ensure we can handle recent package specifications
RUN pip install --upgrade pip

RUN pip install "sglang[all]==0.1.12" "outlines<=0.0.30"

# Expose port for the sglang service
EXPOSE 80

# Specify the command to run your sglang service
ENTRYPOINT ["python", "-m", "sglang.launch_server", "--model-path", "mistralai/Mistral-7B-Instruct-v0.2", "--port", "80", "--host", "0.0.0.0", "--chat-template", "chatml"]
```

When I replaced the model path with 'MaziyarPanahi/MoMo-72B-lora-1.8.7-DPO-GPTQ', I started getting this error:

```

(algo-llm-deploy) [ubuntu @ VERDELLM3 (Asterix) for small LLMs : algo-llm-deploy] docker compose logs sglang
sglang_service  | Use chat template: chatml
sglang_service  | Process Process-1:
sglang_service  | router init state: Traceback (most recent call last):
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/router/manager.py", line 68, in start_router_process
sglang_service  |     model_client = ModelRpcClient(server_args, port_args)
sglang_service  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/router/model_rpc.py", line 606, in __init__
sglang_service  |     self.model_server.exposed_init_model(0, server_args, port_args)
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/router/model_rpc.py", line 62, in exposed_init_model
sglang_service  |     self.model_runner = ModelRunner(
sglang_service  |                         ^^^^^^^^^^^^
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/router/model_runner.py", line 275, in __init__
sglang_service  |     self.load_model()
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/router/model_runner.py", line 284, in load_model
sglang_service  |     model_class = get_model_cls_by_arch_name(architectures)
sglang_service  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/router/model_runner.py", line 41, in get_model_cls_by_arch_name
sglang_service  |     model_arch_name_to_cls = import_model_classes()
sglang_service  |                              ^^^^^^^^^^^^^^^^^^^^^^
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/managers/router/model_runner.py", line 34, in import_model_classes
sglang_service  |     module = importlib.import_module(f"sglang.srt.models.{module_path.stem}")
sglang_service  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang_service  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
sglang_service  |     return _bootstrap._gcd_import(name[level:], package, level)
sglang_service  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sglang_service  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
sglang_service  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
sglang_service  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
sglang_service  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
sglang_service  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
sglang_service  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
sglang_service  |   File "/usr/local/lib/python3.11/site-packages/sglang/srt/models/qwen.py", line 28, in <module>
sglang_service  |     from vllm.transformers_utils.configs.qwen import QWenConfig
sglang_service  | ModuleNotFoundError: No module named 'vllm.transformers_utils.configs.qwen'
sglang_service  | 
sglang_service  | detoken init state: init ok

```

From that moment on, I have recreated the docker multiple times, switched the code back to 'mistralai/Mistral-7B-Instruct-v0.2', but keep getting the same error.

I can not understand how it is possible.

**Comment by mattproetsch** [comment]
Looks like vLLM removed qwen as a special case in v0.3.3, downgrade to `vllm==0.3.2` for now
https://github.com/vllm-project/vllm/pull/2637

`pip install vllm==0.3.2`

**Comment by SimoneSartoni** [comment]
Thank you! I feel stupid for not having found it in 2 hours :(

**Comment by fozziethebeat** [comment]
Can the dependency requirements be updated to address this? I also ran into this problem and had to look into what changed in vLLM.

**Comment by hnyls2002** [comment]
It will be updated soon, along with Google Gemma support.

**Comment by Qubitium** [comment]
Why is sglang importing Qwen when the model loading is not even Qwen to begin with? This is not ideal.
