### ISSUE TITLE
sglang for Qwen2.5-14b deploy Error

### ISSUE THREAD

**Issue by wuxianyess** [sgl-project/sglang#2520]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/sgl-workspace/sglang/python/sglang/launch_server.py", line 14, in <module>
    launch_server(server_args)
  File "/sgl-workspace/sglang/python/sglang/srt/server.py", line 526, in launch_server
    launch_engine(server_args=server_args)
  File "/sgl-workspace/sglang/python/sglang/srt/server.py", line 488, in launch_engine
    tokenizer_manager = TokenizerManager(server_args, port_args)
  File "/sgl-workspace/sglang/python/sglang/srt/managers/tokenizer_manager.py", line 109, in __init__
    self.model_config = ModelConfig(
  File "/sgl-workspace/sglang/python/sglang/srt/configs/model_config.py", line 93, in __init__
    self.hf_text_config.hidden_size // self.hf_text_config.num_attention_heads,
  File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 210, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'InternVLChatConfig' object has no attribute 'hidden_size'

**Comment by wuxianyess** [comment]
Can sglang support internvl model?

**Comment by VanshRana12** [comment]
any update on this?

**Comment by happened** [comment]
same error
