### ISSUE TITLE
[Bug] `Qwen/QwQ-32B-Preview` undefined symbol error

### ISSUE THREAD

**Issue by HuanzhiMao** [sgl-project/sglang#2539]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

```
$ python -m sglang.launch_server --model-path Qwen/QwQ-32B-Preview 
2024-12-21 13:11:42.425868: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-12-21 13:11:42.443184: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1734786702.465802    2843 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1734786702.472602    2843 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-12-21 13:11:42.494050: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX512F AVX512_VNNI AVX512_BF16 AVX512_FP16 AVX_VNNI, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
WARNING 12-21 13:11:44 _custom_ops.py:20] Failed to import from vllm._C with ImportError('/home/ubuntu/.local/lib/python3.10/site-packages/vllm/_C.abi3.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSsb')
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/launch_server.py", line 5, in <module>
    from sglang.srt.server import launch_server
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/server.py", line 46, in <module>
    from sglang.srt.managers.data_parallel_controller import (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/managers/data_parallel_controller.py", line 27, in <module>
    from sglang.srt.managers.scheduler import run_scheduler_process
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/managers/scheduler.py", line 63, in <module>
    from sglang.srt.managers.tp_worker import TpModelWorker
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 25, in <module>
    from sglang.srt.model_executor.model_runner import ModelRunner
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 42, in <module>
    from sglang.srt.layers.attention.flashinfer_backend import FlashInferAttnBackend
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/srt/layers/attention/flashinfer_backend.py", line 28, in <module>
    from flashinfer import (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/__init__.py", line 17, in <module>
    from .activation import gelu_and_mul, gelu_tanh_and_mul, silu_and_mul
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/activation.py", line 32, in <module>
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/activation.py", line 23, in <module>
    from . import _kernels
ImportError: /home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/_kernels.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs
```

### Reproduction

`python -m sglang.launch_server --model-path Qwen/QwQ-32B-Preview `

### Environment

```
$ python3 -m sglang.check_env
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/check_env.py", line 213, in <module>
    check_env()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/check_env.py", line 195, in check_env
    env_info.update(get_package_versions(PACKAGE_LIST))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/sglang/check_env.py", line 54, in get_package_versions
    module = importlib.import_module(package_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/__init__.py", line 17, in <module>
    from .activation import gelu_and_mul, gelu_tanh_and_mul, silu_and_mul
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/activation.py", line 32, in <module>
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/activation.py", line 23, in <module>
    from . import _kernels
ImportError: /home/ubuntu/.local/lib/python3.10/site-packages/flashinfer/_kernels.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs
```

**Comment by zhyncs** [comment]
```
pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/ --force-reinstall
```
