### ISSUE TITLE
ModuleNotFoundError: No module named 'jsonschema.protocols'

### ISSUE THREAD

**Issue by Chenghao-Jia** [sgl-project/sglang#254]
when I execute this bash to  launch a server, the terimal will tell me this error.
`python -m sglang.launch_server --model-path model/1-grade/Qwen1.5-0.5B-Chat/ --port 30000` 
```
Traceback (most recent call last):
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/launch_server.py", line 3, in <module>
    from sglang.srt.server import ServerArgs, launch_server
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/server.py", line 25, in <module>
    from sglang.srt.constrained import disable_cache
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/constrained/__init__.py", line 1, in <module>
    from outlines.caching import cache as disk_cache
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/site-packages/outlines/__init__.py", line 2, in <module>
    import outlines.generate
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/site-packages/outlines/generate/__init__.py", line 6, in <module>
    from .json import json
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/site-packages/outlines/generate/json.py", line 7, in <module>
    from outlines.fsm.json_schema import build_regex_from_schema, get_schema_from_signature
  File "/home/chenghao/miniconda3/envs/sglang/lib/python3.10/site-packages/outlines/fsm/json_schema.py", line 6, in <module>
    from jsonschema.protocols import Validator
ModuleNotFoundError: No module named 'jsonschema.protocols'
```

**Comment by Chenghao-Jia** [comment]
I have used `pip install -U 'jsonschema<4.0'`,but the problem also exit.

**Comment by hnyls2002** [comment]
@Chenghao-Jia  The local `jsonschema` version I used is `4.21.1`, could you please try it again?
