### ISSUE TITLE
[Bug] Outlines version error for Grammar Backend

### ISSUE THREAD

**Issue by zhaochenyang20** [sgl-project/sglang#2550]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

Running SGLang latest version and outlines latest version:

```bash
ImportError: cannot import name 'build_regex_from_schema' from 'outlines.fsm.json_schema' (/opt/dlami/nvme/chenyang/miniconda3/envs/sglang/lib/python3.11/site-packages/outlines/fsm/json_schema.py)
```

I think it's just naming error. So I set this as a good-first-issue.

### Reproduction

Easy to reproduce.

### Environment

Easy to reproduce.

**Comment by zhaochenyang20** [comment]
Related to https://github.com/sgl-project/sglang/issues/2549 and https://github.com/sgl-project/sglang/pull/2292.

**Comment by shuaills** [comment]
This might be related to the dependency conflict between `vllm` and `sglang`. `sglang` needs `torch 2.4`, but newer `vllm` versions require `torch 2.5`, which could be causing issues with `outlines`.

**Comment by zhaochenyang20** [comment]
> This might be related to the dependency conflict between `vllm` and `sglang`. `sglang` needs `torch 2.4`, but newer `vllm` versions require `torch 2.5`, which could be causing issues with `outlines`.

Specifically, SGLang 0.4 now depends on torch 2.4. vllm 0.6.5 and 0.6.4 depend on torch 2.5. And vllm 0.6.5 depends on outlines 0.1.11, but openrlhf depends on vllm 0.6.5. So we give up on supporting them comparatively right now.

**Comment by gobraves** [comment]
There’s an issue regarding the removal of vllm #2245 . Do we have any plans to continue working on this task?

**Comment by zhaochenyang20** [comment]
> There’s an issue regarding the removal of vllm #2245 . Do we have any plans to continue working on this task?

Yeah. @zhyncs and Yi Zhang are continue working on this.

**Comment by swamymushini** [comment]
@zhaochenyang20 can you please confirm what are the the requirements of torch, vllm, other versions to install sglang..

i tried what ever is present in the website 
pip install --upgrade pip
pip install sgl-kernel --force-reinstall --no-deps
pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer/

but getting error 
Collecting xformers==0.0.28.post3 (from vllm==0.6.4.post1->sglang[all])
  Using cached xformers-0.0.28.post3.tar.gz (7.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_owd1541/xformers_624ea054603a4878bd5ab3155d1d4544/setup.py", line 24, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


My python version is 3.11 and cuda version is 12.1

**Comment by zhaochenyang20** [comment]
```bash
Name: torch
Version: 2.5.1+cu121

Name: sglang
Version: 0.4.2

Name: vllm
Version: 0.6.4.post1
```

@swamymushini Here you are
