### ISSUE TITLE
upgrade setuptools and wheel if you found "torch module not found" when installing

### ISSUE THREAD

**Issue by MiladInk** [sgl-project/sglang#2554]
I encountered an issue while installing `sglang`. After upgrading pip (`pip install --upgrade pip`), I ran:

```bash
pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/
```

But it failed with the error:  
`ModuleNotFoundError: No module named 'torch'`.

I found on the Flash Attention GitHub that running this solved the issue:  
```bash
python -m pip install --upgrade pip wheel setuptools
```

It worked for me, so sharing in case someone faces the same problem! I don't know what the exact reason is though as the error itself was pretty strange.

**Comment by zhaochenyang20** [comment]
Thanks. We think this may related to the version conflicts between torch, sglang and vllm. @zhyncs

**Comment by swamymushini** [comment]
@MiladInk 

Collecting torchvision==0.20.1 (from vllm==0.6.4.post1->sglang[all])
  Using cached torchvision-0.20.1-cp311-cp311-manylinux1_x86_64.whl.metadata (6.1 kB)
Collecting xformers==0.0.28.post3 (from vllm==0.6.4.post1->sglang[all])
  Using cached xformers-0.0.28.post3.tar.gz (7.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-_owd1541/xformers_624ea054603a4878bd5ab3155d1d4544/setup.py", line 24, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


I'm still facing the same issue.. i tried pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/
and python -m pip install --upgrade pip wheel setuptools
 as well

**Comment by zhaochenyang20** [comment]
This is an installation error. I think I can give it to simon @simveit . Could you help on this? Thanks!

**Comment by simveit** [comment]
Hello @swamymushini ,
I think you have some of your dependencies wrong. Using a fresh virtual environment I was not able to produce your issue.
Please try out the following and let me know if it worked 
```bash
# Install uv following one of the methods from 
# https://docs.astral.sh/uv/getting-started/installation/

# Install python version
uv python install 3.12

# Create fresh virtual environment
uv venv --python 3.12 # Create virtual environment

# Installation from sglang docs
uv pip install --upgrade pip 
uv pip install sgl-kernel --force-reinstall --no-deps
uv pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/

# Use the venv
source .venv/bin/activate

# Sanity check
python -c "import sglang; print(sglang.__version__)"
```
Of course you may use other ways than uv but I recommend it because it is very fast.

**Comment by swamymushini** [comment]
@simveit im still facing the same issues

 uv pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/
Using Python 3.10.14 environment at: /opt/conda
Resolved 139 packages in 1.31s
  × Failed to build `xformers==0.0.28.post3`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
      ModuleNotFoundError: No module named 'torch'

      hint: This error likely indicates that `xformers@0.0.28.post3` depends on `torch`, but doesn't declare it as a build dependency. If `xformers` is a first-party package, consider
      adding `torch` to its `build-system.requires`. Otherwise, `uv pip install torch` into the environment and re-run with `--no-build-isolation`.
  help: `xformers` (v0.0.28.post3) was included because `sglang[all]` (v0.3.6) depends on `vllm` (v0.6.4.post1) which depends on `xformers`
(base) [ec2-user@ip-mask ~]$ pip install `xformers==0.0.28.post3
> ^C
(base) [ec2-user@ip-mask ~]$ pip install xformers==0.0.28.post3
Collecting xformers==0.0.28.post3
  Using cached xformers-0.0.28.post3.tar.gz (7.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vswvel_y/xformers_bca5757754574b17936fa6a765e08c9b/setup.py", line 24, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.




can you please help..I'm using amazon linux EC2 VM 

even if I try to install xformers directly with  pip install xformers==0.0.28.post3
getting below issues
 /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/C++17.h:13:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 9 or later."
       #error \
        ^~~~~
      In file included from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:11:0,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/Context.h:4,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                       from xformers/csrc/attention/attention.cpp:8:

  error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)
(ec2-user) (base) [ec2-user@ip-10-192-136-144 ~]$ pip list | grep -E "torch|xformers"
pytorch-triton-rocm      2.1.0
torch                    2.4.0+cu121
xformers                 0.0.27.post2

**Comment by swamymushini** [comment]
@simveit im still facing the same issues

 uv pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/
Using Python 3.10.14 environment at: /opt/conda
Resolved 139 packages in 1.31s
  × Failed to build `xformers==0.0.28.post3`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stderr]
      Traceback (most recent call last):
        File "<string>", line 14, in <module>
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/home/ec2-user/.cache/uv/builds-v0/.tmpJYsG5k/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 24, in <module>
      ModuleNotFoundError: No module named 'torch'

      hint: This error likely indicates that `xformers@0.0.28.post3` depends on `torch`, but doesn't declare it as a build dependency. If `xformers` is a first-party package, consider
      adding `torch` to its `build-system.requires`. Otherwise, `uv pip install torch` into the environment and re-run with `--no-build-isolation`.
  help: `xformers` (v0.0.28.post3) was included because `sglang[all]` (v0.3.6) depends on `vllm` (v0.6.4.post1) which depends on `xformers`
(base) [ec2-user@ip-mask ~]$ pip install `xformers==0.0.28.post3
> ^C
(base) [ec2-user@ip-mask ~]$ pip install xformers==0.0.28.post3
Collecting xformers==0.0.28.post3
  Using cached xformers-0.0.28.post3.tar.gz (7.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vswvel_y/xformers_bca5757754574b17936fa6a765e08c9b/setup.py", line 24, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.




can you please help..I'm using amazon linux EC2 VM 

even if I try to install xformers directly with  pip install xformers==0.0.28.post3
getting below issues
 /opt/conda/lib/python3.10/site-packages/torch/include/c10/util/C++17.h:13:2: error: #error "You're trying to build PyTorch with a too old version of GCC. We need GCC 9 or later."
       #error \
        ^~~~~
      In file included from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/core/Generator.h:11:0,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/CPUGeneratorImpl.h:3,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/Context.h:4,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/ATen/ATen.h:7,
                       from /opt/conda/lib/python3.10/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                       from xformers/csrc/attention/attention.cpp:8:

  error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Failed to build xformers
ERROR: Failed to build installable wheels for some pyproject.toml based projects (xformers)
(ec2-user) (base) [ip-mask ~]$ pip list | grep -E "torch|xformers"
pytorch-triton-rocm      2.1.0
torch                    2.4.0+cu121
xformers                 0.0.27.post2

**Comment by simveit** [comment]
From the output you posted here the problem might be related to the fact that you have conda installed and [uv will install the packages into there if the venv is not activated before pip installing](https://docs.astral.sh/uv/pip/environments/#discovery-of-python-environments).

Please try 

```bash
# Install uv following one of the methods from 
# https://docs.astral.sh/uv/getting-started/installation/

# Install python version
uv python install 3.12

# Create fresh virtual environment
uv venv --python 3.12 # Create virtual environment

# Use the venv
source .venv/bin/activate

# Installation from sglang docs
uv pip install --upgrade pip 
uv pip install sgl-kernel --force-reinstall --no-deps
uv pip install "sglang[all]" --find-links https://flashinfer.ai/whl/cu121/torch2.4/flashinfer/

# Sanity check
python -c "import sglang; print(sglang.__version__)"
```

There seems to be also issue that there are multiple versions of torch installed and also an issue with gcc which you might need to fix. Please make sure that after doing `source .venv/bin/activate` `which python` points to the virtual environment and not to conda.
Alternatively you might try to create a fresh conda environment and pip install there.

**Comment by zhaochenyang20** [comment]
Great reply. Thanks so much. In my sense, I think we can modify the installation docs. @simveit
