### ISSUE TITLE
[Feature] DeepSeek V3 optimization

### ISSUE THREAD

**Issue by zhyncs** [sgl-project/sglang#2591]
### Checklist

- [ ] 1. If the issue you raised is not a feature but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 2. Please use English, otherwise it will be closed.

### Adoption

[SGLang adoption for DeepSeek V3 and R1](https://github.com/sgl-project/sglang/discussions/3322)

### Usage

User Guide for Existing System (Installation & Launch)

https://github.com/sgl-project/sglang/tree/main/benchmark/deepseek_v3

Please use the latest version [v0.4.2.post4](https://pypi.org/project/sglang/0.4.2.post4/). Please prefer to use docker image. `docker pull lmsysorg/sglang:latest`

For running on AMD MI300X, use this as a reference. [Running DeepSeek-R1 on a single NDv5 MI300X VM](https://techcommunity.microsoft.com/blog/azurehighperformancecomputingblog/running-deepseek-r1-on-a-single-ndv5-mi300x-vm/4372726)

### Features

- [x] Support CUDA Graph @HandH1998 @ispobock 
- [x] Support Torch compile @ispobock 
- [x] Use BF16 for bmm @zhyncs 
- [x] Improve the accuracy for FP8 @HandH1998 @zhyncs @ispobock 
- [x] Tuning FP8 GEMM @HandH1998 @zhyncs 
- [x] Replace `moe_align_block_size` @HandH1998 @zhyncs @BBuf 
- [x] FusedMoE tuning for H200 `E=256,N=256,device_name=NVIDIA_H200,dtype=fp8_w8a8.json` @BBuf 
- [x] TP+DP Attention @Ying1123 
- [x] Support overlap scheduler with DP attention @merrymercy
- [x] Fuse Sigmoid Gate  [moe_kernels.cu](https://github.com/NVIDIA/TensorRT-LLM/blob/main/cpp/tensorrt_llm/kernels/mixtureOfExperts/moe_kernels.cu) @NovTi @BBuf (torch compile is sufficient for this use case, so the priority and ROI to support it are not high. Closing for now.)
- [x] Support `nextn` speculative decoding @ispobock  https://github.com/sgl-project/sglang/issues/3472
- [x] FP8 GEMM CUTLASS implementation @yizhang2077 
- [x] Better [fused_experts](https://github.com/sgl-project/sglang/blob/34e405e01f7ff15ad56399999b9c00859a0b5134/python/sglang/srt/layers/moe/fused_moe_triton/fused_moe.py#L1123) @bbuf @zhyncs 
- [x] FlashInfer Prefill and MLA Decoding @zhyncs @ispobock 
- [x] Integrate DeepGemm #4199 #4343
- [x] Integrate FlashMLA #4472 #4514 
- [ ] FP8 GEMM Composable Kernel implementation @HaiShaw 
- [ ] Support Pipeline Parallelism @Ying1123  

More things (e.g., PD disaggregation, cache) are tracked at https://github.com/sgl-project/sglang/issues/4042

**Comment by libratiger** [comment]
Very quick response !
I understand that the overlap scheduler is model-independent and is a general optimization that should be supported by default. 
At least some special optimizations are needed?

**Comment by merrymercy** [comment]
The overlap scheduler is model-independent but has not been supported when using dp attention. We have a private branch for this and will upstream it soon.

**Comment by Qubitium** [comment]
Wow. @zhyncs Can you confirm deepseek v3 is only runnable on FP8 capable hardware such as H100+?

**Comment by fengyang95** [comment]
Is the memory sufficient for an 8 gpus instance? This model size is too large.

**Comment by zhyncs** [comment]
> Is the memory sufficient for an 8 gpus instance? This model size is too large.

671B works on H200 * 8 with FP8 (671 < 141 * 8)

**Comment by zhyncs** [comment]
Hi @fengyang95 You can also consider multi node.
> If you do not have GPUs with large enough memory, please try multi-node tensor parallelism ([help 1](https://github.com/sgl-project/sglang/blob/637de9e8ce91fd3e92755eb2a842860925954ab1/docs/backend/backend.md?plain=1#L88-L95) [help 2](https://github.com/sgl-project/sglang/blob/637de9e8ce91fd3e92755eb2a842860925954ab1/docs/backend/backend.md?plain=1#L152-L168)).

**Comment by zhyncs** [comment]
FYI Due to the tight schedule, SGLang v0.4.1 currently only provides preliminary support for DeepSeek V3. To make it run more cost-efficiently, we need to complete most of the optimizations mentioned above. If you are interested in any of the above optimizations, feel free to join the [SGLang Slack](https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2rtikx2pv-DUfPrhx2SaNAq~47YtV1XQ) for discussions or contribute a PR. We hope to complete these optimizations quickly and appreciate any discussion and contributions.

**Comment by zhyncs** [comment]
Update: SGLang v0.4.1.post1 supports CUDA Graph for DeepSeek V3, please use the latest version.
```bash
pip install "sglang[all]==0.4.1.post1" --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer
```

**Comment by zhyncs** [comment]
Update: SGLang v0.4.1.post2 supports FP8 GEMM Tuning for DeepSeek V3, please use the latest version.

```
pip install "sglang[all]==0.4.1.post2" --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer
```

**Comment by Lzhang-hub** [comment]
> Update: SGLang v0.4.1.post1 supports CUDA Graph for DeepSeek V3, please use the latest version.
> 
> ```shell
> pip install "sglang[all]==0.4.1.post1" --find-links https://flashinfer.ai/whl/cu124/torch2.4/flashinfer
> ```

CUDA Graph support multi node? I updated latest version, inference with two H20*8 node, It hang when capture cuda graph.

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/pull/2647

**Comment by CSEEduanyu** [comment]
plan to support mtp?

**Comment by zhyncs** [comment]
> plan to support mtp?

It's on the roadmap and it's named `nextn`. We'll support it soon.

**Comment by pipul** [comment]
从知乎帖子跟过来 https://zhuanlan.zhihu.com/p/714761319
请教个问题

@zhyncs

非常有意思的文章，我们大概在一个月前，在 SGLang 中实现了你文中提到的 A_CC_ME 版本 [如何看待 DeepSeek 发布的 MoE 大模型 DeepSeek-V2？](https://www.zhihu.com/question/655172528/answer/3584052758)

以及做了 MQA 的优化 [Optimize MLA/GQA/MQA Triton decoding by ispobock · Pull Request #1138 · sgl-project/sglang](http://link.zhihu.com/?target=https%3A//github.com/sgl-project/sglang/pull/1138)
事实上你提到的结论「MLA 由于是 Compressed_KV， 只有一个 Head，相当于 MQA，因此没办法再继续划分，每个 Rank 各自保留一份完整的 Compressed_KV」和我们的结论是一致的。DeepSeek 内部的实现，如果有一个 KV Cache Memory Pool 或许可以解决这个问题，TP 8 时，就不用每张卡都重复存一份了[酷]

@pika-jy qkv proj 的TP 已经是完整Dim（Dim = Head * Head_Dim）上分了，和mlp一样，attn 计算 head_dim上再分没必要了吧？这一维度本来就很小了，128，又额外引入通信

我的问题是：
如果qkv是完整的DIM上分TP了，那计算attention的时候，每个TP算各自的qkv，最后再做softmax不行么？跟传统的attention计算一样
算attention的时候，汇聚所有TP的qk结果（只需要qk结果，不需要传输kv），再做softmax
没太理解这个地方为啥不行。

**Comment by llllllooooox** [comment]
@zhyncs @Ying1123 @merrymercy ,hello, 
As you mentioned above, TP+DP,

> TP+DP Attention @Ying1123

I have two questions, could you help me answer them?

1.Can we decouple TP and DP after this implementation? Can we configure the scenario where DP is not equal to TP?

2.Is there a detailed schedule for the mentioned above? Are there any related supporting design documents that can be shared?

**Comment by mutinifni** [comment]
I had another question regarding DP attention. The [sglang blog](https://lmsys.org/blog/2024-12-04-sglang-v0-4/#data-parallelism-attention-for-deepseek-models) mentions that DP attention is effective because of the MLA has only 1 KV head, which causes unnecessary duplication of KV caches.  DeepSeek-V3 MLA has more KV heads (16 attention, 128 KV), so do we still replicate KV caches if just using something like TP8 or TP16? I understand there might not be sufficient heads if the deployment is large. 

+1 for shared design docs, if possible.

**Comment by pipul** [comment]
> I had another question regarding DP attention. The [sglang blog](https://lmsys.org/blog/2024-12-04-sglang-v0-4/#data-parallelism-attention-for-deepseek-models) mentions that DP attention is effective because of the MLA has only 1 KV head, which causes unnecessary duplication of KV caches. DeepSeek-V3 MLA has more KV heads (16 attention, 128 KV), so do we still replicate KV caches if just using something like TP8 or TP16? I understand there might not be sufficient heads if the deployment is large.
> 
> +1 for shared design docs, if possible.

@zhyncs @Mutinifni 

https://huggingface.co/deepseek-ai/DeepSeek-V3/blob/main/config.json
"num_key_value_heads": 128,
DeepSeek-V3  has 128 KV heads??

**Comment by min-xu-et** [comment]
Are there any data related to inference time batch size and token imbalance between experts? What's the total throughput like for a 8xH200 node?

**Comment by CSEEduanyu** [comment]
Has there been any progress with the support from NextN?

**Comment by lambert0312** [comment]
The overlap scheduler with DP attention can not be used on A800 * 4., because always OOM.

**Comment by MtFitzRoy** [comment]
Is there a plan to support TP + SP attention?

The paper says "The attention part employs 4-way Tensor Parallelism (TP4) with Sequence Parallelism (SP)"

**Comment by wa2lina** [comment]
Can you support deepseek R1 Q4KM GGUF file，https://huggingface.co/unsloth/DeepSeek-R1-GGUF

**Comment by Xu-Chen** [comment]
Any process about nextn speculative decoding?

**Comment by NoCodre** [comment]
Everything I don't do results in an error: with another framework, the model loads fine. With this framework, other models also load successfully. I tried changing the parameters in various ways with no result, tested on different graphics cards, and with different amounts of video memory.

# python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-V3 --tp 1 --trust-remote-code 
[2025-01-29 06:46:29] server_args=ServerArgs(model_path='deepseek-ai/DeepSeek-V3', tokenizer_path='deepseek-ai/DeepSeek-V3', tokenizer_mode='auto', load_format='auto', trust_remote_code=True, dtype='auto', kv_cache_dtype='auto', quantization_param_path=None, quantization=None, context_length=None, device='cuda', served_model_name='deepseek-ai/DeepSeek-V3', chat_template=None, is_embedding=False, revision=None, skip_tokenizer_init=False, host='127.0.0.1', port=30000, mem_fraction_static=0.88, max_running_requests=None, max_total_tokens=None, chunked_prefill_size=2048, max_prefill_tokens=16384, schedule_policy='lpm', schedule_conservativeness=1.0, cpu_offload_gb=0, prefill_only_one_req=False, tp_size=1, stream_interval=1, stream_output=False, random_seed=364073524, constrained_json_whitespace_pattern=None, watchdog_timeout=300, download_dir=None, base_gpu_id=0, log_level='info', log_level_http=None, log_requests=False, show_time_cost=False, enable_metrics=False, decode_log_interval=40, api_key=None, file_storage_pth='sglang_storage', enable_cache_report=False, dp_size=1, load_balance_method='round_robin', ep_size=1, dist_init_addr=None, nnodes=1, node_rank=0, json_model_override_args='{}', lora_paths=None, max_loras_per_batch=8, attention_backend='flashinfer', sampling_backend='flashinfer', grammar_backend='outlines', speculative_draft_model_path=None, speculative_algorithm=None, speculative_num_steps=5, speculative_num_draft_tokens=64, speculative_eagle_topk=8, enable_double_sparsity=False, ds_channel_config_path=None, ds_heavy_channel_num=32, ds_heavy_token_num=256, ds_heavy_channel_type='qk', ds_sparse_decode_threshold=4096, disable_radix_cache=False, disable_jump_forward=False, disable_cuda_graph=False, disable_cuda_graph_padding=False, disable_outlines_disk_cache=False, disable_custom_all_reduce=False, disable_mla=False, disable_overlap_schedule=False, enable_mixed_chunk=False, enable_dp_attention=False, enable_ep_moe=False, enable_torch_compile=False, torch_compile_max_bs=32, cuda_graph_max_bs=8, cuda_graph_bs=None, torchao_config='', enable_nan_detection=False, enable_p2p_check=False, triton_attention_reduce_in_fp32=False, triton_attention_num_kv_splits=8, num_continuous_decode_steps=1, delete_ckpt_after_loading=False, enable_memory_saver=False, allow_auto_truncate=False, enable_custom_logit_processor=False, tool_call_parser=None)
[2025-01-29 06:46:42 TP0] MLA optimization is turned on. Use triton backend.
[2025-01-29 06:46:42 TP0] Init torch distributed begin.
[2025-01-29 06:46:42 TP0] Load weight begin. avail mem=11.30 GB
[2025-01-29 06:46:42 TP0] Detected fp8 checkpoint. Please note that the format is experimental and subject to change.
Cache shape torch.Size([163840, 64])
[2025-01-29 06:46:42 TP0] Scheduler hit an exception: Traceback (most recent call last):
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 1773, in run_scheduler_process
    scheduler = Scheduler(server_args, port_args, gpu_id, tp_rank, dp_rank)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/scheduler.py", line 239, in __init__
    self.tp_worker = TpWorkerClass(
                     ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tp_worker_overlap_thread.py", line 63, in __init__
    self.worker = TpModelWorker(server_args, gpu_id, tp_rank, dp_rank, nccl_port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/managers/tp_worker.py", line 68, in __init__
    self.model_runner = ModelRunner(
                        ^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/model_executor/model_runner.py", line 185, in __init__
    self.load_model()
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/model_executor/model_runner.py", line 306, in load_model
    self.model = get_model(
                 ^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/model_loader/__init__.py", line 22, in get_model
    return loader.load_model(
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/model_loader/loader.py", line 357, in load_model
    model = _initialize_model(
            ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/model_loader/loader.py", line 138, in _initialize_model
    return model_class(
           ^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/models/deepseek_v2.py", line 837, in __init__
    self.model = DeepseekV2Model(config, quant_config)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/models/deepseek_v2.py", line 799, in __init__
    DeepseekV2DecoderLayer(
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/models/deepseek_v2.py", line 729, in __init__
    self.mlp = DeepseekV2MoE(config=config, quant_config=quant_config)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/models/deepseek_v2.py", line 146, in __init__
    self.experts = MoEImpl(
                   ^^^^^^^^
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/layers/moe/fused_moe_triton/layer.py", line 299, in __init__
    self.quant_method.create_weights(
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/sglang/srt/layers/quantization/fp8.py", line 487, in create_weights
    torch.empty(
  File "/root/miniconda3/envs/sglang/lib/python3.12/site-packages/torch/utils/_device.py", line 106, in __torch_function__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.50 GiB. GPU 0 has a total capacity of 11.81 GiB of which 694.25 MiB is free. Including non-PyTorch memory, this process has 10.87 GiB memory in use. Of the allocated memory 10.55 GiB is allocated by PyTorch, and 16.01 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

[2025-01-29 06:46:42] Received sigquit from a child proces. It usually means the child failed.
Killed

**Comment by Neo9061** [comment]
Hi @ispobock, wonder if you have any timeline to share `nextn` (speculative decoding) will be supported? thanks

**Comment by ispobock** [comment]
We have finished spec module refactor and will support `nextn` in the next 1~2 weeks.

**Comment by Neo9061** [comment]
> We have finished spec module refactor and will support `nextn` in the next 1~2 weeks.

Thanks! I wonder if your implementation will include any mechanism to generate the acceptance rates of the MTP head?

**Comment by lambert0312** [comment]
[DeepSeek MTP spec decode #12755](https://github.com/vllm-project/vllm/pull/12755) is Implement DeepSeek MTP: https://github.com/vllm-project/vllm/issues/12181 to support DeepSeek MTP layers for next n prediction.

**Comment by yukavio** [comment]
Does sglang now support deepseekv3 inference with EP>1? When I added --enable-ep-moe to the command to start the service, I found that the process would hang. I'm not sure if this is a problem caused by my environment or if this feature is not currently supported.

**Comment by jianglan89** [comment]
> Does sglang now support deepseekv3 inference with EP>1? When I added --enable-ep-moe to the command to start the service, I found that the process would hang. I'm not sure if this is a problem caused by my environment or if this feature is not currently supported.

Me too, it seems not support ep-moe in 0.4.2

**Comment by BBuf** [comment]
Need help [here](https://github.com/sgl-project/sglang/issues/3339), If you are familiar with CUDA optimization and have ideas about this issue, feel free to contact me.

**Comment by 01lin** [comment]
When will mtp(nextn speculative decoding) be supported?

**Comment by lambert0312** [comment]
This is https://github.com/CentML's implementation of DeepSeek MTP modules that enable speculative decoding for DeepSeek-R1. https://github.com/vllm-project/vllm/pull/12915

**Comment by ltm920716** [comment]
hi,
I  am new to sglang，and I need help about deploying deepseek on two nodes：
https://github.com/sgl-project/sglang/tree/main/benchmark/deepseek_v3#example-serving-with-two-h2008-nodes-and-docker

I have two H100 nodes，what is the best setting at parameters  for the throughout？

thanks

**Comment by groklab** [comment]
Dear All - is it normal to have 3 hours waiting time on `loading safetensors checkpoint shards`?

![Image](https://github.com/user-attachments/assets/22dfa9b2-ffa6-44ca-ad90-c325338627de)

4 nodes and each node has 4 H100.  Not using docker.

Thanks.

**Comment by zhyncs** [comment]
FYI You can check out the latest progress of DeepSeek V3/R1 nextn here. https://github.com/sgl-project/sglang/issues/3472
I believe the majority of the difficult tasks have been completed recently, and we will be launching this feature in the coming days. Please stay tuned.

**Comment by iammeizu** [comment]
I deploy deepseek-v3 on 8 * h20 cards using sglang latest version ，the model serving run success, but output text was a mess，like 
  “勞經於In學éToTheText》\n檢 we would“ like,畢竟以\n\n it\n\n馬國in les un, Un\n\n transitive.black!\n\n.\n\n 這in,Definitionive had-t E ,andopo en min,,\n 1R:ik\n\n Écrit ***\n\n 立方 ** ce ** duue ** m **  duidge \n, . en leé onlayeropo ** **主 etDE ** mitgr **-: (**了** due-ui ** DE ( ** permission theRE,Task**IN P**DE \n\n Client é,dule En Info MIN WEB，ZA}\n\n** LeUseKK,…\n\n\n\nBLnéSO estONOtherlate ** Cl缶 r- traditional-- Establishmentrée耶 **-**  ù parLE:** =DRval N queyreatek ** B\n\n ** un est être Un liqu** (Ô le �- ** Mine est-mer Merr** AN2 In être processed $Break ** GA  IN**-info,ANNі Gö”

what should i do ? （no error log was found） @zhyncs

**Comment by iammeizu** [comment]
I also tried vllm to run both deepseek-v3 and r1 on h20s，the output text was similar，how to debug this problem？

**Comment by zhyncs** [comment]
> I deploy deepseek-v3 on 8 * h20 cards using sglang latest version ，the model serving run success, but output text was a mess，like “勞經於In學éToTheText》\n檢 we would“ like,畢竟以\n\n it\n\n馬國in les un, Un\n\n transitive.black!\n\n.\n\n 這in,Definitionive had-t E ,andopo en min,,\n 1R:ik\n\n Écrit _**\n\n 立方 ** ce ** duue ** m ** duidge \n, . en leé onlayeropo ** 主 etDE ** mitgr -: (了 due-ui ** DE ( ** permission theRE,TaskIN PDE \n\n Client é,dule En Info MIN WEB，ZA}\n\n** LeUseKK,…\n\n\n\nBLnéSO estONOtherlate ** Cl缶 r- traditional-- Establishmentrée耶 **-** ù parLE:_* =DRval N queyreatek ** B\n\n ** un est être Un liqu** (Ô le �- ** Mine est-mer Merr** AN2 In être processed $Break ** GA IN**-info,ANNі Gö”
> 
> what should i do ? （no error log was found） [@zhyncs](https://github.com/zhyncs)

@iammeizu You should raise an issue separately. https://github.com/sgl-project/sglang/issues/new?template=1-bug-report.yml

**Comment by FlamingoPg** [comment]
> I also tried vllm to run both deepseek-v3 and r1 on h20s，the output text was similar，how to debug this problem？

I run deepseek-v3 with 8 * H20, it works well. @iammeizu 

![Image](https://github.com/user-attachments/assets/7476a9b8-75f2-4794-89d1-df26d5e8fa6c)

**Comment by FlamingoPg** [comment]
I also test gsm8k and mmlu, you can refer this issue https://github.com/sgl-project/sglang/issues/3486.

**Comment by iammeizu** [comment]
thks for reply，I solved this problem by check model file compeletion (some safetensor missing , but sglang or vllm don't report error ) @yinfan98 @zhyncs

**Comment by groklab** [comment]
Hi!

How can I deploy DeepSeek V3 on 4 nodes with 14 H100s?

The setup:

node 1
![image](https://github.com/user-attachments/assets/5f2981b0-09a3-4295-a521-1067354d51c0)

node 2
![image](https://github.com/user-attachments/assets/cb251086-e56e-4aac-9eea-33e06b9a28f4)

node 3
![image](https://github.com/user-attachments/assets/ab4e3b65-f47f-45f2-99e1-6ea4c3491e40)

node 4
![image](https://github.com/user-attachments/assets/9347a5fb-90e2-47c4-87cb-e29996b17bed)

---

My commands are:
```
# node 1
python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 0 --trust-remote-code --enable-torch-compile --host 0.0.0.0 --port 30000 --grammar-backend xgrammar

# node 2
python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 1 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar

# node 3
python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 2 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar

# node 4
python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 3 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar
```

Then got error: `AssertionError: tp_size must be divisible by number of nodes`

Is there a workaround?

**Comment by xixingya** [comment]
> Hi!
> 
> How can I deploy DeepSeek V3 on 4 nodes with 14 H100s?
> 
> The setup:
> 
> node 1 ![image](https://github.com/user-attachments/assets/5f2981b0-09a3-4295-a521-1067354d51c0)
> 
> node 2 ![image](https://github.com/user-attachments/assets/cb251086-e56e-4aac-9eea-33e06b9a28f4)
> 
> node 3 ![image](https://github.com/user-attachments/assets/ab4e3b65-f47f-45f2-99e1-6ea4c3491e40)
> 
> node 4 ![image](https://github.com/user-attachments/assets/9347a5fb-90e2-47c4-87cb-e29996b17bed)
> 
> My commands are:
> 
> ```
> # node 1
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 0 --trust-remote-code --enable-torch-compile --host 0.0.0.0 --port 30000 --grammar-backend xgrammar
> 
> # node 2
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 1 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar
> 
> # node 3
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 2 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar
> 
> # node 4
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 3 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar
> ```
> 
> Then got error: `AssertionError: tp_size must be divisible by number of nodes`
> 
> Is there a workaround?

> Hi!
> 
> How can I deploy DeepSeek V3 on 4 nodes with 14 H100s?
> 
> The setup:
> 
> node 1 ![image](https://github.com/user-attachments/assets/5f2981b0-09a3-4295-a521-1067354d51c0)
> 
> node 2 ![image](https://github.com/user-attachments/assets/cb251086-e56e-4aac-9eea-33e06b9a28f4)
> 
> node 3 ![image](https://github.com/user-attachments/assets/ab4e3b65-f47f-45f2-99e1-6ea4c3491e40)
> 
> node 4 ![image](https://github.com/user-attachments/assets/9347a5fb-90e2-47c4-87cb-e29996b17bed)
> 
> My commands are:
> 
> ```
> # node 1
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 0 --trust-remote-code --enable-torch-compile --host 0.0.0.0 --port 30000 --grammar-backend xgrammar
> 
> # node 2
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 1 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar
> 
> # node 3
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 2 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar
> 
> # node 4
> python3 -m sglang.launch_server --model-path /models/dsv3 --tp 14 --dist-init-addr 10.21.99.116:5000 --nnodes 4 --node-rank 3 --trust-remote-code --enable-torch-compile --grammar-backend xgrammar
> ```
> 
> Then got error: `AssertionError: tp_size must be divisible by number of nodes`
> 
> Is there a workaround?

"intermediate size":18432. 
quantization block n=128
18432/14 is not an integer, and it also needs to be satisfied that 18432/tp_size divided by 128 is an integer.

**Comment by zhyncs** [comment]
ref
MTP support: https://github.com/sgl-project/sglang/pull/3582
v0.4.3.post1 release: https://github.com/sgl-project/sglang/pull/3638

SGLang supports MTP (nextn) in the Triton backend, achieving a speed of 77 tokens/s, twice as fast as other OSS LLM engines.

**Comment by ShivamB25** [comment]
@zhyncs can you please recommed the command for long prompt (lots of queries) since we are working with large documents. we want to run our own. 
. system has 8 x mi300x , 2TB ram and dual amd process epyc 9654 (96cores). if that helps.
i am using this as of now
```
➜  ~ docker run -d \      
  --name sglang \
  --device=/dev/kfd \
  --device=/dev/dri \
  --security-opt seccomp=unconfined \
  --cap-add=SYS_PTRACE \
  --group-add video \
  --privileged \
  --shm-size 256g \
  --ipc=host \
  -p 3000:3000 \
  -v ~/.cache/huggingface:/root/.cache/huggingface \
  -e HSA_NO_SCRATCH_RECLAIM=1 \
  jesselopezmicrosoft/sglang:mi300x \
  python3 -m sglang.launch_server \
    --model unsloth/DeepSeek-R1 \
    --tp 8 \
    --trust-remote-code \
    --host 0.0.0.0 \
    --port 3000 \
    --enable-hierarchical-cache \
    --enable-cache-report \
    --chunked-prefill-size 8192 \
    --enable-metrics \
    --show-time-cost \
    --stream-output \
    --quantization fp8 \
    --attention-backend triton \
    --sampling-backend flashinfer \
    --grammar-backend xgrammar```

**Comment by xutizhou** [comment]
@zhyncs Is there any plan for optimizing the FP8 GEMM kernel? Recently, I’ve been working on some optimizations for DeepSeekV3 and achieved promising results. I’d love to contribute to the community if possible. Let me know how I can help!

**Comment by YangQun1** [comment]
@zhyncs Is there any plan to support ep moe for deepseek-v3/r1? there are related issues: https://github.com/sgl-project/sglang/issues/3371
Ok, I find the feature issue. https://github.com/sgl-project/sglang/issues/2740

**Comment by zhyncs** [comment]
> [@zhyncs](https://github.com/zhyncs) Is there any plan for optimizing the FP8 GEMM kernel? Recently, I’ve been working on some optimizations for DeepSeekV3 and achieved promising results. I’d love to contribute to the community if possible. Let me know how I can help!

@xutizhou sgl-kernel already supports the CUTLASS block wise fp8 https://github.com/sgl-project/sglang/blob/main/sgl-kernel/src/sgl-kernel/csrc/fp8_blockwise_gemm_kernel.cu

Please join the slack channel https://slack.sglang.ai

**Comment by zhyncs** [comment]
> [@zhyncs](https://github.com/zhyncs) Is there any plan to support ep moe for deepseek-v3/r1? there are related issues: [#3371](https://github.com/sgl-project/sglang/issues/3371) Ok, I find the feature issue. [#2740](https://github.com/sgl-project/sglang/issues/2740)

ref https://github.com/sgl-project/sglang/pull/3602

**Comment by xutizhou** [comment]
> > [@zhyncs](https://github.com/zhyncs) Is there any plan for optimizing the FP8 GEMM kernel? Recently, I’ve been working on some optimizations for DeepSeekV3 and achieved promising results. I’d love to contribute to the community if possible. Let me know how I can help!
> 
> [@xutizhou](https://github.com/xutizhou) sgl-kernel already supports the CUTLASS block wise fp8 https://github.com/sgl-project/sglang/blob/main/sgl-kernel/src/sgl-kernel/csrc/fp8_blockwise_gemm_kernel.cu
> 
> Please join the slack channel https://slack.sglang.ai

Thank you for the reference provided.

**Comment by zqqQiu** [comment]
> thks for reply，I solved this problem by check model file compeletion (some safetensor missing , but sglang or vllm don't report error ) [@yinfan98](https://github.com/yinfan98) [@zhyncs](https://github.com/zhyncs)

Can you share the command on 8*h20?

**Comment by YangZeyu95** [comment]
Hi, is there any plan to support pipeline parallelism? As I don't have IB for connection between 2 servers, pp will be very helpful for performance

**Comment by tutu329** [comment]
> IB

the same problem

**Comment by tutu329** [comment]
> Hi, is there any plan to support pipeline parallelism? As I don't have IB for connection between 2 servers, pp will be very helpful for performance

the same problem

**Comment by groklab** [comment]
Hi SGLang Team - should we expect a smooth transition to deepseek v3 0324 checkpoint (without any changes) or do you need some backend changes before we can pull the 0324 weights?

https://huggingface.co/deepseek-ai/DeepSeek-V3-0324

**Comment by zhyncs** [comment]
> Hi SGLang Team - should we expect a smooth transition to deepseek v3 0324 checkpoint (without any changes) or do you need some backend changes before we can pull the 0324 weights?
> 
> https://huggingface.co/deepseek-ai/DeepSeek-V3-0324

Hi @groklab Thanks to let me know. I will upload the NextN weights for this new checkpoint.

**Comment by parambole** [comment]
Hey @zhyncs I am currently working on https://github.com/AI-Hypercomputer/maxtext/pull/1837 Deepseek's Multi-Token Prediction into Maxtext.

**Question:**

As part of the MTP implementation, has the team been able to load the open MTP  module Deepseek V3 weights and analyze the implementation during pre-training and fine-tuning? I am curious to know about any observed behavior?

Specifically I am observing: https://github.com/deepseek-ai/DeepSeek-V3/issues/928
