### ISSUE TITLE
Empty Regex hangs forever

### ISSUE THREAD

**Issue by lucasavila00** [sgl-project/sglang#276]
```python
@function
def filter_question(s):
    s += "<s> [INST] Add 1 and 1. [/INST]"
    s += gen("answer", regex="")
```

An empty regex causes the server to print:
```
Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/home/lucas/oss/sglang/python/sglang/srt/managers/router/model_rpc.py", line 169, in exposed_step
    self.handle_generate_request(recv_req)
  File "/home/lucas/oss/sglang/python/sglang/srt/managers/router/model_rpc.py", line 262, in handle_generate_request
    req.regex_fsm = self.regex_fsm_cache.query(req.sampling_params.regex)
  File "/home/lucas/oss/sglang/python/sglang/srt/constrained/base_cache.py", line 34, in query
    val = _init_with_timer(key)
  File "/home/lucas/oss/sglang/python/sglang/srt/constrained/base_cache.py", line 18, in _init_with_timer
    val = self.init_value(key)
  File "/home/lucas/oss/sglang/python/sglang/srt/constrained/fsm_cache.py", line 13, in init_value
    return RegexFSM(regex, self.outlines_tokenizer)
  File "/home/lucas/.local/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 121, in __init__
    self.states_to_token_maps, self.empty_token_ids = create_states_mapping(
  File "/home/lucas/.local/lib/python3.10/site-packages/outlines/caching.py", line 74, in wrapper
    result = cached_function(*args, **kwargs)
  File "/home/lucas/.local/lib/python3.10/site-packages/outlines/fsm/fsm.py", line 103, in create_states_mapping
    regex_fsm, _ = make_deterministic_fsm(regex_pattern.to_fsm().reduce())
  File "/home/lucas/.local/lib/python3.10/site-packages/outlines/fsm/regex.py", line 165, in make_deterministic_fsm
    new_alphabet = BetterAlphabet(new_symbol_mapping)
  File "/home/lucas/.local/lib/python3.10/site-packages/outlines/fsm/regex.py", line 17, in __init__
    assert anything_else in self._symbol_mapping
AssertionError
```

and the python code of the client hangs forever.

I did the HTTP request directly to SGLang server and the HTTP request never finishes.

**Comment by hnyls2002** [comment]
@lucasavila00 This bug seems to be an `outlines` bug, but they are updating their APIs a lot in the incoming `0.0.35` version, I will look at it when it releases.

**Comment by lucasavila00** [comment]
@hnyls2002 I think we have 2 issues here.

One is the empty regex crashing the interpreter, and the other is the sglang not responding at all.

I'm using "serverless" cloud hosting and the non-response makes the server stay alive until the pre-defined timeout.

Ideally the server should never hang and it should return an error...


I'll try fixing the non-response issue and submit a PR.

**Comment by hnyls2002** [comment]
@lucasavila00  Sorry to cause that, as there would be some unexpected bugs raised when running the server, we don't choose to crash the entire server but just print an error log here:

https://github.com/sgl-project/sglang/blob/ad1dd74673a2e918a39d869865c1830fb634d150/python/sglang/srt/managers/router/model_rpc.py#L185-L186

Even if the above exception happens, our server can still receive other requests, and works well.

But your concern totally makes sense, when a running request comes across an exception, it is actually aborted, so we should let the user know this case.

The real problems are more complex, sometimes a batch of requests get an exception an all of them are aborted or our backend just keep them running in infinite loops, reported the exception again and again.

We will try to figure out this problem, appreciate again for reminding us!
