### ISSUE TITLE
`--enable-flashinfer` fails

### ISSUE THREAD

**Issue by s7ev3n** [sgl-project/sglang#317]
When I turn on flashinfer, it reports the following error:
```
Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 184, in exposed_step
    self.forward_step()
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 199, in forward_step
    self.forward_fill_batch(new_batch)
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 412, in forward_fill_batch
    ) = self.model_runner.forward(
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 488, in forward
    return self.forward_extend(**kwargs)
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 382, in forward_extend
    input_metadata = InputMetadata.create(
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 226, in create
    ret.init_flashinfer_args(tp_size)
  File "/home/wst4sgh/playground/sine/.venv/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 127, in init_flashinfer_args
    self.prefill_wrapper.begin_forward(
TypeError: BatchPrefillWithPagedKVCacheWrapper.begin_forward() missing 1 required positional argument: 'head_dim'
```
sglang: 0.1.13
flashinfer: flashinfer-0.0.3+cu121torch2.1

**Comment by merrymercy** [comment]
It has been fixed by https://github.com/sgl-project/sglang/pull/282.
Could you try the latest main or v0.1.14?
