### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'

### ISSUE THREAD

**Issue by lishuangyuly** [sgl-project/sglang#319]
```
Rank 0: load weight begin.
Rank 0: load weight end.
Rank 0: max_total_num_token=45937, max_prefill_num_token=7656, context_len=4096, 
disable_radix_cache=False, enable_flashinfer=False, disable_regex_jump_forward=False, disable_disk_cache=False, attention_reduce_in_fp32=False
INFO:     Started server process [801902]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
INFO:     127.0.0.1:55578 - "GET /get_model_info HTTP/1.1" 200 OK
new fill batch. #seq: 1. #cached_token: 0. #new_token: 9. #remaining_req: 0. #running_req: 0. tree_cache_hit_rate: 0.00%.
Exception in ModelRpcClient:
Traceback (most recent call last):
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 184, in exposed_step
    self.forward_step()
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 199, in forward_step
    self.forward_fill_batch(new_batch)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 412, in forward_fill_batch
    ) = self.model_runner.forward(
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 488, in forward
    return self.forward_extend(**kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 393, in forward_extend
    return self.model.forward(input_ids, input_metadata.positions, input_metadata)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 269, in forward
    hidden_states = self.model(input_ids, positions, input_metadata, input_embeds)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 239, in forward
    hidden_states, residual = layer(
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 191, in forward
    hidden_states = self.self_attn(
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 140, in forward
    attn_output = self.attn(q, k, v, input_metadata)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/layers/radix_attention.py", line 115, in forward
    return self.extend_forward(q, k, v, input_metadata)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/layers/radix_attention.py", line 48, in extend_forward_triton
    extend_attention_fwd(
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/layers/extend_attention.py", line 241, in extend_attention_fwd
    _fwd_kernel[grid](
  File "<string>", line 63, in _fwd_kernel
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/triton/compiler/compiler.py", line 425, in compile
    so_path = make_stub(name, signature, constants)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/triton/compiler/make_launcher.py", line 39, in make_stub
    so = _build(name, src_path, tmpdir)
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/triton/common/build.py", line 61, in _build
    cuda_lib_dirs = libcuda_dirs()
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/site-packages/triton/common/build.py", line 21, in libcuda_dirs
    libs = subprocess.check_output(["ldconfig", "-p"]).decode()
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/mnt/octave/data/lsy/anaconda3/envs/sgl/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ldconfig'
```
sglang==0.1.13
outlines==0.0.34

**Comment by isaac-vidas** [comment]
This worked for me https://github.com/sgl-project/sglang/issues/41#issuecomment-1899354400

**Comment by lishuangyuly** [comment]
Thanks！The solution works for it！
