### ISSUE TITLE
VLLM version

### ISSUE THREAD

**Issue by eaubin** [sgl-project/sglang#373]
`python -m sglang.launch_server --model-path Mistral-7B-Instruct-v0.2/` fails with 

```
router init state: Traceback (most recent call last):
  File ".venv/lib/python3.9/site-packages/sglang/srt/managers/router/manager.py", line 68, in start_router_process
    model_client = ModelRpcClient(server_args, port_args)
  File ".venv/lib/python3.9/site-packages/sglang/srt/managers/router/model_rpc.py", line 619, in __init__
    self.model_server.exposed_init_model(0, server_args, port_args)
  File ".venv/lib/python3.9/site-packages/sglang/srt/managers/router/model_rpc.py", line 70, in exposed_init_model
    self.model_runner = ModelRunner(
  File ".venv/lib/python3.9/site-packages/sglang/srt/managers/router/model_runner.py", line 287, in __init__
    self.load_model()
  File ".venv/lib/python3.9/site-packages/sglang/srt/managers/router/model_runner.py", line 296, in load_model
    model_class = get_model_cls_by_arch_name(architectures)
  File ".venv/lib/python3.9/site-packages/sglang/srt/managers/router/model_runner.py", line 49, in get_model_cls_by_arch_name
    model_arch_name_to_cls = import_model_classes()
  File ".venv/lib/python3.9/site-packages/sglang/srt/managers/router/model_runner.py", line 42, in import_model_classes
    module = importlib.import_module(name)
  File ".../lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File ".venv/lib/python3.9/site-packages/sglang/srt/models/gemma.py", line 12, in <module>
    from vllm.model_executor.input_metadata import InputMetadata
ModuleNotFoundError: No module named 'vllm.model_executor.input_metadata'
```

on a new install. This seems to be cause by the default install of VLLM 0.4.0.post1. InputMetadata was removed in https://github.com/vllm-project/vllm/commit/925f3332cac488e5ad2dbc8f5c6d5f42d2556816

**Comment by SaddamHusseinsCorgi** [comment]
same problem here. Any update?

**Comment by eaubin** [comment]
@clintonruairi I went back to an vLLM 0.3.3 in the meantime.

**Comment by SaddamHusseinsCorgi** [comment]
If you build sgl from source it solves the problem!

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/blob/21ba3a88a10c3dadb6997320950facfb8c567626/python/pyproject.toml#L24
