### ISSUE TITLE
 typo in  sglang/srt/server.py  Runtime  log_evel

### ISSUE THREAD

**Issue by dhgarcia** [sgl-project/sglang#478]
There is a typo in  sglang/srt/server.py  Runtime

**log_evel** should be **log_level**

`class Runtime:
    def __init__(
        self,
        log_evel: str = "error",
        model_overide_args: Optional[dict] = None,
        *args,
        **kwargs,
    ):
        """See the arguments in server_args.py::ServerArgs"""
        self.server_args = ServerArgs(*args, log_level=log_evel, **kwargs)
`

https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/server.py#L254
https://github.com/sgl-project/sglang/blob/main/python/sglang/srt/server.py#L260

This typo causes an error when using  fastchat.serve.sglang_worker
sglang.srt.server_args.ServerArgs() got multiple values for keyword argument 'log_level'

> python3 -m fastchat.serve.sglang_worker --model-path models/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --multimodal
2024-05-26 14:51:19 | ERROR | stderr | Traceback (most recent call last):
2024-05-26 14:51:19 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-05-26 14:51:19 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-26 14:51:19 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-05-26 14:51:19 | ERROR | stderr |     exec(code, run_globals)
2024-05-26 14:51:19 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastchat/serve/sglang_worker.py", line 290, in <module>
2024-05-26 14:51:19 | ERROR | stderr |     runtime = sgl.Runtime(
2024-05-26 14:51:19 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/sglang/api.py", line 39, in Runtime
2024-05-26 14:51:19 | ERROR | stderr |     return Runtime(*args, **kwargs)
2024-05-26 14:51:19 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/sglang/srt/server.py", line 246, in __init__
2024-05-26 14:51:19 | ERROR | stderr |     self.server_args = ServerArgs(*args, log_level=log_evel, **kwargs)
2024-05-26 14:51:19 | ERROR | stderr | TypeError: sglang.srt.server_args.ServerArgs() got multiple values for keyword argument 'log_level'
2024-05-26 14:51:19 | ERROR | stderr | Exception ignored in: <function Runtime.__del__ at 0x705e40350b80>
2024-05-26 14:51:19 | ERROR | stderr | Traceback (most recent call last):
2024-05-26 14:51:19 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/sglang/srt/server.py", line 331, in __del__
2024-05-26 14:51:19 | ERROR | stderr |     self.shutdown()
2024-05-26 14:51:19 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/sglang/srt/server.py", line 284, in shutdown
2024-05-26 14:51:19 | ERROR | stderr |     if self.pid is not None:
2024-05-26 14:51:19 | ERROR | stderr | AttributeError: 'Runtime' object has no attribute 'pid'

**Comment by dhgarcia** [comment]
Solved by #480 for [v0.1.17](https://github.com/sgl-project/sglang/releases/tag/v0.1.17)
