### ISSUE TITLE
KeyError: 'response', Error with fastchat.serve.sglang_worker  and release v0.1.16  when using multimodal model

### ISSUE THREAD

**Issue by dhgarcia** [sgl-project/sglang#479]
When using fastchat.serve.sglang_worker and v0.1.16 I get error when making a request that includes an image.

> python3 -m fastchat.serve.sglang_worker --model-path models/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --multimodal

> 2024-05-26 16:08:33 | INFO | stdout | INFO:     172.21.0.1:39356 - "POST /worker_get_conv_template HTTP/1.1" 200 OK
2024-05-26 16:08:33 | INFO | stdout | INFO:     172.21.0.1:39364 - "POST /model_details HTTP/1.1" 200 OK
2024-05-26 16:08:33 | INFO | stdout | INFO:     172.21.0.1:39370 - "POST /count_token HTTP/1.1" 200 OK
2024-05-26 16:08:33 | INFO | stdout | INFO:     172.21.0.1:39384 - "POST /worker_generate HTTP/1.1" 500 Internal Server Error
2024-05-26 16:08:33 | ERROR | stderr | ERROR:    Exception in ASGI application
2024-05-26 16:08:33 | ERROR | stderr | Traceback (most recent call last):
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
2024-05-26 16:08:33 | ERROR | stderr |     result = await app(  # type: ignore[func-returns-value]
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-05-26 16:08:33 | ERROR | stderr |     return await self.app(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
2024-05-26 16:08:33 | ERROR | stderr |     await super().__call__(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
2024-05-26 16:08:33 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-05-26 16:08:33 | ERROR | stderr |     raise exc
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-05-26 16:08:33 | ERROR | stderr |     await self.app(scope, receive, _send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-05-26 16:08:33 | ERROR | stderr |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-26 16:08:33 | ERROR | stderr |     raise exc
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-26 16:08:33 | ERROR | stderr |     await app(scope, receive, sender)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
2024-05-26 16:08:33 | ERROR | stderr |     await self.middleware_stack(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
2024-05-26 16:08:33 | ERROR | stderr |     await route.handle(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
2024-05-26 16:08:33 | ERROR | stderr |     await self.app(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
2024-05-26 16:08:33 | ERROR | stderr |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-05-26 16:08:33 | ERROR | stderr |     raise exc
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-05-26 16:08:33 | ERROR | stderr |     await app(scope, receive, sender)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
2024-05-26 16:08:33 | ERROR | stderr |     response = await func(request)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
2024-05-26 16:08:33 | ERROR | stderr |     raw_response = await run_endpoint_function(
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-05-26 16:08:33 | ERROR | stderr |     return await dependant.call(**values)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastchat/serve/sglang_worker.py", line 210, in api_generate
2024-05-26 16:08:33 | ERROR | stderr |     output = await worker.generate_gate(params)
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastchat/serve/sglang_worker.py", line 176, in generate_gate
2024-05-26 16:08:33 | ERROR | stderr |     async for x in self.generate_stream_gate(params):
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastchat/serve/sglang_worker.py", line 166, in generate_stream_gate
2024-05-26 16:08:33 | ERROR | stderr |     async for ret in self.generate_stream(params):
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/fastchat/serve/sglang_worker.py", line 140, in generate_stream
2024-05-26 16:08:33 | ERROR | stderr |     async for out, meta_info in state.text_async_iter(
2024-05-26 16:08:33 | ERROR | stderr |   File "/root/.local/lib/python3.10/site-packages/sglang/lang/interpreter.py", line 768, in text_async_iter
2024-05-26 16:08:33 | ERROR | stderr |     out = str(self.stream_executor.variables[var_name][prev:])
2024-05-26 16:08:33 | ERROR | stderr | KeyError: 'response'

I don't get the error if I use sglang launch_server.

> python3 -m sglang.launch_server --model-path models/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --multimodal

I also don't get this error when I use v0.1.13 of sglang.

**Comment by dhgarcia** [comment]
I imagine this can be more something that fschat would need to update than an issue here but would like to understand what is going on.

**Comment by dmilcevski** [comment]
I get the same error. These are the fastchat lines that throw the error: https://github.com/lm-sys/FastChat/blob/c5223e34babd24c3f9b08205e6751ea6e42c9684/fastchat/serve/sglang_worker.py#L140 and https://github.com/lm-sys/FastChat/blob/c5223e34babd24c3f9b08205e6751ea6e42c9684/fastchat/serve/sglang_worker.py#L127. I am not sure if there is something special here. Just streaming enabled by key and then trying to get the result for this key, and `sglang` throws an error that this key doesn't exist.
