### ISSUE TITLE
 Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "localhost", use "localhost://"

### ISSUE THREAD

**Issue by dmilcevski** [sgl-project/sglang#521]
I am trying the new sglang version v0.1.17 with FastChat and I am getting this error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/FastChat/fastchat/serve/sglang_worker.py", line 17, in <module>
    import sglang as sgl
  File "/sglang/python/sglang/__init__.py", line 30, in <module>
    from sglang.backend.litellm import LiteLLM
  File "/sglang/python/sglang/backend/litellm.py", line 9, in <module>
    import litellm
  File "/usr/local/lib/python3.10/dist-packages/litellm/__init__.py", line 236, in <module>
    module_level_aclient = AsyncHTTPHandler(timeout=request_timeout)
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/custom_httpx/http_handler.py", line 42, in __init__
    self.client = httpx.AsyncClient(
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1458, in __init__
    {URLPattern(key): transport for key, transport in mounts.items()}
  File "/usr/local/lib/python3.10/dist-packages/httpx/_client.py", line 1458, in <dictcomp>
    {URLPattern(key): transport for key, transport in mounts.items()}
  File "/usr/local/lib/python3.10/dist-packages/httpx/_utils.py", line 364, in __init__
    raise ValueError(
ValueError: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "localhost", use "localhost://"
```

**Comment by dmilcevski** [comment]
I was able to solve this issue by changing my `no_proxy` and `NO_PROXY` env variables to be in the format `http://localhost` instead of just `localhost`. However I am getting now this error:

```
2024-06-10 12:36:08 | ERROR | stderr | INFO:     Started server process [3975704]
2024-06-10 12:36:08 | ERROR | stderr | INFO:     Waiting for application startup.
2024-06-10 12:36:08 | ERROR | stderr | INFO:     Application startup complete.
2024-06-10 12:36:08 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
2024-06-10 12:36:08 | ERROR | stderr | Exception in thread Thread-1 (_wait_and_warmup):
2024-06-10 12:36:08 | ERROR | stderr | Traceback (most recent call last):
2024-06-10 12:36:08 | ERROR | stderr |   File "/sglang/python/sglang/srt/server.py", line 246, in _wait_and_warmup
2024-06-10 12:36:08 | ERROR | stderr |     assert res.status_code == 200
2024-06-10 12:36:08 | ERROR | stderr | AssertionError
2024-06-10 12:36:08 | ERROR | stderr |
2024-06-10 12:36:08 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-10 12:36:08 | ERROR | stderr |
2024-06-10 12:36:08 | ERROR | stderr | Traceback (most recent call last):
2024-06-10 12:36:08 | ERROR | stderr |   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-06-10 12:36:08 | ERROR | stderr |     self.run()
2024-06-10 12:36:08 | ERROR | stderr |   File "/usr/lib/python3.10/threading.py", line 953, in run
2024-06-10 12:36:08 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-06-10 12:36:08 | ERROR | stderr |   File "/sglang/python/sglang/srt/server.py", line 250, in _wait_and_warmup
2024-06-10 12:36:08 | ERROR | stderr |     print(f"Initialization failed. warmup error: {e}")
2024-06-10 12:36:08 | ERROR | stderr | UnboundLocalError: local variable 'e' referenced before assignment
2024-06-10 12:36:13 | ERROR | stderr | Traceback (most recent call last):
2024-06-10 12:36:13 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-06-10 12:36:13 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-06-10 12:36:13 | ERROR | stderr |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
2024-06-10 12:36:13 | ERROR | stderr |     exec(code, run_globals)
2024-06-10 12:36:13 | ERROR | stderr |   File "/FastChat/fastchat/serve/sglang_worker.py", line 290, in <module>
2024-06-10 12:36:13 | ERROR | stderr |     runtime = sgl.Runtime(
2024-06-10 12:36:13 | ERROR | stderr |   File "/sglang/python/sglang/api.py", line 39, in Runtime
2024-06-10 12:36:13 | ERROR | stderr |     return Runtime(*args, **kwargs)
2024-06-10 12:36:13 | ERROR | stderr |   File "/sglang/python/sglang/srt/server.py", line 320, in __init__
2024-06-10 12:36:13 | ERROR | stderr |     raise RuntimeError(
2024-06-10 12:36:13 | ERROR | stderr | RuntimeError: Initialization failed. Please see the error messages above.
/usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**Comment by dmilcevski** [comment]
I found the solution for my problem. My `no_proxy` was set to `localhost,127.0.0.1,0.0.0.0`, setting it to `no_proxy=0.0.0.0,localhost,127.0.0.1` fixed the problem. It is really stupid issue coming from `litellm` and `httpx` for that matter. This also causes the worker not being able to connect to `http://127.0.0.1:30000`. This is for users behind corporate proxy.

**Comment by dmilcevski** [comment]
My issue is solved. We can close the ticket.

**Comment by sabretus** [comment]
@dmilcevski The `no_proxy` variable accepts mask, and `0.0.0.0` means "everything", so it should not be in `no_proxy`. I don't understand how you solved this problem, it looks like a bug.

**Comment by perfectspr** [comment]
I also got the same error:
ValueError: Proxy keys should use proper URL forms rather than plain scheme strings. Instead of "localhost", use "localhost://"

it is a bug!

**Comment by bgyoon** [comment]
Another solution is `pip uninstall litellm` if you aren't using litellm.
