### ISSUE TITLE
Qwen 2 7B not working

### ISSUE THREAD

**Issue by sudarshan-kamath** [sgl-project/sglang#522]
This appears on a fresh installation of sglang. Currently using docker container with the following packages

sglang==0.1.17
triton==2.3.0
transformers==4.41.2
torch==2.3.0
vllm==0.4.3
vllm-flash-attn==2.5.8.post2

nvcc --version

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:17:15_PST_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
```

```
CUDA_VISIBLE_DEVICES=2 python -m sglang.launch_server --model-path Qwen/Qwen2-7B-Instruct-GPTQ-Int8 --port 30000
/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[gpu_id=0] Set cuda device.
[gpu_id=0] Init nccl begin.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[gpu_id=0] Load weight begin. avail mem=78.27 GB
INFO 06-10 11:32:21 gptq_marlin.py:133] The model is convertible to gptq_marlin during runtime. Using gptq_marlin kernel.
INFO 06-10 11:32:23 weight_utils.py:207] Using model weights format ['*.safetensors']
[gpu_id=0] Load weight end. type=Qwen2ForCausalLM, avail mem=69.90 GB
[gpu_id=0] Memory pool end. avail mem=6.64 GB
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[gpu_id=0] max_total_num_tokens=1162244, max_prefill_tokens=65536, context_len=32768, 
[gpu_id=0] server_args: enable_flashinfer=False, attention_reduce_in_fp32=False, disable_radix_cache=False, disable_regex_jump_forward=False, disable_disk_cache=False, 
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
INFO:     Started server process [34862]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:30000 (Press CTRL+C to quit)
INFO:     127.0.0.1:33602 - "GET /get_model_info HTTP/1.1" 200 OK
[gpu_id=0] Prefil batch. #new-seq: 1, #new-token: 6, #cached-token: 0, cache hit rate: 0.00%, #running-req: 0, #queue-req: 0
Exception in ModelTpServer:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 188, in exposed_step
    self.forward_step()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 218, in forward_step
    self.forward_decode_batch(self.running_batch)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 572, in forward_decode_batch
    next_token_ids, _ = batch.sample(logits)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/infer_batch.py", line 592, in sample
    sampled_index = torch.multinomial(probs_sort, num_samples=1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

Exception in ControllerSingle:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/manager_single.py", line 93, in start_controller_process
    loop.run_until_complete(controller.loop_for_forward())
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/manager_single.py", line 44, in loop_for_forward
    out_pyobjs = await self.model_client.step(next_step_input)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 753, in _func
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 188, in exposed_step
    self.forward_step()
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 218, in forward_step
    self.forward_decode_batch(self.running_batch)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 572, in forward_decode_batch
    next_token_ids, _ = batch.sample(logits)
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/infer_batch.py", line 592, in sample
    sampled_index = torch.multinomial(probs_sort, num_samples=1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

Killed
```

**Comment by hnyls2002** [comment]
@sudarshan-kamath This is due to the fp16 reduction loss in the attention kernel. Try use the CLI argument `--attention-reduce-in-fp32`.

**Comment by sudarshan-kamath** [comment]
@hnyls2002 Thanks a lot. This works now :) I will close the issue

**Comment by xhjcxxl** [comment]
![image](https://github.com/user-attachments/assets/a998ccbb-40c3-4c94-9511-be6bbcebaad0)
add this args can slove it
