### ISSUE TITLE
[Feature] Support for LLama 3.1

### ISSUE THREAD

**Issue by TimilsinaBimal** [sgl-project/sglang#710]
### Motivation

Since Llama3.1 is already released. I tested with gptq quant and it doesn't work. 
```bash
Traceback (most recent call last):
sglang  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
sglang  |     return _run_code(code, main_globals, None,
sglang  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
sglang  |     exec(code, run_globals)
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/launch_server.py", line 14, in <module>
sglang  |     launch_server(server_args, None)
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/server.py", line 209, in launch_server
sglang  |     tokenizer_manager = TokenizerManager(server_args, port_args, model_overide_args)
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/tokenizer_manager.py", line 67, in __init__
sglang  |     self.hf_config = get_config(
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/hf_transformers_utils.py", line 40, in get_config
sglang  |     config = AutoConfig.from_pretrained(
sglang  |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py", line 989, in from_pretrained
sglang  |     return config_class.from_dict(config_dict, **unused_kwargs)
sglang  |   File "/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py", line 772, in from_dict
sglang  |     config = cls(**config_dict)
sglang  |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 161, in __init__
sglang  |     self._rope_scaling_validation()
sglang  |   File "/usr/local/lib/python3.10/dist-packages/transformers/models/llama/configuration_llama.py", line 182, in _rope_scaling_validation
sglang  |     raise ValueError(
sglang  | ValueError: `rope_scaling` must be a dictionary with two fields, `type` and `factor`, got {'factor': 8.0, 'high_freq_factor': 4.0, 'low_freq_factor': 1.0, 'original_max_position_embeddings': 8192, 'rope_type': 'llama3'}
```

I think it needs some tweaking.

### Additional Resources
Model: https://huggingface.co/ModelCloud/Meta-Llama-3.1-8B-Instruct-gptq-4bit

**Comment by merrymercy** [comment]
do you use the main branch? Which are your sglang and vllm versions?

**Comment by merrymercy** [comment]
It should be supported after https://github.com/sgl-project/sglang/commit/444a02441a50f87d86c406901b3726b323a3fc0f

**Comment by TimilsinaBimal** [comment]
I build the main branch. But didn't work either.
```bash
sglang  | [gpu_id=0] Init nccl begin.
sglang  | [gpu_id=0] Load weight begin. avail mem=21.74 GB
sglang  | Process Process-1:
sglang  | Initialization failed. controller_init_state: Traceback (most recent call last):
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/manager_single.py", line 135, in start_controller_process
sglang  |     controller = ControllerSingle(
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/manager_single.py", line 69, in __init__
sglang  |     self.tp_server = ModelTpServer(
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 72, in __init__
sglang  |     self.model_runner = ModelRunner(
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/model_runner.py", line 96, in __init__
sglang  |     self.load_model()
sglang  |   File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/model_runner.py", line 112, in load_model
sglang  |     vllm_model_config = VllmModelConfig(
sglang  |   File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 166, in __init__
sglang  |     self.max_model_len = _get_and_verify_max_len(
sglang  |   File "/usr/local/lib/python3.10/dist-packages/vllm/config.py", line 1417, in _get_and_verify_max_len
sglang  |     if rope_scaling is not None and rope_scaling["type"] != "su" \
sglang  | KeyError: 'type'
sglang  | 
sglang  | Initialization failed. detoken_init_state: init ok
sglang exited with code 0

```

**Comment by TimilsinaBimal** [comment]
I am able to run the same model using VLLM 0.5.3.post1. But not with sglang.

**Comment by Qubitium** [comment]
@TimilsinaBimal  Strange crash point. Let me check what's going on here.

**Comment by TimilsinaBimal** [comment]
The issue seems to be in the docker file. Currently it installs the sglang package published in pypi, not the one from repo.
I made some tweaks and it's working now! 

```yml

ARG CUDA_VERSION=12.4.1

FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu22.04

ARG CUDA_VERSION=12.4.1
ARG PYTHON_VERSION=3

ENV DEBIAN_FRONTEND=noninteractive

RUN echo 'tzdata tzdata/Areas select America' | debconf-set-selections \
    && echo 'tzdata tzdata/Zones/America select Los_Angeles' | debconf-set-selections \
    && apt-get update -y \
    && apt-get install -y ccache software-properties-common \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update -y \
    && apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-dev python${PYTHON_VERSION}-venv python3-pip \
    && if [ "${PYTHON_VERSION}" != "3" ]; then update-alternatives --install /usr/bin/python3 python3 /usr/bin/python${PYTHON_VERSION} 1; fi \
    && python3 --version \
    && python3 -m pip --version \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN apt-get update -y \
    && apt-get install -y python3-pip git curl sudo

# Workaround for https://github.com/openai/triton/issues/2507 and
# https://github.com/pytorch/pytorch/issues/107960 -- hopefully
# this won't be needed for future versions of this docker image
# or future versions of triton.
RUN ldconfig /usr/local/cuda-$(echo $CUDA_VERSION | cut -d. -f1,2)/compat/
COPY . /sgl-workspace

WORKDIR /sgl-workspace

RUN pip3 --no-cache-dir install --upgrade pip

RUN pip3 install -e "python[all]"

RUN pip3 --no-cache-dir uninstall -y triton triton-nightly \
    && pip3 --no-cache-dir install --no-deps --index-url https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/Triton-Nightly/pypi/simple/ triton-nightly \
    && pip3 --no-cache-dir install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.3/

ENV DEBIAN_FRONTEND=interactive

```

Thanks everyone for quick response!
