### ISSUE TITLE
Qwen2-72B-Instruct-GPTQ-Int4 KeyError: 'rope_type

### ISSUE THREAD

**Issue by bravelll** [sgl-project/sglang#746]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

python -m sglang.launch_server --model-path /u01/liuys/.cache/modelscope/hub/qwen/Qwen2-72B-Instruct-GPTQ-Int4 --enable-p2p-check --port 30000  --tp 4 --mem-fraction-static 0.7 --quantization gptq
error:
Traceback (most recent call last):
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/site-packages/sglang/launch_server.py", line 14, in <module>
    launch_server(server_args)
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/site-packages/sglang/srt/server.py", line 257, in launch_server
    tokenizer_manager = TokenizerManager(server_args, port_args, model_overide_args)
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/site-packages/sglang/srt/managers/tokenizer_manager.py", line 75, in __init__
    self.context_len = get_context_length(self.hf_config)
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/site-packages/sglang/srt/hf_transformers_utils.py", line 76, in get_context_length
    if config.rope_scaling["rope_type"] == "llama3":
KeyError: 'rope_type'

### Reproduction

python -m sglang.launch_server --model-path /u01/liuys/.cache/modelscope/hub/qwen/Qwen2-72B-Instruct-GPTQ-Int4 --enable-p2p-check --port 30000  --tp 4 --mem-fraction-static 0.7 --quantization gptq

### Environment

```Shell
rtx3090
```

**Comment by zhyncs** [comment]
cc @Ying1123

**Comment by merrymercy** [comment]
Fixed by https://github.com/sgl-project/sglang/commit/679ebcbbdc37e129b16d305660514dfafda0f7ca. Please try the main branch!

**Comment by bravelll** [comment]
> Fixed by [679ebcb](https://github.com/sgl-project/sglang/commit/679ebcbbdc37e129b16d305660514dfafda0f7ca). Please try the main branch!由 . 修复。请尝试主分支！
follow error：
INFO:     Started server process [2684970]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:30000 (Press CTRL+C to quit)
Initialization failed. warmup error: 
Exception in thread Thread-1 (_wait_and_warmup):
Traceback (most recent call last):
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/u01/liuys/anaconda3/envs/sglang-env/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/u02/liuys/sglang/python/sglang/srt/server.py", line 356, in _wait_and_warmup
    raise e
  File "/u02/liuys/sglang/python/sglang/srt/server.py", line 351, in _wait_and_warmup
    assert res.status_code == 200
AssertionError
