### ISSUE TITLE
[Bug] Assertion error: Exception in ModelTpServer: This happens when we do return_log_prob=True

### ISSUE THREAD

**Issue by SatyanarayanPati** [sgl-project/sglang#747]
### Checklist

- [x] 1. I have searched related issues but cannot get the expected help.
- [x] 2. The bug has not been fixed in the latest version.
- [x] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

When I have given the argument return_log_probe=True. Its showing the below message. I am getting this in sagemaker environment the instance type is 

### Reproduction

INFO:     127.0.0.1:59618 - "POST /generate/ HTTP/1.1" 307 Temporary Redirect
[gpu_id=0] Prefill batch. #new-seq: 1, #new-token: 2, #cached-token: 42, cache hit rate: 45.26%, #running-req: 0, #queue-req: 0
Exception in ModelTpServer:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 186, in exposed_step
    self.forward_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 216, in forward_step
    self.forward_decode_batch(self.running_batch)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 567, in forward_decode_batch
    output = self.model_runner.forward(batch, ForwardMode.DECODE)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/model_runner.py", line 334, in forward
    return self.forward_decode(batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/model_runner.py", line 274, in forward_decode
    return self.cuda_graph_runner.replay(batch)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/cuda_graph_runner.py", line 188, in replay
    assert not batch.return_logprob
AssertionError
 
Exception in ControllerSingle:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/manager_single.py", line 151, in start_controller_process
    controller.loop_for_forward()
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/manager_single.py", line 88, in loop_for_forward
    out_pyobjs = self.tp_server.exposed_step(recv_reqs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 186, in exposed_step
    self.forward_step()
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 216, in forward_step
    self.forward_decode_batch(self.running_batch)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 567, in forward_decode_batch
    output = self.model_runner.forward(batch, ForwardMode.DECODE)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/model_runner.py", line 334, in forward
    return self.forward_decode(batch)
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/model_runner.py", line 274, in forward_decode
    return self.cuda_graph_runner.replay(batch)
  File "/opt/conda/lib/python3.10/site-packages/sglang/srt/managers/controller/cuda_graph_runner.py", line 188, in replay
    assert not batch.return_logprob
AssertionError
 
Killed

### Environment

```Shell
/bin/sh: 1: /usr/local/cuda/bin/nvcc: not found
Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
CUDA available: True
GPU 0: NVIDIA A10G
CUDA_HOME: /usr/local/cuda
NVCC: Not Available
CUDA Driver Version: 535.183.01
PyTorch: 2.3.1+cu121
sglang: 0.2.1
flashinfer: 0.1.1+cu121torch2.3
requests: 2.31.0
tqdm: 4.66.4
numpy: 1.26.4
aiohttp: 3.9.5
fastapi: 0.110.3
hf_transfer: 0.1.8
huggingface_hub: 0.24.2
interegular: 0.3.3
packaging: 23.2
pillow: Module Not Found
psutil: 5.9.8
pydantic: 2.8.2
uvicorn: 0.29.0
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.3.post1
openai: 1.37.1
anthropic: 0.31.2
NVIDIA Topology: 
        GPU0    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      0-15    0               N/A
 
Legend:
 
  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks
 
ulimit soft: 65536
```

**Comment by StevenZHB** [comment]
Same problem when I set sampling_params = {"temperature":1,"n":5, "logprobs":1， “max_tokens”:10}, and the engine crashes.
When I set sampling_params = {"temperature":1,"n":5, "logprobs":1， “max_tokens”:1}, the engine will not crash.

**Comment by merrymercy** [comment]
- Short-term fix: please try to add `--disable-cuda-graph` when you launch the server.
- Long-term fix: I will have a PR to fix this soon this weekend.

**Comment by merrymercy** [comment]
This should be fixed by https://github.com/sgl-project/sglang/pull/775
