### ISSUE TITLE
[Bug]  Unable to install on mac

### ISSUE THREAD

**Issue by xianbaoqian** [sgl-project/sglang#758]
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

It requires vllm which can only be installed on Linux

Collecting vllm==0.5.3.post1 (from sglang[all])
  Using cached vllm-0.5.3.post1.tar.gz (874 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      <string>:56: RuntimeWarning: Failed to get commit hash:
      Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
      Traceback (most recent call last):
        File "/Users/wangtz/projects/sglang/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/wangtz/projects/sglang/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/wangtz/projects/sglang/env/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/x2/6_05fh3x5gd8bb3v0wym9gyr0000gn/T/pip-build-env-rhsrhje3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/x2/6_05fh3x5gd8bb3v0wym9gyr0000gn/T/pip-build-env-rhsrhje3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/x2/6_05fh3x5gd8bb3v0wym9gyr0000gn/T/pip-build-env-rhsrhje3/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 65, in <module>
      AssertionError: vLLM only supports Linux platform (including WSL).
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is 

### Reproduction

pip install "sglang[all]"

### Environment

```Shell
Mac Apple Silicon
```

**Comment by zhyncs** [comment]
Currently, only MVIDIA GPUs are supported, Mac is not supported. Thanks.

**Comment by xianbaoqian** [comment]
I manually removed the vllm dependency and it works now.

**Comment by Springrx** [comment]
> I manually removed the vllm dependency and it works now.

How can I remove the vllm dependency manually?
