### ISSUE TITLE
[Bug] Prompt logprobs support

### ISSUE THREAD

**Issue by StevenZHB** [sgl-project/sglang#782]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

sglang supports logprobs but does it support outputting prompt log logprobs?
I tried with the sampling params {'echo':True}, and it raised error:
ERROR:    Exception in ASGI application
Traceback (most recent call last):
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
            result = await app(  # type: ignore[func-returns-value]
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
            return await self.app(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
            await super().__call__(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
            await self.middleware_stack(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
            raise exc
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
            await self.app(scope, receive, _send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
            await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
            raise exc
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
            await app(scope, receive, sender)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
            await self.middleware_stack(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
            await route.handle(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
            await self.app(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
            await wrap_app_handling_exceptions(app, request)(scope, receive, send)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
            raise exc
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
            await app(scope, receive, sender)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
            response = await func(request)
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
            raw_response = await run_endpoint_function(
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
            return await dependant.call(**values)
      File "/sglang/python/sglang/srt/server.py", line 132, in openai_v1_completions
            return await v1_completions(tokenizer_manager, raw_request)
      File "/sglang/python/sglang/srt/openai_api/adapter.py", line 217, in v1_completions
            text = request.prompt + text

### Reproduction

sampling_params = {'temperature': 0, 'top_p': 1.0, 'best_of': 1, 'max_tokens': 1, 'n': 1, 'stop': ['<|eot_id|>'], 'logprobs': 1}
to get the prompt logprobs from llama3-8B-instruct

### Environment

```Shell
python3 -m sglang.check_env
Python: 3.9.17 (main, Jul  5 2023, 20:41:20) [GCC 11.2.0]
CUDA available: True
GPU 0,1: NVIDIA A800-SXM4-80GB
CUDA_HOME: /zhanghongbo/CUDA/cuda-11_8
NVCC: Cuda compilation tools, release 11.8, V11.8.89
CUDA Driver Version: 525.105.17
525.105.17
PyTorch: 2.3.0+cu118
flashinfer: 0.1.1+cu118torch2.3
requests: 2.31.0
tqdm: 4.66.1
numpy: 1.25.0
aiohttp: 3.8.5
fastapi: 0.110.0
hf_transfer: Module Not Found
huggingface_hub: 0.23.2
interegular: 0.3.3
packaging: 24.0
pillow: Module Not Found
psutil: 5.9.8
pydantic: 2.5.0
uvicorn: 0.23.2
uvloop: 0.19.0
zmq: 25.1.2
vllm: 0.5.3.post1
openai: 1.30.0
anthropic: Module Not Found
litellm: Module Not Found
NVIDIA Topology: 
        GPU0    GPU1    NIC0    CPU Affinity    NUMA Affinity
GPU0     X      NV8     SYS     48-63   3
GPU1    NV8      X      SYS     48-63   3
NIC0    SYS     SYS      X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0


ulimit soft: 1048576
```

**Comment by Ying1123** [comment]
It works fine for me. Could you provide more reproducible instructions?
```
python -m sglang.launch_server --model-path meta-llama/Meta-Llama-3-8B
```

```
curl -X POST http://0.0.0.0:30000/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "Meta-Llama-3-8B",
"prompt": "Please introduce yourself",
"max_tokens": 1,
"n": 1,
"temperature": 0,
"logprobs": 1,
"echo": true,
"stop": ["<|eot_id|>"]
}'
```

```
{"id":"3df5b00a608f4529ba08e6fcf70a0b00","object":"text_completion","created":1722167227,"model":"Meta-Llama-3-8B","choices":[{"index":0,"text":"Please introduce yourself and","logprobs":{"text_offset":[-1,-1,-1,-1,-1],"token_logprobs":[null,-7.716526508331299,-7.56634521484375,-0.22307726740837097,-0.9105053544044495],"tokens":["<|begin_of_text|>","Please"," introduce"," yourself"," and"],"top_logprobs":[null,{"Question":-1.1852765083312988},{" note":-2.003844976425171},{" yourself":-0.22307726740837097},{" and":-0.9105053544044495}]},"finish_reason":"FINISH_LENGTH: 1"}],"usage":{"prompt_tokens":4,"total_tokens":5,"completion_tokens":1}}
```

**Comment by StevenZHB** [comment]
The error happens when I pass list to the server:
curl -X POST http://0.0.0.0:30000/v1/completions \
-H "Content-Type: application/json" \
-d '{
"model": "Meta-Llama-3-8B",
"prompt": ["Please introduce yourself"],
"max_tokens": 1,
"n": 1,
"temperature": 0,
"logprobs": 1,
"echo": true,
"stop": ["<|eot_id|>"]
}'
the error is like below:
File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app                                          
            raise exc
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app                                          
            await app(scope, receive, sender)                                                                                                                                      
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/starlette/routing.py", line 74, in app                                                             
            response = await func(request)                                                                                                                                         
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app                                                              
            raw_response = await run_endpoint_function(                                                                                                                            
      File "/miniconda3/envs/steven/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function                                            
            return await dependant.call(**values)                                                                                                                                  
      File "/sglang/python/sglang/srt/server.py", line 132, in openai_v1_completions                                                                               
            return await v1_completions(tokenizer_manager, raw_request)                                                                                                            
      File "/sglang/python/sglang/srt/openai_api/adapter.py", line 217, in v1_completions                                                                          
            text = request.prompt + text                                                                                                                                           
TypeError: can only concatenate list (not "str") to list

When I set echo=False and it's fine

**Comment by merrymercy** [comment]
Can you only pass a single prompt? Or do you really want to pass a list for batch inference?

**Comment by StevenZHB** [comment]
Yes, the server works fine when I input a string. However, when I attempt batch inference, the server reports an error. This issue was normal when I tried it on vllm; when inputting m prompts and specifying n outputs for each, vllm would place m*n outputs in the 'choices'. The reason I want to use batch inference is that the throughput would be higher than sending multiple individual prompts at the same time.

**Comment by merrymercy** [comment]
@StevenZHB I will work on a fix soon in one day. In the meanwhile, you can try to use multiple python thread to send the requests in parallel. It will give you almost the same throughput!

**Comment by Ying1123** [comment]
Fixed by https://github.com/sgl-project/sglang/pull/791
