### ISSUE TITLE
[Bug]  Cannot profile with nsight

### ISSUE THREAD

**Issue by rexmxw02** [sgl-project/sglang#827]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

When I use nsys to perform perf analysis, this error is reported. How can I solve it
![image](https://github.com/user-attachments/assets/5a953be2-09c8-41e5-9b9f-00945b909d7f)
Exception in run_tp_server:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 739, in run_tp_server
    model_server = ModelTpServer(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/tp_worker.py", line 72, in __init__
    self.model_runner = ModelRunner(
  File "/usr/local/lib/python3.10/dist-packages/sglang/srt/managers/controller/model_runner.py", line 83, in __init__
    initialize_model_parallel(tensor_model_parallel_size=self.tp_size)
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 889, in initialize_model_parallel
    _TP = init_model_parallel_group(group_ranks,
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 732, in init_model_parallel_group
    return GroupCoordinator(
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/parallel_state.py", line 176, in __init__
    self.pynccl_comm = PyNcclCommunicator(
  File "/usr/local/lib/python3.10/dist-packages/vllm/distributed/device_communicators/pynccl.py", line 74, in __init__
    dist.broadcast(tensor, src=ranks[0], group=group)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/c10d_logger.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/distributed_c10d.py", line 2144, in broadcast
    work.wait()
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:525] Read error [33.120.6.16]:22914: Connection reset by peer

### Reproduction

nsys launch --trace=cublas,cuda,cudnn,nvtx --show-output=true --cuda-graph-trace node --session-new sglang python3 -m sglang.launch_server --model-path model/ --host 0.0.0.0 --port 30000 --tp-size 8

### Environment

```Shell
sglang0.2.6 && sglang0.2.0
```

**Comment by Ying1123** [comment]
Can you run without nsight?

**Comment by rexmxw02** [comment]
Turning off nsys can start, but opening nsys will cause it to freeze

**Comment by rexmxw02** [comment]
> Can you run without nsight?
Turning off nsys can start, but opening nsys will cause it to freeze

**Comment by zhyncs** [comment]
ref https://github.com/sgl-project/sglang/issues/845 Due to the issue being duplicated, this one will be closed for now. It can be reopened if needed. Thank you.
