### ISSUE TITLE
[Bug] sglang.launch_server error on V100 (disable flashinfer)

### ISSUE THREAD

**Issue by AlanShao-zy** [sgl-project/sglang#831]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

hi, I got error when I tried to run

```bash
python3 -m sglang.launch_server --model-path /root/hf_model/Qwen/Qwen2-72B-Instruct-GPTQ-Int4 --dtype half --trust-remote-code --tp-size 8 --disable-flashinfer
```

error:
```bash
Exception in run_tp_server:
Traceback (most recent call last):
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 756, in run_tp_server
    model_server.exposed_step(recv_reqs)
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 190, in exposed_step
    self.forward_step()
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 206, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/controller/tp_worker.py", line 450, in forward_prefill_batch
    next_token_ids = batch.sample(output.next_token_logits)
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/sglang/srt/managers/controller/infer_batch.py", line 702, in sample
    batch_next_token_ids, success = top_k_top_p_sampling_from_probs(
  File "/root/miniconda3/envs/sgl/lib/python3.10/site-packages/flashinfer/sampling.py", line 266, in top_k_top_p_sampling_from_probs
    return _kernels.top_k_top_p_sampling_from_probs(
RuntimeError: TopKTopPSamplingFromProbs failed with error code no kernel image is available for execution on the device
```

### Reproduction

```bash
python3 -m sglang.launch_server --model-path /root/hf_model/Qwen/Qwen2-72B-Instruct-GPTQ-Int4 --dtype half --trust-remote-code --tp-size 8 --disable-flashinfer
```

### Environment

```Shell
env:


Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: Tesla V100-SXM2-32GB
CUDA_HOME: /usr/local/cuda-12.2
NVCC: Cuda compilation tools, release 12.2, V12.2.140
CUDA Driver Version: 535.129.03
535.129.03
535.129.03
535.129.03
535.129.03
535.129.03
535.129.03
535.129.03
PyTorch: 2.3.1+cu121
sglang: 0.2.6
flashinfer: 0.1.2+cu121torch2.3
requests: 2.32.3
tqdm: 4.66.4
numpy: 1.26.4
aiohttp: 3.9.5
fastapi: 0.111.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.3
interegular: 0.3.3
packaging: 24.1
pillow: Module Not Found
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.3
uvloop: 0.19.0
zmq: 26.0.3
vllm: 0.5.3.post1
openai: 1.37.1
anthropic: 0.32.0
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      NV1     NV1     NV2     PHB     PHB     NV2     PHB     0-95    0               N/A
GPU1    NV1      X      NV2     NV1     PHB     PHB     PHB     NV2     0-95    0               N/A
GPU2    NV1     NV2      X      NV2     NV1     PHB     PHB     PHB     0-95    0               N/A
GPU3    NV2     NV1     NV2      X      PHB     NV1     PHB     PHB     0-95    0               N/A
GPU4    PHB     PHB     NV1     PHB      X      NV2     NV1     NV2     0-95    0               N/A
GPU5    PHB     PHB     PHB     NV1     NV2      X      NV2     NV1     0-95    0               N/A
GPU6    NV2     PHB     PHB     PHB     NV1     NV2      X      NV1     0-95    0               N/A
GPU7    PHB     NV2     PHB     PHB     NV2     NV1     NV1      X      0-95    0               N/A

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 65535


model:
Qwen2-72B-Instruct-GPTQ-Int4
```

**Comment by Ying1123** [comment]
Try to add `--disable-flashinfer --disable-flashinfer-sampling` https://github.com/sgl-project/sglang/blob/1edd4e07d6ad52f4f63e7f6beaa5987c1e1cf621/python/sglang/srt/server_args.py#L338-L347

**Comment by shawHuaZe** [comment]
你好，我因为一些原因无法下载flashinner，所以我按照说明添加了--disable-flashinfer --disable-flashinfer-sampling，但还是无法启动服务器。
我的启动命令为
```sh
python -m sglang.launch_server --model-path "/root/autodl-tmp/work/Model/Mistral-7B-Instruct" --port 30000 --disable-flashinfer --disable-flashinfer-sampling
```
报错为：
```tex
Traceback (most recent call last):
  File "/root/miniconda3/envs/sglang/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/envs/sglang/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/launch_server.py", line 5, in <module>
    from sglang.srt.server import launch_server
  File "/root/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/server.py", line 47, in <module>
    from sglang.srt.managers.controller_multi import (
  File "/root/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/controller_multi.py", line 30, in <module>
    from sglang.srt.managers.controller_single import (
  File "/root/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/controller_single.py", line 25, in <module>
    from sglang.srt.managers.tp_worker import (
  File "/root/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 32, in <module>
    from sglang.srt.managers.io_struct import (
  File "/root/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/io_struct.py", line 25, in <module>
    from sglang.srt.managers.schedule_batch import BaseFinishReason
  File "/root/miniconda3/envs/sglang/lib/python3.10/site-packages/sglang/srt/managers/schedule_batch.py", line 25, in <module>
    from flashinfer.sampling import top_k_top_p_sampling_from_probs
ModuleNotFoundError: No module named 'flashinfer'
```
我不知道是为什么

**Comment by zhyncs** [comment]
@shawHuaZe FlashInfer isn't currently lazy import, and we have no plans to adopt lazy import, making its installation essential. For those with an sm70 architecture, LMDeploy is recommended. If you're on an sm75 architecture like T4, you should install FlashInfer and enable `--disable-flashinfer --disable-flashinfer-sampling`. With an sm80+ architecture, simply install FlashInfer and stick to the default settings.

**Comment by Ais0n** [comment]
@zhyncs Hi I came across the same issue when running `python3 -m sglang.launch_server --model-path liuhaotian/llava-v1.5-7b --tokenizer-path llava-hf/llava-1.5-7b-hf --port 30000 --disable-flashinfer --disable-flashinfer-sampling`. I have followed your advice to add the two parameters but it didn't work. I used the same card (Tesla V100-32GB) with the issue author. BTW sticking to the default settings also didn't work (a similar 'no kernel graph available' error will be thrown)

Error:
```
CUDA Error: no kernel image is available for execution on the device (209) /tmp/build-via-sdist-f2_5l_cn/flashinfer-0.1.4+cu124torch2.4/include/flashinfer/norm.cuh: line 112 at function cudaLaunchKernel((void*)kernel, nblks, nthrs, args, smem_size, stream)
Exception in ModelTpServer:
Traceback (most recent call last):
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 222, in exposed_step
    self.forward_step()
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 238, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 452, in forward_prefill_batch
    output = self.model_runner.forward(batch, ForwardMode.EXTEND)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 393, in forward
    return self.forward_extend_multi_modal(batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 382, in forward_extend_multi_modal
    return self.model.forward(
           ^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llava.py", line 255, in forward
    return self.language_model(
           ^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llama2.py", line 314, in forward
    hidden_states = self.model(input_ids, positions, input_metadata, input_embeds)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llama2.py", line 281, in forward
    hidden_states, residual = layer(
                              ^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llama2.py", line 228, in forward
    hidden_states = self.input_layernorm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/vllm/model_executor/custom_op.py", line 13, in forward
    return self._forward_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/layers/layernorm.py", line 45, in forward_cuda
    out = rmsnorm(x, self.weight.data, self.variance_epsilon)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/flashinfer/norm.py", line 52, in rmsnorm
    return _kernels.rmsnorm(input, weight, eps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: RMSNorm failed with error code no kernel image is available for execution on the device

Exception in ControllerSingle:
Traceback (most recent call last):
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/controller_single.py", line 166, in start_controller_process
    controller.loop_for_forward()
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/controller_single.py", line 103, in loop_for_forward
    out_pyobjs = self.tp_server.exposed_step(recv_reqs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 222, in exposed_step
    self.forward_step()
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 238, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/managers/tp_worker.py", line 452, in forward_prefill_batch
    output = self.model_runner.forward(batch, ForwardMode.EXTEND)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 393, in forward
    return self.forward_extend_multi_modal(batch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/model_executor/model_runner.py", line 382, in forward_extend_multi_modal
    return self.model.forward(
           ^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llava.py", line 255, in forward
    return self.language_model(
           ^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llama2.py", line 314, in forward
    hidden_states = self.model(input_ids, positions, input_metadata, input_embeds)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llama2.py", line 281, in forward
    hidden_states, residual = layer(
                              ^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/models/llama2.py", line 228, in forward
    hidden_states = self.input_layernorm(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/vllm/model_executor/custom_op.py", line 13, in forward
    return self._forward_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/sglang/srt/layers/layernorm.py", line 45, in forward_cuda
    out = rmsnorm(x, self.weight.data, self.variance_epsilon)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jet/home/yhuang16/.conda/envs/sgl/lib/python3.11/site-packages/flashinfer/norm.py", line 52, in rmsnorm
    return _kernels.rmsnorm(input, weight, eps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: RMSNorm failed with error code no kernel image is available for execution on the device
```

Environment:
```
Python: 3.11.9
CUDA available: True
GPU 0: Tesla V100-SXM2-32GB
CUDA_HOME: /opt/packages/cuda/v12.4.0
NVCC: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
PyTorch: 2.4.0+cu124
sglang: 0.2.12
flashinfer: 0.1.4+cu124torch2.4
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.3
fastapi: 0.112.0
hf_transfer: 0.1.8
huggingface_hub: 0.24.5
interegular: 0.3.3
packaging: 24.1
pillow: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.5
uvloop: 0.19.0
zmq: 0.0.0
vllm: 0.5.4
openai: 1.40.5
anthropic: 0.33.1
```
