### ISSUE TITLE
OOM Error on A40 GPU [Jupyter notebook]

### ISSUE THREAD

**Issue by aflah02** [sgl-project/sglang#86]
I was trying the following code sample (adapted from the discussion in https://github.com/sgl-project/sglang/issues/81) - 

```
import sglang as sgl
from sglang import function, gen, set_default_backend, Runtime

@sgl.function
def tool_use(s, question):
    s += "To answer this question: " + question + ", "
    s += "I need to use a " + sgl.gen("tool", choices=["calculator", "web browser"]) + ". "
    if s["tool"] == "calculator":
        s += "The math expression is" + sgl.gen("expression")
    elif s["tool"] == "web browser":
        s += "The website url is" + sgl.gen("url")

runtime = Runtime(model_path='Model_Saves/teknium--OpenHermes-2.5-Mistral-7B')
set_default_backend(runtime)

driver_tool_use()
```
   
I firstly got the same error as described here: https://github.com/sgl-project/sglang/issues/41#issuecomment-1899347676
I then followed Solution 2 from this [comment](https://github.com/sgl-project/sglang/issues/41#issuecomment-1899354400) and the error disappeared but I now get an OOM error even though I have `46068 MiB` of space on the GPU which is more than what a 7B model needs. On checking with `nvidia-smi` I see `41158MiB` in use. I'm running this in a Jupyter notebook.

The error - 

```
router init state: Traceback (most recent call last):
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/managers/router/manager.py", line 68, in start_router_process
    model_client = ModelRpcClient(server_args, port_args)
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 480, in __init__
    self.model_server.exposed_init_model(0, server_args, port_args)
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/managers/router/model_rpc.py", line 53, in exposed_init_model
    self.model_runner = ModelRunner(
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 233, in __init__
    self.load_model()
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/managers/router/model_runner.py", line 278, in load_model
    model = model_class(
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 258, in __init__
    self.model = LlamaModel(config, linear_method)
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 218, in __init__
    [
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 219, in <listcomp>
    LlamaDecoderLayer(config, i, linear_method)
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 167, in __init__
    self.mlp = LlamaMLP(
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/sglang/srt/models/llama2.py", line 49, in __init__
    self.down_proj = RowParallelLinear(
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 495, in __init__
    self.linear_weights = self.linear_method.create_weights(
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/vllm/model_executor/layers/linear.py", line 55, in create_weights
    weight = Parameter(torch.empty(output_size_per_partition,
  File "/NS/llm-1/nobackup/afkhan/anaconda3/envs/peft_mem/lib/python3.10/site-packages/torch/utils/_device.py", line 77, in __torch_function__
    return func(*args, **kwargs)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 44.39 GiB of which 77.62 MiB is free. Process 535546 has 40.19 GiB memory in use. Including non-PyTorch memory, this process has 4.11 GiB memory in use. Of the allocated memory 3.80 GiB is allocated by PyTorch, and 15.38 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

detoken init state: init ok

```

**Comment by merrymercy** [comment]
According to the error message, the GPU memory is occupied by other processes. 

You can try to kill them by https://github.com/sgl-project/sglang/blob/9e037c822ccabaf593c0145a9d8377f177e22ff9/test/killall_python.sh#L1

**Comment by aflah02** [comment]
Thanks for sharing the script @merrymercy 
However, when I start the run the GPU is empty so everything occupying GPU space (which is a single process) must be coming from the code in the script. Wouldn't running this just kill the notebook?

**Comment by merrymercy** [comment]
Did you use pytorch in the notebook before launching the sglang runtime?
If so, please try to launch the sglang runtime before you use any GPU library.

By default, sglang runtime will occupy all GPU memory. If you want the runtime to only use a portion of the GPU memory, you can set `mem_fraction_static`.

```
runtime = Runtime(model_path="meta-llama/Llama-2-7b-chat-hf", mem_fraction_static=0.7)
```

**Comment by aflah02** [comment]
Nope I did not use any other library apart from sglang in the notebook. The first cell I executed contained the code I shared. I'll try setting the `mem_fraction_static`. Maybe that would help!

**Comment by aflah02** [comment]
Running it from the notebook did not work but running it on the terminal and making calls from a notebook does work. Not sure why though.
