### ISSUE TITLE
[Bug] 运行sglang.launch_server报错：cannot import name 'default_dump_dir' from 'triton.runtime.cache'

### ISSUE THREAD

**Issue by NoobPythoner** [sgl-project/sglang#881]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/sglang/launch_server.py", line 5, in <module>
    from sglang.srt.server import launch_server
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/sglang/srt/server.py", line 46, in <module>
    from sglang.srt.hf_transformers_utils import get_tokenizer
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/sglang/srt/hf_transformers_utils.py", line 35, in <module>
    from sglang.srt.utils import is_multimodal_model
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/sglang/srt/utils.py", line 40, in <module>
    from triton.runtime.cache import (
ImportError: cannot import name 'default_dump_dir' from 'triton.runtime.cache' (/home/gtlm/.local/lib/python3.11/site-packages/triton/runtime/cache.py

### Reproduction

python -m sglang.launch_server --model-path ./Meta-Llama-3-8B-Instruct --port 8000

### Environment

```Shell
ubuntu 22.04
python-3.11
torch                                            2.3.1
torchaudio                                       2.3.1+cu121
torchvision                                      0.18.1
tornado                                          6.4
tox                                              4.14.1
tqdm                                             4.66.2
tqdm-multiprocess                                0.0.11
traitlets                                        5.14.2
transformers                                     4.43.3
transformers-stream-generator                    0.0.5
triton                                           2.3.1
sglang                                           0.2.7

cuda 12.2
```

**Comment by merrymercy** [comment]
update triton and torch version or try our docker image?
