### ISSUE TITLE
[Bug]  部署gemma-2-2b，open AI客户端发送请求时，报错：System role not supported

### ISSUE THREAD

**Issue by NoobPythoner** [sgl-project/sglang#892]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

INFO:     192.168.137.9:50376 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/sglang/srt/server.py", line 157, in openai_v1_chat_completions
    return await v1_chat_completions(tokenizer_manager, raw_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/sglang/srt/openai_api/adapter.py", line 720, in v1_chat_completions
    adapted_request, request = v1_chat_generate_request(all_requests, tokenizer_manager)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/sglang/srt/openai_api/adapter.py", line 602, in v1_chat_generate_request
    prompt = tokenizer_manager.tokenizer.apply_chat_template(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1833, in apply_chat_template
    rendered_chat = compiled_template.render(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gtlm/anaconda3/envs/llama_factory/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 1914, in raise_exception
    raise TemplateError(message)
jinja2.exceptions.TemplateError: System role not supported

### Reproduction

python -m sglang.launch_server --model-path gemma-2-2b-it --port 8081 --mem-fraction-static 0.7 --host 0.0.0.0

### Environment

```Shell
ubuntu 22.04 ,python3.11
sglang                                           0.2.7
shapely                                          2.0.4
shellingham                                      1.5.4
shortuuid                                        1.0.13
shtab                                            1.7.1
simplejson                                       3.19.2
six                                              1.16.0
smart-open                                       7.0.4
sniffio                                          1.3.1
socksio                                          1.0.0
sortedcontainers                                 2.4.0
soundfile                                        0.12.1
soupsieve                                        2.5
soxr                                             0.3.7
SQLAlchemy                                       2.0.28
sqlitedict                                       2.1.0
sse-starlette                                    2.0.0
stack-data                                       0.6.3
starlette                                        0.36.3
statsmodels                                      0.14.2
StrEnum                                          0.4.15
striprtf                                         0.0.26
svgwrite                                         1.4.3
swift                                            2.32.0
swifter                                          1.4.0
sympy                                            1.12
tabledata                                        1.3.3
tabulate                                         0.9.0
tcolorpy                                         0.1.4
tenacity                                         8.2.3
tensorboard                                      2.15.2
tensorboard-data-server                          0.7.2
tensorflow                                       2.15.0
tensorflow-estimator                             2.15.0
tensorflow-hub                                   0.16.1
tensorflow-io-gcs-filesystem                     0.36.0
termcolor                                        2.3.0
terminado                                        0.18.1
texttable                                        1.7.0
textual                                          0.70.0
tf_keras                                         2.16.0
threadpoolctl                                    3.3.0
tika                                             2.6.0
tiktoken                                         0.7.0
timm                                             0.9.16
tinycss2                                         1.2.1
tokenizers                                       0.19.1
toml                                             0.10.2
tomli                                            2.0.1
tomlkit                                          0.12.0
toolz                                            0.12.1
torch                                            2.3.1
torchaudio                                       2.3.1+cu121
torchvision                                      0.18.1
tornado                                          6.4
tox                                              4.14.1
tqdm                                             4.66.2
tqdm-multiprocess                                0.0.11
traitlets                                        5.14.2
transformers                                     4.43.3
transformers-stream-generator                    0.0.5
triton-nightly                                   3.0.0.post20240716052845
trl                                              0.8.1
```

**Comment by NoobPythoner** [comment]
不支持"System" 这种role？

**Comment by Ying1123** [comment]
gemma model does not support system prompts. You can move the system prompt to the first user message.
